### ISSUE TITLE
请教实现syscall的问题

### ISSUE THREAD

**Issue by gofmt** [zhkl0228/unidbg#100]
[ WARN][11:23:26][ARMSyscallHandler:448] handleInterrupt intno=2, NR=-1073754376, svcNumber=0x110, PC=unicorn@0xfffe0194, syscall=null
unicorn.UnicornException
	at com.github.unidbg.linux.android.dvm.DalvikVM$17.handle(DalvikVM.java:303)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:111)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:351)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:442)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:196)
	at com.wx.Weixin.emulateFunction(Weixin.java:108)
	at com.wx.Weixin.<init>(Weixin.java:60)
	at com.wx.Weixin.main(Weixin.java:75)

出现这样的错误,是不是需要自己实现0x110号syscall方法?

**Comment by zhkl0228** [comment]
看着像是模拟java出问题

**Comment by gofmt** [comment]
谢谢,确实是模拟Thread调用栈出问题了.
