### ISSUE TITLE
getMethodID中methodMap.put有值，但是getMethod读取时却为null

### ISSUE THREAD

**Issue by xiaohaidao1** [zhkl0228/unidbg#109]
代码及so已发到您的邮箱

getMethodID中methodMap.put有值，但是getMethod读取时为null。读取错误信息如下：

RX@0x400a2711[libpdd_secure.so]0xa2711
JNIEnv->GetStaticObjectField(class android/content/Context, TELEPHONY_SERVICE Ljava/lang/String; => "phone") was called from RX@0x400a2805[libpdd_secure.so]0xa2805
JNIEnv->FindClass(com/xunmeng/pinduoduo/service_hook/SystemServiceHooker) was called from RX@0x400a2537[libpdd_secure.so]0xa2537
JNIEnv->FindClass(com/xunmeng/pinduoduo/service_hook/SystemServiceHooker) was called from RX@0x400a3715[libpdd_secure.so]0xa3715
JNIEnv->CallStaticObjectMethodV(class com/xunmeng/pinduoduo/service_hook/SystemServiceHooker, getService("phone") => android.telephony.TelephonyManager@3aa9e816) was called from RX@0x400a38d7[libpdd_secure.so]0xa38d7
JNIEnv->FindClass(com/android/internal/telephony/ITelephony$Stub) was called from RX@0x40089175[libpdd_secure.so]0x89175
JNIEnv->CallStaticObjectMethod(class com/android/internal/telephony/ITelephony$Stub, asInterface(Landroid/os/IBinder;)Lcom/android/internal/telephony/ITelephony;) was called from RX@0x400891c7[libpdd_secure.so]0x891c7
JNIEnv->FindClass(java/lang/Object) was called from RX@0x400a2325[libpdd_secure.so]0xa2325
hash--1:3039392124  put DvmMethod---1 com.github.unidbg.linux.android.dvm.DvmMethod@21de60b4
hash--: 3039392124  get method--- null
JNIEnv->FindClass(android/content/Context) was called from 
UnicornPointer was called from RX@0x400a334d[libpdd_secure.so]0xa334d
[17:44:00 352]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:444) - handleInterrupt intno=2, NR=-1073753960, svcNumber=0x114, PC=unicorn@0xfffe01d4, syscall=null
unicorn.UnicornException: dvmObject=android.telephony.TelephonyManager@3aa9e816, dvmClass=class android/telephony/TelephonyManager, jmethodID=unicorn@0xb529717c
	at com.github.unidbg.linux.android.dvm.DalvikVM$21.handle(DalvikVM.java:384)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:111)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:108)
	at unicorn.Unicorn.emu_start(Native  #####Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:351)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:448)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:196)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:222)
	at com.xunmeng.pinduoduo.secure.SecureNative.nativeGenerate2Local(SecureNative.java:128)
	at com.xunmeng.pinduoduo.secure.SecureNative.main(SecureNative.java:117)

**Comment by xuzc** [comment]
解决了吗，我也遇到了类似的问题

**Comment by nubuntu** [comment]
> Is it solved, I also had a similar issue

I have similar issue, how did you solve?
