### ISSUE TITLE
更新后项目不能用了

### ISSUE THREAD

**Issue by weststarqp** [zhkl0228/unidbg#110]
不管我如何设置,都会提示:
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.github.unidbg.AbstractEmulator.<init>(AbstractEmulator.java:80)
	at com.github.unidbg.arm.AbstractARMEmulator.<init>(AbstractARMEmulator.java:47)
	at com.github.unidbg.linux.android.AndroidARMEmulator.<init>(AndroidARMEmulator.java:50)
	at com.github.unidbg.linux.android.AndroidARMEmulator.<init>(AndroidARMEmulator.java:42)
	at com.bytedance.frameworks.core.encrypt.TTEncrypt.<init>(TTEncrypt.java:41)
	at com.bytedance.frameworks.core.encrypt.TTEncrypt.main(TTEncrypt.java:61)
Caused by: java.lang.IllegalStateException: java.io.IOException: Couldn't load library library unicorn_java
	at unicorn.Unicorn.<clinit>(Unicorn.java:161)
	... 6 more
Caused by: java.io.IOException: Couldn't load library library unicorn_java
	at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:141)
	at unicorn.Unicorn.<clinit>(Unicorn.java:159)
	... 6 more
Caused by: java.lang.UnsatisfiedLinkError: no unicorn_java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:136)
	... 7 more

**Comment by zhkl0228** [comment]
去除-Djava.library.path跟-Djna.library.path试下

**Comment by weststarqp** [comment]
去除过,还是一样的效果,
另外尝试过提取unicorn.jar包中的windows_64的dll,设置其所在 java.library.path的路径,或者手动加载该dll文件,均提示:
Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\WorkSpace\GitHub\unidbg\lib\unicorn_java.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.bytedance.frameworks.core.encrypt.TTEncrypt.main(TTEncrypt.java:62)

**Comment by zhkl0228** [comment]
windows版本号多少，回头测试下

**Comment by weststarqp** [comment]
Microsoft Windows [版本 10.0.18362.592]
麻烦大佬了

**Comment by shLuckyCode** [comment]
> 去除-Djava.library.path跟-Djna.library.path试下

我测试去除后本机能运行，编译成jar包后放到其他机器上就会报和上面一样的错误

**Comment by qiang** [comment]
我更新项目后提示 com.github.zhkl0228:capstone 的3.0.7 版本找不到，我给降级到了3.0.6
```
      <dependency>
            <groupId>com.github.zhkl0228</groupId>
            <artifactId>capstone</artifactId>
            <version>3.0.7</version>
        </dependency>
```

**Comment by zhkl0228** [comment]
已提交代码，更新后再试下

> Microsoft Windows [版本 10.0.18362.592]
> 麻烦大佬了

**Comment by weststarqp** [comment]
> 已提交代码，更新后再试下
> 
> > Microsoft Windows [版本 10.0.18362.592]
> > 麻烦大佬了

运行通过,又跑起来了,十分感谢!
