### ISSUE TITLE
通过反射匿名类、接口获取手机里deviceId在unidbg里怎么修复

### ISSUE THREAD

**Issue by lvygcode** [zhkl0228/unidbg#111]
1)unidbg尝试加载第三方app的so，在获取手机deviceId会挂掉
  JNIEnv->CallStaticObjectMethod(class com/android/internal/telephony/ITelephony$Stub, asInterface(Landroid/os/IBinder;)Lcom/android/internal/telephony/ITelephony;) was called from RX@0x400891c7[xxxx.so]0x891c7
UnicornPointer was called from RX@0x400891c7[xxxx.so]0x891c7
WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:444) - handleInterrupt intno=2, NR=-1073753312, svcNumber=0x12c, PC=unicorn@0xfffe0354, syscall=null
java.lang.AbstractMethodError: com/android/internal/telephony/ITelephony$Stub->asInterface(Landroid/os/IBinder;)Lcom/android/internal/telephony/ITelephony;
	at com.github.unidbg.linux.android.dvm.AbstractJni.callStaticObjectMethod(AbstractJni.java:273)
	at com.xunmeng.pinduoduo.secure.SecureNative.callStaticObjectMethod(SecureNative.java:357)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callStaticObjectMethod(DvmMethod.java:28)
	at com.github.unidbg.linux.android.dvm.DalvikVM$45.handle(DalvikVM.java:991)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:111)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:108)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:351)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:448)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:196)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:235)
	
	
  ITelephony是Android源码里的一个@hide的接口。asInterface是Bind转换机制。手机模块基本用的AIDL通信机制。这种类型类在unidbg如何绕过?

2)附以用上边类型获取deviceId的java方法(猜测的)

public static String getDeviceIdLevel1(Context context) {
        try {
            Class ServiceManager = Class.forName("android.os.ServiceManager");
            Method getService = ServiceManager.getDeclaredMethod("getService", String.class);
            getService.setAccessible(true);
            IBinder binder = (IBinder) getService.invoke(null, Context.TELEPHONY_SERVICE);
            Class Stub = Class.forName("com.android.internal.telephony.ITelephony$Stub");
            Method asInterface = Stub.getDeclaredMethod("asInterface", IBinder.class);
            asInterface.setAccessible(true);
            Object binderProxy = asInterface.invoke(null, binder);
            try {
                Method getDeviceId = binderProxy.getClass().getDeclaredMethod("getDeviceId", String.class);
                if (getDeviceId != null) {
                    return (String) getDeviceId.invoke(binderProxy, context.getPackageName());
                }
            } catch (Exception e) {

            }
            Method getDeviceId = binderProxy.getClass().getDeclaredMethod("getDeviceId");
            if (getDeviceId != null) {
                return (String) getDeviceId.invoke(binderProxy);
            }
        } catch (Exception e) {
            //();
        }
        return "";
    }

**Comment by zhkl0228** [comment]
vm.resolveClass("com/android/internal/telephony/ITelephony").newObject

**Comment by apxar** [comment]
我也遇到这个了，还有错 @lvygcode ，你解决了吗～

**Comment by sanqudui8ban** [comment]
我解决了，确实unidbg有问题，要改系统代码

**Comment by wengxianxun** [comment]
Class ServiceManager = Class.forName("android.os.ServiceManager");   这个类我这么调用会提示ClassNotFoundException

**Comment by Jayce-Jian** [comment]
> 我解决了，确实unidbg有问题，要改系统代码

@sanqudui8ban 可以说下是什么解决的吗

**Comment by sanqudui8ban** [comment]
过了几年了，不记得了。

**Comment by lvygcode** [comment]
1)unidbg尝试加载第三方app的so，在获取手机deviceId会挂掉 JNIEnv->CallStaticObjectMethod(class
