### ISSUE TITLE
调用so其他函数没问题，调用这个sign(Ljava/lang/String;[B)Ljava/lang/String;报错

### ISSUE THREAD

**Issue by FuChen2018** [zhkl0228/unidbg#125]
at com.github.unidbg.linux.android.dvm.DalvikVM$74.handle(DalvikVM.java:1545)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:111)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:339)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:436)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:196)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:58)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:220)

请教一下大佬们什么问题啊emmm....

**Comment by FuChen2018** [comment]
emmm..作者大大方便回复一下吗..我比较菜..

**Comment by FuChen2018** [comment]
JNIEnv->FindClass(com/izuiyou/network/NetCrypto) was called from RX@0x400495d5[libnet_crypto.so]0x495d5
JNIEnv->RegisterNatives(com/izuiyou/network/NetCrypto, RW@0x4017d010[libnet_crypto.so]0x17d010, 8) was called from RX@0x400495e5[libnet_crypto.so]0x495e5
RegisterNative(com/izuiyou/network/NetCrypto, native_init()V, RX@0x40049633[libnet_crypto.so]0x49633)
RegisterNative(com/izuiyou/network/NetCrypto, encodeAES([B)[B, RX@0x40049645[libnet_crypto.so]0x49645)
RegisterNative(com/izuiyou/network/NetCrypto, decodeAES([BZ)[B, RX@0x400496e5[libnet_crypto.so]0x496e5)
RegisterNative(com/izuiyou/network/NetCrypto, sign(Ljava/lang/String;[B)Ljava/lang/String;, RX@0x4004982d[libnet_crypto.so]0x4982d)
RegisterNative(com/izuiyou/network/NetCrypto, getProtocolKey()Ljava/lang/String;, RX@0x400499b5[libnet_crypto.so]0x499b5)
RegisterNative(com/izuiyou/network/NetCrypto, setProtocolKey(Ljava/lang/String;)V, RX@0x40049a15[libnet_crypto.so]0x49a15)
RegisterNative(com/izuiyou/network/NetCrypto, registerDID([B)Z, RX@0x40049a91[libnet_crypto.so]0x49a91)
RegisterNative(com/izuiyou/network/NetCrypto, generateSign([B)Ljava/lang/String;, RX@0x40049b23[libnet_crypto.so]0x49b23)
Find native function Java_com_izuiyou_network_NetCrypto_native_init()V => RX@0x40049633[libnet_crypto.so]0x49633

Exception in thread "main" java.lang.IllegalArgumentException: find method failed: sign(Ljava/lang/String;[B)Ljava/lang/String;
	at com.github.unidbg.linux.android.dvm.DvmClass.findNativeFunction(DvmClass.java:211)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:39)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:35)


f9的

**Comment by FuChen2018** [comment]
JNIEnv->FindClass(com/izuiyou/network/NetCrypto) was called from RX@0x400495d5[libnet_crypto.so]0x495d5
JNIEnv->RegisterNatives(com/izuiyou/network/NetCrypto, RW@0x4017d010[libnet_crypto.so]0x17d010, 8) was called from RX@0x400495e5[libnet_crypto.so]0x495e5
RegisterNative(com/izuiyou/network/NetCrypto, native_init()V, RX@0x40049633[libnet_crypto.so]0x49633)
RegisterNative(com/izuiyou/network/NetCrypto, encodeAES([B)[B, RX@0x40049645[libnet_crypto.so]0x49645)
RegisterNative(com/izuiyou/network/NetCrypto, decodeAES([BZ)[B, RX@0x400496e5[libnet_crypto.so]0x496e5)
RegisterNative(com/izuiyou/network/NetCrypto, sign(Ljava/lang/String;[B)Ljava/lang/String;, RX@0x4004982d[libnet_crypto.so]0x4982d)
RegisterNative(com/izuiyou/network/NetCrypto, getProtocolKey()Ljava/lang/String;, RX@0x400499b5[libnet_crypto.so]0x499b5)
RegisterNative(com/izuiyou/network/NetCrypto, setProtocolKey(Ljava/lang/String;)V, RX@0x40049a15[libnet_crypto.so]0x49a15)
RegisterNative(com/izuiyou/network/NetCrypto, registerDID([B)Z, RX@0x40049a91[libnet_crypto.so]0x49a91)
RegisterNative(com/izuiyou/network/NetCrypto, generateSign([B)Ljava/lang/String;, RX@0x40049b23[libnet_crypto.so]0x49b23)
Find native function Java_com_izuiyou_network_NetCrypto_native_init()V => RX@0x40049633[libnet_crypto.so]0x49633
Find native function Java_com_izuiyou_network_NetCrypto_sign(Ljava/lang/String;[B)Ljava/lang/String; => RX@0x4004982d[libnet_crypto.so]0x4982d
JNIEnv->GetArrayLength([B@13fee20c => 32) was called from RX@0x40065789[libnet_crypto.so]0x65789
JNIEnv->GetStringUtfChars("http://api.izuiyou.com/verifycode/register") was called from RX@0x4006505f[libnet_crypto.so]0x6505f
JNIEnv->ReleaseStringUTFChars("http://api.izuiyou.com/verifycode/register") was called from RX@0x4006507b[libnet_crypto.so]0x6507b
JNIEnv->FindClass(com/izuiyou/common/base/BaseApplication) was called from RX@0x4004cd89[libnet_crypto.so]0x4cd89
[03:46:59 833]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:447) - handleInterrupt intno=2, NR=-1073744336, svcNumber=0x12b, PC=unicorn@0xfffe0344, syscall=null
java.lang.NullPointerException
	at com.github.unidbg.linux.android.dvm.DvmClass.getStaticMethodID(DvmClass.java:82)
	at com.github.unidbg.linux.android.dvm.DalvikVM$44.handle(DalvikVM.java:948)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:111)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:339)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:436)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:196)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:58)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:220)
	at com.com.zuiyou.Nmsl.sign(Nmsl.java:88)
	at com.com.zuiyou.Nmsl.main(Nmsl.java:65)
destroy

Process finished with exit code 0

**Comment by FuChen2018** [comment]
JNIEnv->FindClass(com/izuiyou/network/NetCrypto) was called from RX@0x400495d5[libnet_crypto.so]0x495d5
JNIEnv->RegisterNatives(com/izuiyou/network/NetCrypto, RW@0x4017d010[libnet_crypto.so]0x17d010, 8) was called from RX@0x400495e5[libnet_crypto.so]0x495e5
RegisterNative(com/izuiyou/network/NetCrypto, native_init()V, RX@0x40049633[libnet_crypto.so]0x49633)
RegisterNative(com/izuiyou/network/NetCrypto, encodeAES([B)[B, RX@0x40049645[libnet_crypto.so]0x49645)
RegisterNative(com/izuiyou/network/NetCrypto, decodeAES([BZ)[B, RX@0x400496e5[libnet_crypto.so]0x496e5)
RegisterNative(com/izuiyou/network/NetCrypto, sign(Ljava/lang/String;[B)Ljava/lang/String;, RX@0x4004982d[libnet_crypto.so]0x4982d)
RegisterNative(com/izuiyou/network/NetCrypto, getProtocolKey()Ljava/lang/String;, RX@0x400499b5[libnet_crypto.so]0x499b5)
RegisterNative(com/izuiyou/network/NetCrypto, setProtocolKey(Ljava/lang/String;)V, RX@0x40049a15[libnet_crypto.so]0x49a15)
RegisterNative(com/izuiyou/network/NetCrypto, registerDID([B)Z, RX@0x40049a91[libnet_crypto.so]0x49a91)
RegisterNative(com/izuiyou/network/NetCrypto, generateSign([B)Ljava/lang/String;, RX@0x40049b23[libnet_crypto.so]0x49b23)
Find native function Java_com_izuiyou_network_NetCrypto_native_init()V => RX@0x40049633[libnet_crypto.so]0x49633
Find native function Java_com_izuiyou_network_NetCrypto_sign(Ljava/lang/String;[B)Ljava/lang/String; => RX@0x4004982d[libnet_crypto.so]0x4982d
JNIEnv->GetArrayLength([B@158d2680 => 32) was called from RX@0x40065789[libnet_crypto.so]0x65789
JNIEnv->GetStringUtfChars("http://api.baidu.com") was called from RX@0x4006505f[libnet_crypto.so]0x6505f
JNIEnv->ReleaseStringUTFChars("http://api.baidu.com") was called from RX@0x4006507b[libnet_crypto.so]0x6507b
JNIEnv->FindClass(com/izuiyou/common/base/BaseApplication) was called from RX@0x4004cd89[libnet_crypto.so]0x4cd89
[03:53:40 290]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:447) - handleInterrupt intno=2, NR=-1073744336, svcNumber=0x12b, PC=unicorn@0xfffe0344, syscall=null
java.lang.NullPointerException
	at com.github.unidbg.linux.android.dvm.DvmClass.getStaticMethodID(DvmClass.java:82)
	at com.github.unidbg.linux.android.dvm.DalvikVM$44.handle(DalvikVM.java:948)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:111)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:339)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:436)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:196)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:58)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:220)
	at com.com.zuiyou.Nmsl.sign(Nmsl.java:88)
	at com.com.zuiyou.Nmsl.main(Nmsl.java:65)
destroy
Disconnected from the target VM, address: '127.0.0.1:43717', transport: 'socket'

Process finished with exit code 0

**Comment by zhkl0228** [comment]
Context类声明为com/izuiyou/common/base/BaseApplication试下

**Comment by FuChen2018** [comment]
> Context类声明为com/izuiyou/common/base/BaseApplication试下

    Nmsl(boolean logging) {


        emulator = new AndroidARMEmulator("cn.xiaochuankeji.tieba"); 
        final Memory memory = emulator.getMemory(); 
        memory.setLibraryResolver(new AndroidResolver(23)); 
        vm = emulator.createDalvikVM(new File(APK_PATH)); 
        vm.setVerbose(logging); 
        DalvikModule dm = vm.loadLibrary("net_crypto", false); /
        dm.callJNI_OnLoad(emulator); 
        module = dm.getModule(); 
        TTEncryptUtils = vm.resolveClass("com/izuiyou/network/NetCrypto");
    }
    void destroy() throws IOException {
        emulator.close();
        System.out.println("destroy");

    }
    public static void main(String[] args) throws Exception {
        Nmsl test = new Nmsl(true);
        test.native_init();
        test.sign();
        test.destroy();
    }
    public  void native_init() throws IOException {
        TTEncryptUtils.callStaticJniMethod(emulator,"native_init()V");
    }
    public synchronized String sign() throws IOException {
        String a = "http://api.baidu.com";
        String b = "c20dd5d5d5d5d5d5d5d55f5f5f5f5f5f0f252220358ba247b73dd496aec1f448";
        Number ret =TTEncryptUtils.callStaticJniMethod(emulator,"sign(Ljava/lang/String;[B)Ljava/lang/String;",new StringObject(vm,a),new ByteArray(hexToByteArray(b)));
        long hash = ret.intValue() & 0xffffffffL;
        StringObject array = vm.getObject(hash);
        return array.getValue();
    }


代码应该怎么改啊。。大佬能不能指明一下。。我比较菜。。。麻烦大佬了

**Comment by zhkl0228** [comment]
vm.setJni

**Comment by FuChen2018** [comment]
> vm.setJni

JNIEnv->FindClass(com/izuiyou/network/NetCrypto) was called from RX@0x400495d5[libnet_crypto.so]0x495d5
JNIEnv->RegisterNatives(com/izuiyou/network/NetCrypto, RW@0x4017d010[libnet_crypto.so]0x17d010, 8) was called from RX@0x400495e5[libnet_crypto.so]0x495e5
RegisterNative(com/izuiyou/network/NetCrypto, native_init()V, RX@0x40049633[libnet_crypto.so]0x49633)
RegisterNative(com/izuiyou/network/NetCrypto, encodeAES([B)[B, RX@0x40049645[libnet_crypto.so]0x49645)
RegisterNative(com/izuiyou/network/NetCrypto, decodeAES([BZ)[B, RX@0x400496e5[libnet_crypto.so]0x496e5)
RegisterNative(com/izuiyou/network/NetCrypto, sign(Ljava/lang/String;[B)Ljava/lang/String;, RX@0x4004982d[libnet_crypto.so]0x4982d)
RegisterNative(com/izuiyou/network/NetCrypto, getProtocolKey()Ljava/lang/String;, RX@0x400499b5[libnet_crypto.so]0x499b5)
RegisterNative(com/izuiyou/network/NetCrypto, setProtocolKey(Ljava/lang/String;)V, RX@0x40049a15[libnet_crypto.so]0x49a15)
RegisterNative(com/izuiyou/network/NetCrypto, registerDID([B)Z, RX@0x40049a91[libnet_crypto.so]0x49a91)
RegisterNative(com/izuiyou/network/NetCrypto, generateSign([B)Ljava/lang/String;, RX@0x40049b23[libnet_crypto.so]0x49b23)
Find native function Java_com_izuiyou_network_NetCrypto_native_init()V => RX@0x40049633[libnet_crypto.so]0x49633
Find native function Java_com_izuiyou_network_NetCrypto_sign(Ljava/lang/String;[B)Ljava/lang/String; => RX@0x4004982d[libnet_crypto.so]0x4982d
JNIEnv->GetArrayLength([B@799f10e1 => 32) was called from RX@0x40065789[libnet_crypto.so]0x65789
JNIEnv->GetStringUtfChars("http://api.baidu.com") was called from RX@0x4006505f[libnet_crypto.so]0x6505f
JNIEnv->ReleaseStringUTFChars("http://api.baidu.com") was called from RX@0x4006507b[libnet_crypto.so]0x6507b
JNIEnv->FindClass(com/izuiyou/common/base/BaseApplication) was called from RX@0x4004cd89[libnet_crypto.so]0x4cd89
[20:00:19 895]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:447) - handleInterrupt intno=2, NR=-1073744444, svcNumber=0x12d, PC=unicorn@0xfffe0364, syscall=null
java.lang.AbstractMethodError: com/izuiyou/common/base/BaseApplication->getAppContext()Landroid/content/Context;
	at com.github.unidbg.linux.android.dvm.AbstractJni.callStaticObjectMethodV(AbstractJni.java:310)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callStaticObjectMethodV(DvmMethod.java:37)
	at com.github.unidbg.linux.android.dvm.DalvikVM$46.handle(DalvikVM.java:989)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:111)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:339)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:436)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:196)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:58)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:220)
	at com.com.zuiyou.Nmsl.sign(Nmsl.java:83)
	at com.com.zuiyou.Nmsl.main(Nmsl.java:61)



我是 vm.setJni(this) 的 报这个错误   java.lang.AbstractMethodError: com/izuiyou/common/base/BaseApplication->getAppContext()Landroid/content/Context;


不知道怎么样来解决。。 vm.setJni  怎么来搞大佬说的这个【 Context类声明为com/izuiyou/common/base/BaseApplication】 麻烦大佬给个代码。。帮帮我这个菜

**Comment by FuChen2018** [comment]
app校验，没初始化的问题。
