### ISSUE TITLE
抖音的有测试过么？

### ISSUE THREAD

**Issue by lauyoume** [zhkl0228/unidbg#13]
```
[17:28:09 783]  WARN [cn.banny.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:346) - handleInterrupt intno=2, NR=1467298506, svcNumber=0x122, PC=unicorn@0xfffe015c, syscall=null
java.lang.AbstractMethodError: java/security/cert/CertificateFactory->getInstance(Ljava/lang/String;)Ljava/security/cert/CertificateFactory;
	at cn.banny.unidbg.linux.android.dvm.AbstractJni.callStaticObjectMethodV(AbstractJni.java:183)
	at cn.banny.unidbg.linux.android.dvm.DvmMethod.callStaticObjectMethodV(DvmMethod.java:35)
	at cn.banny.unidbg.linux.android.dvm.DalvikVM$35.handle(DalvikVM.java:626)
	at cn.banny.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:69)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:204)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:290)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:193)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:43)
```
像这种应该这么解决

**Comment by lauyoume** [comment]
之前还有一个这个错误，我通过重写方法解决，是不是类似这样。
```
[19:10:05 026]  WARN [cn.banny.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:346) - handleInterrupt intno=2, NR=1467298506, svcNumber=0x10d, PC=unicorn@0xfffe00b4, syscall=null
java.lang.AbstractMethodError: java/io/ByteArrayInputStream-><init>([B)V
	at cn.banny.unidbg.linux.android.dvm.AbstractJni.newObjectV(AbstractJni.java:261)
	at com.douyin.DouyinHelper.newObjectV(DouyinHelper.java:100)
```

```
    @Override
    public DvmObject newObjectV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {

        switch (signature) {
            case "java/io/ByteArrayInputStream-><init>([B)V":
                ByteArray bytes = vaList.getObject(0);
                ByteArrayInputStream input = new ByteArrayInputStream(bytes.getValue());
                System.out.println("byte input stream" + bytes.getValue());

                return new ByteArrayInputStreamObject(vm, input);
        }
        return super.newObjectV(vm, dvmClass, signature, vaList);
    }
```

**Comment by zhkl0228** [comment]
是的，类似这样重写，实现对应的jni调用
