### ISSUE TITLE
java.lang.AbstractMethodError: sa_family=-1666383870

### ISSUE THREAD

**Issue by lizihang** [zhkl0228/unidbg#134]
这个错误要怎么处理呢？
[00:29:36 622]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:447) - handleInterrupt intno=2, NR=290, svcNumber=0x0, PC=RX@0x401bfaf0[libc.so]0x41af0, syscall=null
java.lang.AbstractMethodError: sa_family=-1666383870
	at com.github.unidbg.unix.file.UdpSocket.sendto(UdpSocket.java:126)
	at com.github.unidbg.unix.UnixSyscallHandler.sendto(UnixSyscallHandler.java:428)
	at com.github.unidbg.linux.ARMSyscallHandler.sendto(ARMSyscallHandler.java:1337)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:376)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:339)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:436)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:196)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.AndroidElfLoader.runThread(AndroidElfLoader.java:81)
	at com.bytedance.frameworks.core.encrypt.OTest.<init>(OTest.java:157)
	at com.bytedance.frameworks.core.encrypt.OTest.main(OTest.java:175)

============================
还有就是希望可以实现UdpSocket中的：
int SIOCGIWAP = 0x8B15;
int SIOCGIFADDR = 0x8915;

**Comment by zhkl0228** [comment]
依照aosp源码实现
