### ISSUE TITLE
测试百度网盘so时报错

### ISSUE THREAD

**Issue by Erope** [zhkl0228/unidbg#140]
测试的是10.1.14版本  https://wppkg.baidupcs.com/issue/netdisk/apk/BaiduNetdisk_10.1.14.apk  
so是libnetdisk-security.so  
代码如下
```
package com.baidu;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Module;
import com.github.unidbg.linux.android.AndroidARMEmulator;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.*;
import com.github.unidbg.memory.Memory;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;

//百度app
public class baidu extends AbstractJni {

    //ARM模拟器
    private final AndroidEmulator emulator;
    //vm
    private final VM vm;
    //载入的模块
    private final Module module;

    private final DvmClass TTEncryptUtils;

    private final boolean logging;

    //初始化

    @Override
    public DvmObject callStaticObjectMethodV(BaseVM vm, DvmClass dvmObject, String signature, VaList vaList) {
        switch (signature) {
            case "com/baidu/netdisk/security/URLHandler->getSK()Ljava/lang/String;":
                return new StringObject(vm, "ZNlxtg792T2ZQQ41eD9I7bich5f3zh5GT5puZr0vNtQ=");
            case "com/baidu/netdisk/security/URLHandler->getDeviceID()Ljava/lang/String;":
                return new StringObject(vm, "383530E8740684A3ECAC1D6A530A3516|0");
            case "android/content/Context->getPackageName()Ljava/lang/String;": {
                String packageName = vm.getPackageName();
                if (packageName != null) {
                    return new StringObject(vm, packageName);
                }
                break;
            }
        }

        return super.callStaticObjectMethodV(vm, dvmObject, signature, vaList);
    }

    public baidu() throws IOException {
        //创建毒进程，这里其实可以不用写的，我这里是随便写的，使用app本身的进程就可以绕过进程检测
        emulator = new AndroidARMEmulator("com.baidu.netdisk");
        Memory memory = emulator.getMemory();
        //作者支持19和23两个sdk
        memory.setLibraryResolver(new AndroidResolver(23));


        //创建DalvikVM，利用apk本身，可以为null
        //如果用apk文件加载so的话，会自动处理签名方面的jni，具体可看AbstractJni,这就是利用apk加载的好处
        vm = emulator.createDalvikVM(new File("src/test/resources/du.apk"));
        vm.setJni(this);
        this.logging = true;
        vm.setVerbose(logging);
        //加载so，使用armv8-64速度会快很多
        DalvikModule dm = vm.loadLibrary(new File("src/test/resources/libnetdisk-security.so"), false);
        //调用jni
        dm.callJNI_OnLoad(emulator);
        module = dm.getModule();

        //Jni调用的类，加载so
        TTEncryptUtils = vm.resolveClass("com/baidu/netdisk/security/URLHandler");
    }


    //关闭模拟器
    private void destroy() throws IOException {
        emulator.close();
        System.out.println("destroy");
    }

    public static void main(String[] args) throws IOException {
        baidu t = new baidu();
        t.encodeByte();
        t.destroy();
    }

    private String encodeByte() {
        //调试
        // 这里还支持gdb调试，
        //emulator.attach(DebuggerType.GDB_SERVER);
        //附加调试器
//        emulator.attach(DebuggerType.SIMPLE);
//        emulator.traceCode();
        //这里是打断点，原地址0x00005028->新地址0x40005028 新地址需要改成0x4
//        emulator.attach().addBreakPoint(null, 0x40001188);//encode地址
//        emulator.attach().addBreakPoint(null, 0x40000D10);
        //获取encodeByte地址
        Object custom = null;
        DvmObject context = vm.resolveClass("android/content/Context").newObject(custom);
        Number ret = TTEncryptUtils.callStaticJniMethod(emulator, "handlerURL(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
                //传参，这里需要两个字符串，所以就传入两个参数
                vm.addLocalObject(context),
                vm.addLocalObject(new StringObject(vm, "https://pan.baidu.com/rest/2.0/pcs/adx?m=tab&w=1080&h=2210&d=android&v=14310&devuid=0&clienttype=1&channel=android_10_Redmi%20K20%20Pro%20Premium%20Edition_bd-netdisk_1018849x&version=10.1.14&vip=1&firstlaunchtime=1589625679&time=1589687497872&network_type=wifi&apn_id=1_0&freeisp=0&queryfree=0")),
                vm.addLocalObject(new StringObject(vm, "bdusstest")),
                vm.addLocalObject(new StringObject(vm, "123456789")));
        //ret 返回的是地址，
        long result = ret.intValue() & 0xffffffffL;
        //或得其值
        StringObject str = vm.getObject(result);
        System.out.println(str.getValue());
        return str.getValue();
    }
}
```
日志
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=49891:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/tools.jar:/Users/wjh/unidbg/target/test-classes:/Users/wjh/unidbg/target/classes:/Users/wjh/.m2/repository/com/github/zhkl0228/unicorn/1.0.9/unicorn-1.0.9.jar:/Users/wjh/.m2/repository/org/scijava/native-lib-loader/2.3.4/native-lib-loader-2.3.4.jar:/Users/wjh/.m2/repository/com/github/zhkl0228/capstone/3.0.8/capstone-3.0.8.jar:/Users/wjh/.m2/repository/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar:/Users/wjh/.m2/repository/com/github/zhkl0228/keystone/0.9.2/keystone-0.9.2.jar:/Users/wjh/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar:/Users/wjh/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/wjh/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/wjh/.m2/repository/net/dongliu/apk-parser/2.6.4/apk-parser-2.6.4.jar:/Users/wjh/.m2/repository/io/kaitai/kaitai-struct-runtime/0.8/kaitai-struct-runtime-0.8.jar:/Users/wjh/.m2/repository/com/googlecode/plist/dd-plist/1.23/dd-plist-1.23.jar:/Users/wjh/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/wjh/.m2/repository/junit/junit/3.8.2/junit-3.8.2.jar:/Users/wjh/.m2/repository/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar:/Users/wjh/.m2/repository/org/slf4j/slf4j-log4j12/1.7.26/slf4j-log4j12-1.7.26.jar:/Users/wjh/.m2/repository/com/alibaba/fastjson/1.2.60/fastjson-1.2.60.jar com.baidu.baidu
objc[80862]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java (0x109d894c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10bdc04e0). One of the two will be used. Which one is undefined.
JNIEnv->FindClass(com/baidu/netdisk/security/URLHandler) was called from RX@0x40026edf[libnetdisk-security.so]0x26edf
JNIEnv->RegisterNatives(com/baidu/netdisk/security/URLHandler, RW@0x4009b204[libnetdisk-security.so]0x9b204, 1) was called from RX@0x40026ef5[libnetdisk-security.so]0x26ef5
RegisterNative(com/baidu/netdisk/security/URLHandler, handlerURL(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, RX@0x400269bd[libnetdisk-security.so]0x269bd)
Find native function Java_com_baidu_netdisk_security_URLHandler_handlerURL(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; => RX@0x400269bd[libnetdisk-security.so]0x269bd
JNIEnv->FindClass(com/baidu/netdisk/security/URLHandler) was called from RX@0x400269e9[libnetdisk-security.so]0x269e9
JNIEnv->CallStaticObjectMethodV(class com/baidu/netdisk/security/URLHandler, getSK() => "ZNlxtg792T2ZQQ41eD9I7bich5f3zh5GT5puZr0vNtQ=") was called from RX@0x4001ca41[libnetdisk-security.so]0x1ca41
JNIEnv->GetStringUtfChars("ZNlxtg792T2ZQQ41eD9I7bich5f3zh5GT5puZr0vNtQ=") was called from RX@0x40026a23[libnetdisk-security.so]0x26a23
JNIEnv->CallStaticObjectMethodV(class com/baidu/netdisk/security/URLHandler, getDeviceID() => "383530E8740684A3ECAC1D6A530A3516|0") was called from RX@0x4001ca41[libnetdisk-security.so]0x1ca41
JNIEnv->GetStringUtfChars("383530E8740684A3ECAC1D6A530A3516|0") was called from RX@0x40026a61[libnetdisk-security.so]0x26a61
JNIEnv->GetStringUtfChars("https://pan.baidu.com/rest/2.0/pcs/adx?m=tab&w=1080&h=2210&d=android&v=14310&devuid=0&clienttype=1&channel=android_10_Redmi%20K20%20Pro%20Premium%20Edition_bd-netdisk_1018849x&version=10.1.14&vip=1&firstlaunchtime=1589625679&time=1589687497872&network_type=wifi&apn_id=1_0&freeisp=0&queryfree=0") was called from RX@0x40026aaf[libnetdisk-security.so]0x26aaf
JNIEnv->GetStringUtfChars("123456789") was called from RX@0x40026c6b[libnetdisk-security.so]0x26c6b
JNIEnv->GetStringUtfChars("bdusstest") was called from RX@0x40026c87[libnetdisk-security.so]0x26c87
JNIEnv->CallObjectMethodV(android.content.Context@721e0f4f, getPackageManager() => android.content.pm.PackageManager@2aaf7cc2) was called from RX@0x4001c761[libnetdisk-security.so]0x1c761
JNIEnv->CallObjectMethodV(android.content.Context@721e0f4f, getPackageName() => "com.baidu.netdisk") was called from RX@0x4001c761[libnetdisk-security.so]0x1c761
JNIEnv->CallObjectMethodV(android.content.pm.PackageManager@2aaf7cc2, getPackageInfo("com.baidu.netdisk", 0x40) => android.content.pm.PackageInfo@47f6473) was called from RX@0x4001c761[libnetdisk-security.so]0x1c761
JNIEnv->GetObjectField(android.content.pm.PackageInfo@47f6473, signatures [Landroid/content/pm/Signature; => [Lcom.github.unidbg.linux.android.dvm.api.Signature;@6d00a15d) was called from RX@0x4001c5af[libnetdisk-security.so]0x1c5af
JNIEnv->GetObjectArrayElement([Lcom.github.unidbg.linux.android.dvm.api.Signature;@6d00a15d, 0) was called from RX@0x4001c5cd[libnetdisk-security.so]0x1c5cd
JNIEnv->CallObjectMethodV(android.content.pm.Signature@5034c75a, toByteArray() => [B@396a51ab) was called from RX@0x4001c761[libnetdisk-security.so]0x1c761
JNIEnv->GetArrayLength([B@396a51ab => 1025) was called from RX@0x4001c641[libnetdisk-security.so]0x1c641
JNIEnv->FindClass(java/io/ByteArrayInputStream) was called from RX@0x4001c79f[libnetdisk-security.so]0x1c79f
JNIEnv->NewObjectV(class java/io/ByteArrayInputStream, <init>([B@396a51ab) => java.io.ByteArrayInputStream@7f9a81e8) was called from RX@0x4001c9f1[libnetdisk-security.so]0x1c9f1
JNIEnv->FindClass(java/security/cert/CertificateFactory) was called from RX@0x4001c7e1[libnetdisk-security.so]0x1c7e1
JNIEnv->NewStringUTF("X.509") was called from RX@0x4001c807[libnetdisk-security.so]0x1c807
JNIEnv->CallStaticObjectMethodV(class java/security/cert/CertificateFactory, getInstance("X.509") => java.security.cert.CertificateFactory@62ee68d8) was called from RX@0x4001ca41[libnetdisk-security.so]0x1ca41
JNIEnv->FindClass(java/security/cert/X509Certificate) was called from RX@0x4001c829[libnetdisk-security.so]0x1c829
JNIEnv->CallObjectMethodV(java.security.cert.CertificateFactory@62ee68d8, generateCertificate(java.io.ByteArrayInputStream@7f9a81e8) => java.security.cert.Certificate@735b5592) was called from RX@0x4001c761[libnetdisk-security.so]0x1c761
[17:10:59 542]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:448) - handleInterrupt intno=2, NR=-1073744828, svcNumber=0x114, PC=unicorn@0xfffe01d4, syscall=null
unicorn.UnicornException: dvmObject=java.security.cert.Certificate@735b5592, dvmClass=class java/security/cert/Certificate, jmethodID=unicorn@0x6711a142
	at com.github.unidbg.linux.android.dvm.DalvikVM$21.handle(DalvikVM.java:384)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:111)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:336)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:417)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:197)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:58)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:222)
	at com.baidu.baidu.encodeByte(baidu.java:99)
	at com.baidu.baidu.main(baidu.java:82)
[17:10:59 546]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:351) - emulate RX@0x400269bd[libnetdisk-security.so]0x269bd exception sp=unicorn@0xbffff438, msg=dvmObject=java.security.cert.Certificate@735b5592, dvmClass=class java/security/cert/Certificate, jmethodID=unicorn@0x6711a142, offset=659ms
Exception in thread "main" java.lang.NullPointerException
	at com.baidu.baidu.encodeByte(baidu.java:109)
	at com.baidu.baidu.main(baidu.java:82)

Process finished with exit code 1
```
请问这种情况有什么好办法么，新手不太会，谢谢

**Comment by djlshk** [comment]
求问大佬解决了嘛。。

**Comment by liaolingfen4** [comment]
如何解决的，望告知

> 求问大佬解决了嘛。。

**Comment by Erope** [comment]
> 求问大佬解决了嘛。。

没有解决

**Comment by Erope** [comment]
> 如何解决的，望告知
> 
> > 求问大佬解决了嘛。。

没有解决
