### ISSUE TITLE
unidbg运行so异常, 求救各位大大~~

### ISSUE THREAD

**Issue by feng504x** [zhkl0228/unidbg#163]
Connected to the target VM, address: '127.0.0.1:14267', transport: 'socket'
[20:03:28 169]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:385) - libkwsgmain.so load dependency libjnigraphics.so failed
[20:03:28 182]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:385) - libkwsgmain.so load dependency libandroid.so failed
[20:03:28 183]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:385) - libkwsgmain.so load dependency libc++_shared.so failed
[20:03:28 189]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk15ctypeIcE2idE, type=object, size=0] is missing relocationAddr=RW@0x400ccd38[libkwsgmain.so]0xccd38, offset=0x0
[20:03:28 189]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk17num_putIcNS_19ostreambuf_iteratorIcNS_11char_traitsIcEEEEE2idE, type=object, size=0] is missing relocationAddr=RW@0x400ccd34[libkwsgmain.so]0xccd34, offset=0x0
[20:03:28 189]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZTINSt6__ndk18ios_baseE, type=object, size=0] is missing relocationAddr=RW@0x400cc92c[libkwsgmain.so]0xcc92c, offset=0x0
[20:03:28 190]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk17codecvtIcc9mbstate_tE2idE, type=object, size=0] is missing relocationAddr=RW@0x400ccd64[libkwsgmain.so]0xccd64, offset=0x0
[20:03:28 190]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=AAssetManager_fromJava, type=function, size=0] is missing relocationAddr=RW@0x400cce24[libkwsgmain.so]0xcce24, offset=0x0
[20:03:28 190]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk16localeD1Ev, type=function, size=0] is missing relocationAddr=RW@0x400cce50[libkwsgmain.so]0xcce50, offset=0x0
[20:03:28 190]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk18ios_baseD2Ev, type=function, size=0] is missing relocationAddr=RW@0x400cce54[libkwsgmain.so]0xcce54, offset=0x0
[20:03:28 193]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk18ios_base4initEPv, type=function, size=0] is missing relocationAddr=RW@0x400cce5c[libkwsgmain.so]0xcce5c, offset=0x0
[20:03:28 195]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk16localeC1Ev, type=function, size=0] is missing relocationAddr=RW@0x400cce60[libkwsgmain.so]0xcce60, offset=0x0
[20:03:28 195]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNKSt6__ndk18ios_base6getlocEv, type=function, size=0] is missing relocationAddr=RW@0x400cce64[libkwsgmain.so]0xcce64, offset=0x0
[20:03:28 195]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNKSt6__ndk16locale9use_facetERNS0_2idE, type=function, size=0] is missing relocationAddr=RW@0x400cce68[libkwsgmain.so]0xcce68, offset=0x0
[20:03:28 196]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk18ios_base5clearEj, type=function, size=0] is missing relocationAddr=RW@0x400cce6c[libkwsgmain.so]0xcce6c, offset=0x0
[20:03:28 196]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk18ios_base33__set_badbit_and_consider_rethrowEv, type=function, size=0] is missing relocationAddr=RW@0x400cce70[libkwsgmain.so]0xcce70, offset=0x0
[20:03:28 198]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=AAsset_close, type=function, size=0] is missing relocationAddr=RW@0x400ccf50[libkwsgmain.so]0xccf50, offset=0x0
[20:03:28 199]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=AAssetManager_open, type=function, size=0] is missing relocationAddr=RW@0x400ccf54[libkwsgmain.so]0xccf54, offset=0x0
[20:03:28 199]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=AAsset_read, type=function, size=0] is missing relocationAddr=RW@0x400ccf58[libkwsgmain.so]0xccf58, offset=0x0
[20:03:28 199]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=AAsset_getLength, type=function, size=0] is missing relocationAddr=RW@0x400ccf5c[libkwsgmain.so]0xccf5c, offset=0x0
[20:03:28 199]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk16localeC1ERKS0_, type=function, size=0] is missing relocationAddr=RW@0x400ccf7c[libkwsgmain.so]0xccf7c, offset=0x0
[20:03:28 199]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNKSt6__ndk16locale9has_facetERNS0_2idE, type=function, size=0] is missing relocationAddr=RW@0x400ccf80[libkwsgmain.so]0xccf80, offset=0x0
[20:03:28 283]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk15ctypeIcE2idE symbol is missing before init relocationAddr=RW@0x400ccd38[libkwsgmain.so]0xccd38
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk17num_putIcNS_19ostreambuf_iteratorIcNS_11char_traitsIcEEEEE2idE symbol is missing before init relocationAddr=RW@0x400ccd34[libkwsgmain.so]0xccd34
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZTINSt6__ndk18ios_baseE symbol is missing before init relocationAddr=RW@0x400cc92c[libkwsgmain.so]0xcc92c
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk17codecvtIcc9mbstate_tE2idE symbol is missing before init relocationAddr=RW@0x400ccd64[libkwsgmain.so]0xccd64
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]AAssetManager_fromJava symbol is missing before init relocationAddr=RW@0x400cce24[libkwsgmain.so]0xcce24
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk16localeD1Ev symbol is missing before init relocationAddr=RW@0x400cce50[libkwsgmain.so]0xcce50
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk18ios_baseD2Ev symbol is missing before init relocationAddr=RW@0x400cce54[libkwsgmain.so]0xcce54
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk18ios_base4initEPv symbol is missing before init relocationAddr=RW@0x400cce5c[libkwsgmain.so]0xcce5c
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk16localeC1Ev symbol is missing before init relocationAddr=RW@0x400cce60[libkwsgmain.so]0xcce60
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNKSt6__ndk18ios_base6getlocEv symbol is missing before init relocationAddr=RW@0x400cce64[libkwsgmain.so]0xcce64
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNKSt6__ndk16locale9use_facetERNS0_2idE symbol is missing before init relocationAddr=RW@0x400cce68[libkwsgmain.so]0xcce68
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk18ios_base5clearEj symbol is missing before init relocationAddr=RW@0x400cce6c[libkwsgmain.so]0xcce6c
[20:03:28 284]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk18ios_base33__set_badbit_and_consider_rethrowEv symbol is missing before init relocationAddr=RW@0x400cce70[libkwsgmain.so]0xcce70
[20:03:28 285]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]AAsset_close symbol is missing before init relocationAddr=RW@0x400ccf50[libkwsgmain.so]0xccf50
[20:03:28 288]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]AAssetManager_open symbol is missing before init relocationAddr=RW@0x400ccf54[libkwsgmain.so]0xccf54
[20:03:28 289]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]AAsset_read symbol is missing before init relocationAddr=RW@0x400ccf58[libkwsgmain.so]0xccf58
[20:03:28 289]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]AAsset_getLength symbol is missing before init relocationAddr=RW@0x400ccf5c[libkwsgmain.so]0xccf5c
[20:03:28 289]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk16localeC1ERKS0_ symbol is missing before init relocationAddr=RW@0x400ccf7c[libkwsgmain.so]0xccf7c
[20:03:28 289]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNKSt6__ndk16locale9has_facetERNS0_2idE symbol is missing before init relocationAddr=RW@0x400ccf80[libkwsgmain.so]0xccf80
JNIEnv->FindClass(com/kuaishou/android/security/mainplugin/JNICLibrary) was called from RX@0x40005053[libkwsgmain.so]0x5053
JNIEnv->RegisterNatives(com/kuaishou/android/security/mainplugin/JNICLibrary, RW@0x400cd004[libkwsgmain.so]0xcd004, 1) was called from RX@0x40004ff3[libkwsgmain.so]0x4ff3
RegisterNative(com/kuaishou/android/security/mainplugin/JNICLibrary, doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object;, RX@0x4000b771[libkwsgmain.so]0xb771)
JNIEnv->FindClass(com/kuaishou/android/security/kfree/ExceptionProxy) was called from RX@0x40004407[libkwsgmain.so]0x4407
JNIEnv->FindClass(com/kuaishou/dfp/env/Proxy/EngineProxy) was called from RX@0x400045dd[libkwsgmain.so]0x45dd
JNIEnv->FindClass(java/lang/System) was called from RX@0x4000597d[libkwsgmain.so]0x597d
JNIEnv->NewStringUTF("java.vm.version") was called from RX@0x40005ad7[libkwsgmain.so]0x5ad7
[20:03:28 377]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:439) - handleInterrupt intno=2, NR=-1073744468, svcNumber=0x12d, PC=unicorn@0xfffe0364, syscall=null
java.lang.AbstractMethodError: java/lang/System->getProperty(Ljava/lang/String;)Ljava/lang/String;
	at com.github.unidbg.linux.android.dvm.AbstractJni.callStaticObjectMethodV(AbstractJni.java:314)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callStaticObjectMethodV(DvmMethod.java:39)
	at com.github.unidbg.linux.android.dvm.DalvikVM$46.handle(DalvikVM.java:989)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:102)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:344)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:423)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:206)
	at com.github.unidbg.Module.emulateFunction(Module.java:154)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:188)
	at com.github.unidbg.linux.LinuxSymbol.call(LinuxSymbol.java:27)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:30)
	at com.smile.gifmaker.KwaiApp.<init>(KwaiApp.java:42)
	at com.smile.gifmaker.KwaiApp.main(KwaiApp.java:56)
Find native function Java_com_kuaishou_android_security_mainplugin_JNICLibrary_doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object; => RX@0x4000b771[libkwsgmain.so]0xb771
JNIEnv->GetArrayLength(["/rest/n/tag/text/feed/hot1bf3710213ad409930cd91704d077aac", "d7b7d042-d4f2-4012-be60-d97ff2429c17", 0xffffffff, false, android.content.Context@147ed70f, "", false] => 7) was called from RX@0x4001b293[libkwsgmain.so]0x1b293
JNIEnv->GetObjectArrayElement(["/rest/n/tag/text/feed/hot1bf3710213ad409930cd91704d077aac", "d7b7d042-d4f2-4012-be60-d97ff2429c17", 0xffffffff, false, android.content.Context@147ed70f, "", false], 4) was called from RX@0x4000e6cd[libkwsgmain.so]0xe6cd
JNIEnv->GetObjectArrayElement(["/rest/n/tag/text/feed/hot1bf3710213ad409930cd91704d077aac", "d7b7d042-d4f2-4012-be60-d97ff2429c17", 0xffffffff, false, android.content.Context@147ed70f, "", false], 1) was called from RX@0x40019829[libkwsgmain.so]0x19829
JNIEnv->GetStringUtfChars("d7b7d042-d4f2-4012-be60-d97ff2429c17") was called from RX@0x400165f3[libkwsgmain.so]0x165f3
JNIEnv->NewStringUTF("80014 [1] [p11] [0x0][123-533-]") was called from RX@0x40074917[libkwsgmain.so]0x74917
[20:03:30 439]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:439) - handleInterrupt intno=2, NR=-1073746308, svcNumber=0x136, PC=unicorn@0xfffe03f4, syscall=null
java.lang.AbstractMethodError: com/kuaishou/android/security/kfree/ExceptionProxy->nativeReport(ILjava/lang/String;)V
	at com.github.unidbg.linux.android.dvm.AbstractJni.callStaticVoidMethodV(AbstractJni.java:393)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callStaticVoidMethodV(DvmMethod.java:229)
	at com.github.unidbg.linux.android.dvm.DalvikVM$55.handle(DalvikVM.java:1197)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:102)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:344)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:423)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:206)
	at com.github.unidbg.Module.emulateFunction(Module.java:154)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:61)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:222)
	at com.smile.gifmaker.KwaiApp.getSign3(KwaiApp.java:94)
	at com.smile.gifmaker.KwaiApp.main(KwaiApp.java:57)
hash:4294838832, dvmObject=null

挺多问题的, 有大佬帮忙解决一下吗? 万分感激

1.   libkwsgmain.so load dependency libjnigraphics.so failed  这是要导入相关so依赖???
2. java.lang.AbstractMethodError: java/lang/System->getProperty(Ljava/lang/String;)Ljava/lang/String;  这个方法没找到??
3.  java.lang.AbstractMethodError: com/kuaishou/android/security/kfree/ExceptionProxy->nativeReport(ILjava/lang/String;)V
	at com.github.unidbg.linux.android.dvm.AbstractJni.callStaticVoidMethodV(AbstractJni.java:393)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callStaticVoidMethodV(DvmMethod.java:229)
	at com.github.unidbg.linux.android.dvm.DalvikVM$55.handle(DalvikVM.java:1197)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:102)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:344)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:423)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:206)
	at com.github.unidbg.Module.emulateFunction(Module.java:154)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:61)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:222)
	at com.smile.gifmaker.KwaiApp.getSign3(KwaiApp.java:94)
	at com.smile.gifmaker.KwaiApp.main(KwaiApp.java:57)
hash:4294838832, dvmObject=null

**Comment by HuRuWo** [comment]
libandroid.so 和 libjnigraphics.so 的载入已经完成了，具体参考 Utilities32 和 Utilities64
如果还有其他的要加载需要继承 VirtualModule 实现

**Comment by feng504x** [comment]
> 1.libandroid.so 和 libjnigraphics.so 的载入已经完成了，具体参考 Utilities32 和 Utilities64
> 如果还有其他的要加载需要继承 VirtualModule 实现
> 2.getProperty 实现可以参考其他地方的写法类似这样
> 
> ```
> if ("java/lang/System->getProperty(Ljava/lang/String;)Ljava/lang/String;".equals(signature)) {
>             StringObject string = varArg.getObject(0);
>             return new StringObject(vm, System.getProperty(string.getValue()));
>         }
> ```
谢谢大神~~, 可以加个qq请教一下吗?
