### ISSUE TITLE
重写方法后报内存异常

### ISSUE THREAD

**Issue by feng504x** [zhkl0228/unidbg#165]
![image](https://user-images.githubusercontent.com/31628777/87855903-fa772b00-c94d-11ea-9f8d-d5d6127e60c6.png)

"C:\Program Files\Java\jdk1.8.0_171\bin\java" "-javaagent:D:\IntelliJ IDEA 2017.3\lib\idea_rt.jar=8513:D:\IntelliJ IDEA 2017.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_171\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\rt.jar;D:\unidbg_douyin10-master\target\test-classes;D:\unidbg_douyin10-master\target\classes;D:\apache\repository\com\github\zhkl0228\unicorn\1.0.9\unicorn-1.0.9.jar;D:\apache\repository\org\scijava\native-lib-loader\2.3.4\native-lib-loader-2.3.4.jar;D:\apache\repository\com\github\zhkl0228\capstone\3.0.8\capstone-3.0.8.jar;D:\apache\repository\net\java\dev\jna\jna\4.5.2\jna-4.5.2.jar;D:\apache\repository\com\github\zhkl0228\keystone\0.9.2\keystone-0.9.2.jar;D:\apache\repository\commons-codec\commons-codec\1.6\commons-codec-1.6.jar;D:\apache\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;D:\apache\repository\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;D:\apache\repository\net\dongliu\apk-parser\2.6.4\apk-parser-2.6.4.jar;D:\apache\repository\io\kaitai\kaitai-struct-runtime\0.8\kaitai-struct-runtime-0.8.jar;D:\apache\repository\com\googlecode\plist\dd-plist\1.23\dd-plist-1.23.jar;D:\apache\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\apache\repository\junit\junit\3.8.2\junit-3.8.2.jar;D:\apache\repository\org\slf4j\slf4j-api\1.7.26\slf4j-api-1.7.26.jar;D:\apache\repository\org\slf4j\slf4j-log4j12\1.7.26\slf4j-log4j12-1.7.26.jar;D:\apache\repository\com\alibaba\fastjson\1.2.60\fastjson-1.2.60.jar" com.smile.gifmaker.KwaiApp
[23:25:42 594]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:381) - libkwsgmain.so load dependency libc++_shared.so failed
[23:25:42 604]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk15ctypeIcE2idE, type=object, size=0] is missing relocationAddr=RW@0x400ccd38[libkwsgmain.so]0xccd38, offset=0x0
[23:25:42 604]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk17num_putIcNS_19ostreambuf_iteratorIcNS_11char_traitsIcEEEEE2idE, type=object, size=0] is missing relocationAddr=RW@0x400ccd34[libkwsgmain.so]0xccd34, offset=0x0
[23:25:42 604]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZTINSt6__ndk18ios_baseE, type=object, size=0] is missing relocationAddr=RW@0x400cc92c[libkwsgmain.so]0xcc92c, offset=0x0
[23:25:42 605]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk17codecvtIcc9mbstate_tE2idE, type=object, size=0] is missing relocationAddr=RW@0x400ccd64[libkwsgmain.so]0xccd64, offset=0x0
[23:25:42 605]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk16localeD1Ev, type=function, size=0] is missing relocationAddr=RW@0x400cce50[libkwsgmain.so]0xcce50, offset=0x0
[23:25:42 605]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk18ios_baseD2Ev, type=function, size=0] is missing relocationAddr=RW@0x400cce54[libkwsgmain.so]0xcce54, offset=0x0
[23:25:42 605]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk18ios_base4initEPv, type=function, size=0] is missing relocationAddr=RW@0x400cce5c[libkwsgmain.so]0xcce5c, offset=0x0
[23:25:42 606]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk16localeC1Ev, type=function, size=0] is missing relocationAddr=RW@0x400cce60[libkwsgmain.so]0xcce60, offset=0x0
[23:25:42 606]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNKSt6__ndk18ios_base6getlocEv, type=function, size=0] is missing relocationAddr=RW@0x400cce64[libkwsgmain.so]0xcce64, offset=0x0
[23:25:42 606]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNKSt6__ndk16locale9use_facetERNS0_2idE, type=function, size=0] is missing relocationAddr=RW@0x400cce68[libkwsgmain.so]0xcce68, offset=0x0
[23:25:42 606]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk18ios_base5clearEj, type=function, size=0] is missing relocationAddr=RW@0x400cce6c[libkwsgmain.so]0xcce6c, offset=0x0
[23:25:42 606]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk18ios_base33__set_badbit_and_consider_rethrowEv, type=function, size=0] is missing relocationAddr=RW@0x400cce70[libkwsgmain.so]0xcce70, offset=0x0
[23:25:42 606]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNSt6__ndk16localeC1ERKS0_, type=function, size=0] is missing relocationAddr=RW@0x400ccf7c[libkwsgmain.so]0xccf7c, offset=0x0
[23:25:42 606]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libkwsgmain.so]symbol ElfSymbol[name=_ZNKSt6__ndk16locale9has_facetERNS0_2idE, type=function, size=0] is missing relocationAddr=RW@0x400ccf80[libkwsgmain.so]0xccf80, offset=0x0
[23:25:42 737]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk15ctypeIcE2idE symbol is missing before init relocationAddr=RW@0x400ccd38[libkwsgmain.so]0xccd38
[23:25:42 743]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk17num_putIcNS_19ostreambuf_iteratorIcNS_11char_traitsIcEEEEE2idE symbol is missing before init relocationAddr=RW@0x400ccd34[libkwsgmain.so]0xccd34
[23:25:42 743]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZTINSt6__ndk18ios_baseE symbol is missing before init relocationAddr=RW@0x400cc92c[libkwsgmain.so]0xcc92c
[23:25:42 744]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk17codecvtIcc9mbstate_tE2idE symbol is missing before init relocationAddr=RW@0x400ccd64[libkwsgmain.so]0xccd64
[23:25:42 744]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk16localeD1Ev symbol is missing before init relocationAddr=RW@0x400cce50[libkwsgmain.so]0xcce50
[23:25:42 744]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk18ios_baseD2Ev symbol is missing before init relocationAddr=RW@0x400cce54[libkwsgmain.so]0xcce54
[23:25:42 744]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk18ios_base4initEPv symbol is missing before init relocationAddr=RW@0x400cce5c[libkwsgmain.so]0xcce5c
[23:25:42 744]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk16localeC1Ev symbol is missing before init relocationAddr=RW@0x400cce60[libkwsgmain.so]0xcce60
[23:25:42 744]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNKSt6__ndk18ios_base6getlocEv symbol is missing before init relocationAddr=RW@0x400cce64[libkwsgmain.so]0xcce64
[23:25:42 744]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNKSt6__ndk16locale9use_facetERNS0_2idE symbol is missing before init relocationAddr=RW@0x400cce68[libkwsgmain.so]0xcce68
[23:25:42 744]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk18ios_base5clearEj symbol is missing before init relocationAddr=RW@0x400cce6c[libkwsgmain.so]0xcce6c
[23:25:42 744]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk18ios_base33__set_badbit_and_consider_rethrowEv symbol is missing before init relocationAddr=RW@0x400cce70[libkwsgmain.so]0xcce70
[23:25:42 745]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNSt6__ndk16localeC1ERKS0_ symbol is missing before init relocationAddr=RW@0x400ccf7c[libkwsgmain.so]0xccf7c
[23:25:42 745]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:88) - [libkwsgmain.so]_ZNKSt6__ndk16locale9has_facetERNS0_2idE symbol is missing before init relocationAddr=RW@0x400ccf80[libkwsgmain.so]0xccf80
JNIEnv->FindClass(com/kuaishou/android/security/mainplugin/JNICLibrary) was called from RX@0x40005053[libkwsgmain.so]0x5053
JNIEnv->RegisterNatives(com/kuaishou/android/security/mainplugin/JNICLibrary, RW@0x400cd004[libkwsgmain.so]0xcd004, 1) was called from RX@0x40004ff3[libkwsgmain.so]0x4ff3
RegisterNative(com/kuaishou/android/security/mainplugin/JNICLibrary, doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object;, RX@0x4000b771[libkwsgmain.so]0xb771)
JNIEnv->FindClass(com/kuaishou/android/security/kfree/ExceptionProxy) was called from RX@0x40004407[libkwsgmain.so]0x4407
JNIEnv->FindClass(com/kuaishou/dfp/env/Proxy/EngineProxy) was called from RX@0x400045dd[libkwsgmain.so]0x45dd
JNIEnv->FindClass(java/lang/System) was called from RX@0x4000597d[libkwsgmain.so]0x597d
JNIEnv->NewStringUTF("java.vm.version") was called from RX@0x40005ad7[libkwsgmain.so]0x5ad7
JNIEnv->CallStaticObjectMethodV(class java/lang/System, getProperty("java.vm.version") => "25.171-b11") was called from RX@0x40005cbf[libkwsgmain.so]0x5cbf
JNIEnv->GetStringUtfChars("25.171-b11") was called from RX@0x40074727[libkwsgmain.so]0x74727
JNIEnv->ReleaseStringUTFChars("25.171-b11") was called from RX@0x40074741[libkwsgmain.so]0x74741
Find native function Java_com_kuaishou_android_security_mainplugin_JNICLibrary_doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object; => RX@0x4000b771[libkwsgmain.so]0xb771
[23:25:42 791] DEBUG [com.github.unidbg.AbstractEmulator] (AbstractEmulator:335) - emulate RX@0x4000b771[libkwsgmain.so]0xb771 started sp=unicorn@0xbffff788
JNIEnv->GetArrayLength([Lcom.github.unidbg.linux.android.dvm.DvmObject;@3aa9e816 => 7) was called from RX@0x4001b293[libkwsgmain.so]0x1b293
JNIEnv->GetObjectArrayElement([Lcom.github.unidbg.linux.android.dvm.DvmObject;@3aa9e816, 4) was called from RX@0x4000e6cd[libkwsgmain.so]0xe6cd
JNIEnv->GetObjectArrayElement([Lcom.github.unidbg.linux.android.dvm.DvmObject;@3aa9e816, 1) was called from RX@0x40019829[libkwsgmain.so]0x19829
JNIEnv->GetStringUtfChars("d7b7d042-d4f2-4012-be60-d97ff2429c17") was called from RX@0x400165f3[libkwsgmain.so]0x165f3
JNIEnv->NewStringUTF("80014 [1] [p11] [0x0][123-533-]") was called from RX@0x40074917[libkwsgmain.so]0x74917
JNIEnv->CallStaticVoidMethodV(class com/kuaishou/android/security/kfree/ExceptionProxy, nativeReport(0x1388e, "80014 [1] [p11] [0x0][123-533-]")) was called from RX@0x400749b7[libkwsgmain.so]0x749b7
JNIEnv->FindClass(android/app/ActivityThread) was called from RX@0x4002f8e3[libkwsgmain.so]0x2f8e3
JNIEnv->CallStaticObjectMethodV(class android/app/ActivityThread, currentActivityThread() => android.app.ActivityThread@1ae369b7) was called from RX@0x40005cbf[libkwsgmain.so]0x5cbf
JNIEnv->GetStaticObjectField(class android/app/ActivityThread, sPackageManager Landroid/content/pm/IPackageManager; => android.content.pm.IPackageManager@6fffcba5) was called from RX@0x40030847[libkwsgmain.so]0x30847
[23:25:42 878]  WARN [com.github.unidbg.arm.AbstractARMEmulator] (AbstractARMEmulator$1:54) - memory failed: address=0x28, size=1, value=0x0
unicorn.UnicornException: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:339)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:437)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:196)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:232)
	at com.smile.gifmaker.KwaiApp.getSign3(KwaiApp.java:129)
	at com.smile.gifmaker.KwaiApp.main(KwaiApp.java:116)
debugger break at: 0x28
>>> r0=0xfffe0a30(-128464) r1=0x9976233 r2=0x28 r3=0x400cc8c4 r4=0x34033bd0 r5=0x0 r6=0x34033bd0 r7=0xbffff208 r8=0xbffff2ec sb=0x77349ea0 sl=0x0 fp=0x400cc8c4 ip=0x34033bd0 SP=0xbffff160 LR=RX@0x4003166f[libkwsgmain.so]0x3166f PC=unicorn@0x28 cpsr: N=0, Z=1, C=1, V=0, T=0, mode=0b10000
unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at unicorn.Unicorn.mem_read(Native Method)
	at com.github.unidbg.arm.CodeHistory.disassemble(CodeHistory.java:20)
	at com.github.unidbg.arm.AbstractARMDebugger.disassemble(AbstractARMDebugger.java:470)
	at com.github.unidbg.arm.SimpleARMDebugger.loop(SimpleARMDebugger.java:34)
	at com.github.unidbg.arm.AbstractARMDebugger.debug(AbstractARMDebugger.java:178)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:350)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:437)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:196)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:232)
	at com.smile.gifmaker.KwaiApp.getSign3(KwaiApp.java:129)
	at com.smile.gifmaker.KwaiApp.main(KwaiApp.java:116)

求助求助

**Comment by fanfan493** [comment]
解决了么

**Comment by harmongao** [comment]
解决了吗
