### ISSUE TITLE
AbstractMethodError: java/lang/Thread->currentThread()Ljava/lang/Thread;这个错误是什么原因有大佬知道嘛

### ISSUE THREAD

**Issue by gigi0903** [zhkl0228/unidbg#171]
methodName : currentThread
signature : java/lang/Thread->currentThread()Ljava/lang/Thread;
[15:36:18 262]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:442) - handleInterrupt intno=2, NR=-1073746164, svcNumber=0x12d, PC=unicorn@0xfffe0364, syscall=null
java.lang.AbstractMethodError: java/lang/Thread->currentThread()Ljava/lang/Thread;
	at com.github.unidbg.linux.android.dvm.AbstractJni.callStaticObjectMethodV(AbstractJni.java:314)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callStaticObjectMethodV(DvmMethod.java:42)
	at com.github.unidbg.linux.android.dvm.DalvikVM$46.handle(DalvikVM.java:989)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:105)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:336)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:415)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:197)
	at com.github.unidbg.Module.emulateFunction(Module.java:150)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:61)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:222)
	at com.douyin.BlackBox.encodeByte(BlackBox.java:159)
	at com.douyin.BlackBox.main(BlackBox.java:154)

**Comment by dgqypl** [comment]
试试把这段代码加到你的类里：
```java
    @Override
    public DvmObject callStaticObjectMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList varArg) {
        if ("java/lang/System->getProperty(Ljava/lang/String;)Ljava/lang/String;".equals(signature)) {
            StringObject string = varArg.getObject(0);
            String string2;
            if (string.getValue().equals("http.proxyHost")) {
                string2 = "";
            } else if (string.getValue().equals("http.proxyPort")) {
                string2 = "80";
            } else if (string.getValue().equals("java.vm.version")) {
                string2 = "1.8.0";
            } else {
                string2 = System.getProperty(string.getValue());
            }
            return new StringObject(vm, string2);
        }

        if ("java/lang/Thread->currentThread()Ljava/lang/Thread;".equals(signature)) {
            return vm.resolveClass("java/lang/Thread").newObject(Thread.currentThread());
        }
        if ("android/app/Application->getApplicationInfo()Landroid/content/pm/ApplicationInfo;".equals(signature)) {
            return new ApplicationInfo(vm);
        }

        return super.callStaticObjectMethodV(vm, dvmClass, signature, varArg);
    }
```
