### ISSUE TITLE
dvmClass.getMethod(jmethodID.toIntPeer()); return null

### ISSUE THREAD

**Issue by darkgirl** [zhkl0228/unidbg#180]
JNIEnv->FindClass(android/app/Activity) was called from RX@0x40002b3d[libjdbitmapkit.so]0x2b3d
JNIEnv->FindClass(android/content/pm/PackageManager) was called from RX@0x40002b55[libjdbitmapkit.so]0x2b55
JNIEnv->FindClass(android/content/pm/PackageInfo) was called from RX@0x40002b65[libjdbitmapkit.so]0x2b65
JNIEnv->FindClass(android/content/pm/Signature) was called from RX@0x40002b75[libjdbitmapkit.so]0x2b75
CallObjectMethod object=unicorn@0x31190526, jmethodID=unicorn@0x6ef28d94
dvmClass: class android/app/Application
dvmMethod: null
[16:52:06 528]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:446) - handleInterrupt intno=2, NR=-578271390, svcNumber=0x113, PC=unicorn@0xfffe01c4, syscall=null
unicorn.UnicornException
	at com.github.unidbg.linux.android.dvm.DalvikVM$20.handle(DalvikVM.java:366)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:103)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:373)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:461)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:208)
	at com.github.unidbg.Module.emulateFunction(Module.java:154)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:204)
	at com.github.unidbg.linux.LinuxSymbol.call(LinuxSymbol.java:27)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:30)\

请问这是调用哪个方法出问题了?
如何处理呢? android/app/Application这个类我是通过
 return callStaticObjectMethodV(vm, dvmClass, "android/app/ActivityThread->currentApplication()Landroid/app/Application;", null);
得到的, 不知道是不是这里有问题.
另外, 我修改过DalvikVM.java源码, 行数是不对的
多谢.

**Comment by darkgirl** [comment]
没文档, 慢慢研究吧

**Comment by harmongao** [comment]
解决了吗，我也碰到了这个问题

**Comment by ARC4991** [comment]
需要自己实现Jni接口
然后vm.setJni(this);
