### ISSUE TITLE
您好作者，出现此问题应如何解决

### ISSUE THREAD

**Issue by nantian-dog** [zhkl0228/unidbg#190]
`[00:37:06 014]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:446) - handleInterrupt intno=2, NR=-1073744096, svcNumber=0x113, PC=unicorn@0xfffe01c4, syscall=null
java.lang.UnsupportedOperationException: android/content/Context->getPackageCodePath()Ljava/lang/String;
	at com.github.unidbg.linux.android.dvm.AbstractJni.callObjectMethod(AbstractJni.java:731)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callObjectMethod(DvmMethod.java:59)
	at com.github.unidbg.linux.android.dvm.DalvikVM$20.handle(DalvikVM.java:363)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:103)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:357)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:445)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:208)
	at com.github.unidbg.Module.emulateFunction(Module.java:154)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:115)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:250)`
@zhkl0228

**Comment by a978069486** [comment]
重写callObjectMethod
补android/content/Context->getPackageCodePath()Ljava/lang/String;
