### ISSUE TITLE
加载 libc.so 的时候发生指令无效异常 UC_ERR_INSN_INVALID

### ISSUE THREAD

**Issue by ppanda01** [zhkl0228/unidbg#206]
## 案例代码如下，一个常规的so加载操作

> ```
> AndroidEmulator emulator = new AndroidARMEmulator("");
> Memory memory = emulator.getMemory();
> memory.setLibraryResolver(new AndroidResolver(23));
> VM vm = emulator.createDalvikVM(null);
> vm.setVerbose(true);
> vm.setJni(this);
> DalvikModule dm = vm.loadLibrary(new File(this.getClass().getClassLoader().getResource("").getPath() + "lib/libpjsua2.so"), false);
> dm.callJNI_OnLoad(emulator);
> ```

## 异常信息

> ```
> [16:05:06 788]  INFO [com.github.unidbg.linux.AndroidSyscallHandler] (AndroidSyscallHandler:24) - statfs64 buf=unicorn@0xbfffeeb8, path=/sys/fs/selinux
> [16:05:06 791]  INFO [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1879) - openat dirfd=-100, pathname=/proc/filesystems, oflags=0x20000, mode=0
> [16:05:07 288]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:386) - emulate RX@0x4048260c[libc.so]0x1060c failed: sp=unicorn@0xbffff578, offset=576ms
> unicorn.UnicornException: Invalid instruction (UC_ERR_INSN_INVALID)
> 	at unicorn.Unicorn.emu_start(Native Method)
> 	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:376)
> 	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:465)
> 	at com.github.unidbg.arm.AbstractARMEmulator.eInit(AbstractARMEmulator.java:220)
> 	at com.github.unidbg.linux.AbsoluteInitFunction.call(AbsoluteInitFunction.java:38)
> 	at com.github.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:102)
> 	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:180)
> 	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:35)
> 	at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:208)
> 	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:350)
> 	at ms.jni.TestJni.<init>(TestJni.java:31)
> 	at test.Init.initTest(Init.java:50)
> 	at test.Init.main(Init.java:21)
> ```

#### 案例so以及其依赖的arm系统库，链接: https://pan.baidu.com/s/1hlTCc35QY6mR_fvwPCS37A 提取码: 4ijv

**Comment by zhkl0228** [comment]
用最新的unidbg跑，代码如下，能成功加载
`package com.sun.jna;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.LibraryResolver;
import com.github.unidbg.Module;
import com.github.unidbg.linux.android.AndroidARMEmulator;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.jni.ProxyClassFactory;
import com.github.unidbg.memory.Memory;
import com.github.unidbg.virtualmodule.android.AndroidModule;

import java.io.File;
import java.io.IOException;

public class Test {

    private static LibraryResolver createLibraryResolver() {
        return new AndroidResolver(23);
    }

    private static AndroidEmulator createARMEmulator() {
        return new AndroidARMEmulator("test");
    }

    private final AndroidEmulator emulator;
    private final Module module;

    private Test() {
        emulator = createARMEmulator();
        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(createLibraryResolver());

        memory.load(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libopenh264.so"));

        VM vm = emulator.createDalvikVM(null);
        vm.setDvmClassFactory(new ProxyClassFactory());
        vm.setVerbose(true);

        new AndroidModule(emulator, vm).register(memory);

        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libpjsua2.so"), true);
        dm.callJNI_OnLoad(emulator);
        module = dm.getModule();
    }

    private void destroy() throws IOException {
        emulator.close();
        System.out.println("destroy");
    }

    public static void main(String[] args) throws Exception {
        Test test = new Test();

        test.test();

        test.destroy();
    }

    private void test() {
    }

}
`

**Comment by zhkl0228** [comment]
不需要添加系统依赖库

**Comment by ppanda01** [comment]
#### 看了你的回复以后，我又尝试了很久，确定是不行的，我用了最新的源码创建项目。甚至直接复制粘贴你的代码，如果不添加系统的依赖库，会提示依赖缺失，如下：

```
[15:55:22 086]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:393) - libpjsua2.so load dependency libOpenSLES.so failed
[15:55:22 135]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:393) - libpjsua2.so load dependency libGLESv2.so failed
[15:55:22 136]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:393) - libpjsua2.so load dependency libEGL.so failed
destroy

Process finished with exit code 0
```



#### 添加了依然会提示问题，看起来这都是比较底层的问题，我才疏学浅，求而不得。

```
[16:01:26 133]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:392) - emulate RX@0x41371bc0[libcrypto.so]0x10abc0 failed: sp=unidbg@0xbffff758, offset=1ms
com.github.unidbg.arm.backend.BackendException
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:298)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:382)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:471)
	at com.github.unidbg.arm.AbstractARMEmulator.eInit(AbstractARMEmulator.java:227)
	at com.github.unidbg.linux.AbsoluteInitFunction.call(AbsoluteInitFunction.java:38)
	at com.github.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:102)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:180)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:35)
	at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:208)
	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:271)
	at com.sun.jna.Test.<init>(Test.java:42)
	at com.sun.jna.Test.main(Test.java:53)
[16:01:26 725]  INFO [com.github.unidbg.linux.AndroidSyscallHandler] (AndroidSyscallHandler:24) - statfs64 buf=unidbg@0xbffff318, path=/sys/fs/selinux
[16:01:26 727]  INFO [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1886) - openat dirfd=-100, pathname=/proc/filesystems, oflags=0x20000, mode=0
destroy

Process finished with exit code 0
```



#### 还是非常感谢你的回复解惑。

**Comment by zhkl0228** [comment]
依赖缺失不一定影响运行

**Comment by thouger** [comment]
依赖缺失不一定影响运行，但依赖缺失大概率导致不行，爆了一堆 is missing before init relocationAddr=RW@0x40142da0[libxxx.so]0x13fda0,有问题出现还是把问题解决好
