### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by ByboyCn** [zhkl0228/unidbg#212]
[TestSignso.zip](https://github.com/zhkl0228/unidbg/files/5622277/TestSignso.zip)
我在操作这个的时候,发现地119行
  StringObject obj = vm.getObject(hash);
这个的操作,vm.getObject(int)方法只能接受int类型的参数,但是上面的计算是long类型的,我尝试吧long变成int,会出现精度问题,导致读取数据失败,请问这个应该怎么解决呢?还有vm.deleteLocalRefs() 我在vm类中没有找到这个接口方法,所以注释掉了,目前影不影响执行还不知道.

**Comment by ByboyCn** [comment]
"C:\Program Files\Java\jdk1.8.0_271\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:51543,suspend=y,server=n -javaagent:C:\Users\Administrator\AppData\Local\JetBrains\IntelliJIdea2020.2\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_271\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_271\jre\lib\rt.jar;C:\Users\Administrator\Desktop\unidbg-0.9.1\unidbg-android\target\test-classes;C:\Users\Administrator\Desktop\unidbg-0.9.1\unidbg-android\target\classes;C:\Users\Administrator\Desktop\unidbg-0.9.1\unidbg-api\target\classes;C:\Users\Administrator\.m2\repository\com\github\zhkl0228\unicorn\1.0.9\unicorn-1.0.9.jar;C:\Users\Administrator\.m2\repository\org\scijava\native-lib-loader\2.3.4\native-lib-loader-2.3.4.jar;C:\Users\Administrator\.m2\repository\com\github\zhkl0228\capstone\3.0.8\capstone-3.0.8.jar;C:\Users\Administrator\.m2\repository\net\java\dev\jna\jna\4.5.2\jna-4.5.2.jar;C:\Users\Administrator\.m2\repository\com\github\zhkl0228\keystone\0.9.2\keystone-0.9.2.jar;C:\Users\Administrator\.m2\repository\commons-codec\commons-codec\1.6\commons-codec-1.6.jar;C:\Users\Administrator\.m2\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\Administrator\.m2\repository\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\Administrator\.m2\repository\com\alibaba\fastjson\1.2.60\fastjson-1.2.60.jar;C:\Users\Administrator\.m2\repository\com\github\zhkl0228\demumble\1.0.1\demumble-1.0.1.jar;C:\Users\Administrator\Desktop\unidbg-0.9.1\unidbg-dynarmic\target\classes;C:\Users\Administrator\.m2\repository\net\dongliu\apk-parser\2.6.4\apk-parser-2.6.4.jar;C:\Users\Administrator\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Administrator\.m2\repository\junit\junit\4.13.1\junit-4.13.1.jar;C:\Users\Administrator\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-api\1.7.26\slf4j-api-1.7.26.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-log4j12\1.7.26\slf4j-log4j12-1.7.26.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.4\lib\idea_rt.jar" cn.byboy.TestSignso
Connected to the target VM, address: '127.0.0.1:51543', transport: 'socket'
JNIEnv->FindClass(java/lang/Boolean) was called from RX@0x400b3099[libmain.so]0xb3099
JNIEnv->FindClass(java/lang/Integer) was called from RX@0x400b30b3[libmain.so]0xb30b3
JNIEnv->FindClass(java/lang/String) was called from RX@0x400b30cd[libmain.so]0xb30cd
JNIEnv->FindClass(com/taobao/wireless/security/adapter/common/HttpUtil) was called from RX@0x400aa5fb[libmain.so]0xaa5fb
JNIEnv->FindClass(com/taobao/wireless/security/adapter/umid/UmidAdapter) was called from RX@0x400aac2f[libmain.so]0xaac2f
JNIEnv->FindClass(com/taobao/wireless/security/adapter/JNICLibrary) was called from RX@0x4000fed5[libmain.so]0xfed5
JNIEnv->FindClass(com/taobao/wireless/security/adapter/common/SPUtility2) was called from RX@0x400a93bb[libmain.so]0xa93bb
JNIEnv->FindClass(com/taobao/wireless/security/adapter/datacollection/DeviceInfoCapturer) was called from RX@0x40013c63[libmain.so]0x13c63
JNIEnv->FindClass(com/taobao/wireless/security/adapter/datareport/DataReportJniBridge) was called from RX@0x40017c7d[libmain.so]0x17c7d
JNIEnv->FindClass(android/content/Context) was called from RX@0x400b9107[libmain.so]0xb9107
JNIEnv->FindClass(android/content/pm/PackageManager) was called from RX@0x400b9107[libmain.so]0xb9107
JNIEnv->FindClass(android/content/pm/PackageInfo) was called from RX@0x400b9107[libmain.so]0xb9107
JNIEnv->FindClass(android/content/pm/ApplicationInfo) was called from RX@0x400b9107[libmain.so]0xb9107
JNIEnv->FindClass(android/provider/Settings$Secure) was called from RX@0x400b9107[libmain.so]0xb9107
JNIEnv->FindClass(java/util/List) was called from RX@0x400b9107[libmain.so]0xb9107
JNIEnv->FindClass(android/net/wifi/WifiConfiguration) was called from RX@0x400b9107[libmain.so]0xb9107
JNIEnv->FindClass(android/net/wifi/WifiManager) was called from RX@0x400b9107[libmain.so]0xb9107
JNIEnv->FindClass(android/net/DhcpInfo) was called from RX@0x400b9107[libmain.so]0xb9107
JNIEnv->FindClass(com/taobao/dp/util/ZipUtils) was called from RX@0x4003736b[libmain.so]0x3736b
JNIEnv->FindClass(com/taobao/dp/util/CallbackHelper) was called from RX@0x400373af[libmain.so]0x373af
JNIEnv->FindClass(android/content/Context) was called from RX@0x400374cb[libmain.so]0x374cb
JNIEnv->FindClass(android/content/pm/PackageManager) was called from RX@0x400374ff[libmain.so]0x374ff
JNIEnv->FindClass(android/content/pm/PackageInfo) was called from RX@0x40037535[libmain.so]0x37535
JNIEnv->FindClass(android/content/pm/ApplicationInfo) was called from RX@0x4003759d[libmain.so]0x3759d
JNIEnv->FindClass(android/os/Environment) was called from RX@0x4003871d[libmain.so]0x3871d
JNIEnv->FindClass(java/io/File) was called from RX@0x4003875b[libmain.so]0x3875b
JNIEnv->FindClass(android/content/Context) was called from RX@0x400387ab[libmain.so]0x387ab
JNIEnv->FindClass(com/alibaba/wireless/security/mainplugin/SecurityGuardMainPlugin) was called from RX@0x400569c9[libmain.so]0x569c9
JNIEnv->CallStaticObjectMethod(class com/alibaba/wireless/security/mainplugin/SecurityGuardMainPlugin, getMainPluginClassLoader()Ljava/lang/ClassLoader;) was called from RX@0x40056a13[libmain.so]0x56a13
JNIEnv->FindClass(com/alibaba/wireless/security/open/edgecomputing/ECMiscInfo) was called from RX@0x40056421[libmain.so]0x56421
JNIEnv->FindClass(com/alibaba/wireless/security/framework/utils/UserTrackMethodJniBridge) was called from RX@0x400289bb[libmain.so]0x289bb
JNIEnv->RegisterNatives(com/taobao/wireless/security/adapter/JNICLibrary, unidbg@0xbffff6e8, 1) was called from RX@0x400104e9[libmain.so]0x104e9
RegisterNative(com/taobao/wireless/security/adapter/JNICLibrary, doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object;, RX@0x40010231[libmain.so]0x10231)
JNIEnv->FindClass(java/lang/Integer) was called from RX@0x400b4b77[libmain.so]0xb4b77
JNIEnv->FindClass(java/lang/Float) was called from RX@0x400b4b77[libmain.so]0xb4b77
JNIEnv->FindClass(java/lang/String) was called from RX@0x400b4b77[libmain.so]0xb4b77
JNIEnv->FindClass([B) was called from RX@0x400b4b77[libmain.so]0xb4b77
JNIEnv->FindClass(java/util/HashMap) was called from RX@0x400b4b77[libmain.so]0xb4b77
JNIEnv->FindClass(java/util/Set) was called from RX@0x400b4b77[libmain.so]0xb4b77
Find native function Java_com_taobao_wireless_security_adapter_JNICLibrary_doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object; => RX@0x40010231[libmain.so]0x10231
JNIEnv->FindClass(com/alibaba/wireless/security/open/SecException) was called from RX@0x400b37d3[libmain.so]0xb37d3
JNIEnv->NewStringUTF("") was called from RX@0x400b37f7[libmain.so]0xb37f7
JNIEnv->NewObject(com/alibaba/wireless/security/open/SecException, <init>) was called from RX@0x400b380b[libmain.so]0xb380b
[18:00:27 023]  WARN [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$3:104) - Throw object=unidbg@0x441772e, dvmObject=com.alibaba.wireless.security.open.SecException@441772e, class=class com/alibaba/wireless/security/open/SecException
hash:0
Find native function Java_com_taobao_wireless_security_adapter_JNICLibrary_doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object; => RX@0x40010231[libmain.so]0x10231
JNIEnv->GetObjectArrayElement([java.util.HashMap@62150f9e, "21646297", 0x7, null, true], 0) was called from RX@0x400b4d63[libmain.so]0xb4d63
JNIEnv->CallObjectMethod(java/util/HashMap, keySet()Ljava/util/Set; => java.util.Set@15ff3e9e) was called from RX@0x400b4dbb[libmain.so]0xb4dbb
JNIEnv->CallObjectMethod(java/util/Set, toArray()[Ljava/lang/Object; => ["INPUT"]) was called from RX@0x400b4dd7[libmain.so]0xb4dd7
JNIEnv->GetArrayLength(["INPUT"] => 1) was called from RX@0x400b4de7[libmain.so]0xb4de7
JNIEnv->GetObjectArrayElement(["INPUT"], 0) was called from RX@0x400b4e85[libmain.so]0xb4e85
JNIEnv->GetStringUtfChars("INPUT") was called from RX@0x400b32f5[libmain.so]0xb32f5
JNIEnv->ReleaseStringUTFChars("INPUT") was called from RX@0x400b333f[libmain.so]0xb333f
JNIEnv->CallObjectMethod(java/util/HashMap, get(Ljava/lang/Object;)Ljava/lang/Object; => "XPDlGfM+zOoDAMHyPLa9+Okq&&&21646297&99914b932bd37a50b983c5e7c90ae93b&1560149480&mtop.common.gettimestamp&*&&231200@taobao_android_8.8.0&AjA1TIyT9T8vcuFw8Osrli35ALbE3ZW2SHLZNuihw8Ku&&&27&&&&&&&") was called from RX@0x400b4ea5[libmain.so]0xb4ea5
JNIEnv->GetStringUtfChars("XPDlGfM+zOoDAMHyPLa9+Okq&&&21646297&99914b932bd37a50b983c5e7c90ae93b&1560149480&mtop.common.gettimestamp&*&&231200@taobao_android_8.8.0&AjA1TIyT9T8vcuFw8Osrli35ALbE3ZW2SHLZNuihw8Ku&&&27&&&&&&&") was called from RX@0x400b3367[libmain.so]0xb3367
JNIEnv->ReleaseStringUTFChars("XPDlGfM+zOoDAMHyPLa9+Okq&&&21646297&99914b932bd37a50b983c5e7c90ae93b&1560149480&mtop.common.gettimestamp&*&&231200@taobao_android_8.8.0&AjA1TIyT9T8vcuFw8Osrli35ALbE3ZW2SHLZNuihw8Ku&&&27&&&&&&&") was called from RX@0x400b337d[libmain.so]0xb337d
JNIEnv->GetObjectArrayElement([java.util.HashMap@62150f9e, "21646297", 0x7, null, true], 1) was called from RX@0x400b4829[libmain.so]0xb4829
JNIEnv->GetStringUtfChars("21646297") was called from RX@0x400b3367[libmain.so]0xb3367
JNIEnv->ReleaseStringUTFChars("21646297") was called from RX@0x400b337d[libmain.so]0xb337d
JNIEnv->GetObjectArrayElement([java.util.HashMap@62150f9e, "21646297", 0x7, null, true], 2) was called from RX@0x400b4861[libmain.so]0xb4861
JNIEnv->CallIntMethod(java/lang/Integer, intValue()I => 0x7) was called from RX@0x40028edd[libmain.so]0x28edd
JNIEnv->GetObjectArrayElement([java.util.HashMap@62150f9e, "21646297", 0x7, null, true], 3) was called from RX@0x400b4829[libmain.so]0xb4829
JNIEnv->GetObjectArrayElement([java.util.HashMap@62150f9e, "21646297", 0x7, null, true], 4) was called from RX@0x400b4899[libmain.so]0xb4899
JNIEnv->CallBooleanMethod(java/lang/Boolean, booleanValue()Z => true) was called from RX@0x400b393f[libmain.so]0xb393f
JNIEnv->FindClass(com/alibaba/wireless/security/open/SecException) was called from RX@0x400b37d3[libmain.so]0xb37d3
JNIEnv->NewStringUTF("") was called from RX@0x400b37f7[libmain.so]0xb37f7
JNIEnv->NewObject(com/alibaba/wireless/security/open/SecException, <init>) was called from RX@0x400b380b[libmain.so]0xb380b
[18:00:27 054]  WARN [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$3:104) - Throw object=unidbg@0x158da8e, dvmObject=com.alibaba.wireless.security.open.SecException@158da8e, class=class com/alibaba/wireless/security/open/SecException
hash:0
Find native function Java_com_taobao_wireless_security_adapter_JNICLibrary_doCommandNative(I[Ljava/lang/Object;)Ljava/lang/Object; => RX@0x40010231[libmain.so]0x10231
JNIEnv->GetObjectArrayElement([0x0, false], 0) was called from RX@0x400b4861[libmain.so]0xb4861
JNIEnv->CallIntMethod(java/lang/Integer, intValue()I => 0x0) was called from RX@0x40037213[libmain.so]0x37213
JNIEnv->GetObjectArrayElement([0x0, false], 1) was called from RX@0x400b4899[libmain.so]0xb4899
JNIEnv->CallBooleanMethod(java/lang/Boolean, booleanValue()Z => false) was called from RX@0x400b393f[libmain.so]0xb393f
JNIEnv->CallStaticVoidMethod(class com/taobao/dp/util/CallbackHelper, onCallBack(ILjava/lang/String;I)V) was called from RX@0x40039f7b[libmain.so]0x39f7b
JNIEnv->NewStringUTF("000000000000000000000000") was called from RX@0x400b34d9[libmain.so]0xb34d9
hash:1525919705
Exception in thread "main" java.lang.NullPointerException
	at cn.byboy.TestSignso.test(TestSignso.java:121)
	at cn.byboy.TestSignso.main(TestSignso.java:93)
Disconnected from the target VM, address: '127.0.0.1:51543', transport: 'socket'

**Comment by LeToNode** [comment]
看上去是内存地址的偏移量有问题。
