### ISSUE TITLE
How to vm.setJni, all the Jni's implements are invisible or abstract (  AbstractJni[abstract] JniFunction[abstract]  ProxyJni[Package available]) , i cant not new Construct, should i implement class myself?

### ISSUE THREAD

**Issue by lidongbo** [zhkl0228/unidbg#216]
[14:44:04 756]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:446) - handleInterrupt intno=2, NR=-1073744064, svcNumber=0x113, PC=unidbg@0xfffe01c4, syscall=null
java.lang.IllegalStateException: **Please vm.setJni(jni)**
	at com.github.unidbg.linux.android.dvm.Hashable.checkJni(Hashable.java:8)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callObjectMethod(DvmMethod.java:70)
	at com.github.unidbg.linux.android.dvm.DalvikVM$20.handle(DalvikVM.java:372)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:103)
	at com.github.unidbg.arm.backend.UnicornBackend$6.hook(UnicornBackend.java:271)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:296)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:382)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:471)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:215)
	at com.github.unidbg.Module.emulateFunction(Module.java:154)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:128)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:277)
	at com.xxx(xxx.java:162)
	at xxxmain(xxx.java:66)

**Comment by lidongbo** [comment]
i find a way, that works fine. closed this issue.
