### ISSUE TITLE
unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED) bytedance 某车帝

### ISSUE THREAD

**Issue by tanchichong** [zhkl0228/unidbg#245]
> 调用某车帝 llibtfcc.so 中 tfccDecrypt(int i, String str, String str2); 方法
> 参数i：1
> 参数str：14zRM+40n2UGVx0DlI7hqDFjsxGR6eJsnnxUME5ZDT8=
> 参数str2: BQADAggAxzHqH07gvkuZptzo1OjSi/6LI9LXorqXAICkO0f2ILbt//z0V/CGpy6k4m6JlehN5PA1AtqHz6QSJhN3mRXb9ip5QySI61kGDuYhXqBxxcpfcW+Va9l4DgkMLdczm5bBb3HTdchxgmlzmfZ0xtE2mhgug5V87hWZZHZyhd/qs9pc1zeBl51elaei9IHES5JEBtof0QsJp8TGDM7f6PXumwD7a8pDVrDQQovnDEhCMwQx503TE33z1YjUguq4w3HsraEgsrylbZfnFCW2vlu0a1wESE2HgY2DSIdc77v8XbUhe/XdTZM9wD+P2+tGtJU+m/1sL/n63EwPTE7g1qUH6uc7rwI6kINYbPh44QcbUgXBRa9E4Pfa7JSWVVC8eqHvFLka1uD/5DGGpMeQURT78OUkrodChAlFC2JziHhvGGQmE5Lo/XLSJ3OwGISEXWKRd2elyvUuG4v0ALRzmOaFRjGQV5v5Qr7hPeO8wNf9/6fDYvWpb0sVaGG86b/gsGSPfPZF2NzA+wADHwH405R8LeVAVmyNdlJQ5PvxxtV79HG88n0ZBIVzsPlaqyozyS5/nuYtundmTkM2Rr+0sMMd3x8qUHXIdIR5fzyJmEVPcSkrrb9KR1xeapcyGW4ueM54tL/d/QBoQOOgI0U14Zf1Ph350mI=

调用出现错误如下，且程序一直停在方法callStaticJniMethodObject
14:40:20.020 [main] WARN com.github.unidbg.arm.AbstractARMEmulator - memory failed: address=0x27c, size=1, value=0x0, PC=unidbg@0x27c, LR=RX@0x4000903f[libtfcc.so]0x903f
debugger break at: 0x27c
>>> r0=0xfffe0a50(-128432) r1=0x3399da6d r2=0xf4f3cce3 r3=0xfffffffd r4=0xbffff768 r5=0xfffffffd r6=0x40211008 r7=0xbffff788 r8=0x3399da6d sb=0xfffe0a50 sl=0x0 fp=0x0 ip=0x27c SP=0xbffff760 LR=RX@0x4000903f[libtfcc.so]0x903f PC=unidbg@0x27c cpsr: N=0, Z=1, C=1, V=0, T=0, mode=0b10000
com.github.unidbg.arm.backend.BackendException: unicorn.UnicornException: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:298)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:382)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:471)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:215)
	at com.github.unidbg.Module.emulateFunction(Module.java:154)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:128)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:291)
	at cn.atgco.webmagic.util.JniDispatch32.test(JniDispatch32.java:64)
	at cn.atgco.webmagic.util.JniDispatch32.main(JniDispatch32.java:56)
Caused by: unicorn.UnicornException: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:296)
	... 8 more
com.github.unidbg.arm.backend.BackendException: unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at com.github.unidbg.arm.backend.UnicornBackend.mem_read(UnicornBackend.java:101)
	at com.github.unidbg.arm.CodeHistory.disassemble(CodeHistory.java:20)
	at com.github.unidbg.arm.AbstractARMDebugger.disassemble(AbstractARMDebugger.java:610)
	at com.github.unidbg.arm.SimpleARMDebugger.loop(SimpleARMDebugger.java:37)
	at com.github.unidbg.arm.AbstractARMDebugger.debug(AbstractARMDebugger.java:187)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:399)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:471)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:215)
	at com.github.unidbg.Module.emulateFunction(Module.java:154)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:128)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:291)
	at cn.atgco.webmagic.util.JniDispatch32.test(JniDispatch32.java:64)
	at cn.atgco.webmagic.util.JniDispatch32.main(JniDispatch32.java:56)
Caused by: unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at unicorn.Unicorn.mem_read(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.mem_read(UnicornBackend.java:99)
	... 12 more

程序代码：
‘
import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.LibraryResolver;
import com.github.unidbg.Module;
import com.github.unidbg.linux.android.AndroidARMEmulator;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.jni.ProxyClassFactory;
import com.github.unidbg.memory.Memory;

import java.io.File;
import java.io.IOException;

public class JniDispatch32 {

    private static LibraryResolver createLibraryResolver() {
        return new AndroidResolver(23);
    }

    private static AndroidEmulator createARMEmulator() {
        return new AndroidARMEmulator("com.sun.jna");
    }

    private final AndroidEmulator emulator;
    private final Module module;

    private final DvmClass cNative;

    private JniDispatch32() {
        emulator = createARMEmulator();
        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(createLibraryResolver());

        VM vm = emulator.createDalvikVM(null);
        vm.setDvmClassFactory(new ProxyClassFactory());
        vm.setVerbose(true);
        DalvikModule dm = vm.loadLibrary(new File("D:\\atg_project\\atg_webmagic\\src\\main\\resources\\dongchedi\\libtfcc.so"), false);
        dm.callJNI_OnLoad(emulator);
        module = dm.getModule();

        cNative = vm.resolveClass("com/ss/android/tfcc/Tfcc");
    }

    private void destroy() throws IOException {
        emulator.close();
        System.out.println("destroy");
    }

    public static void main(String[] args) throws Exception {
        JniDispatch32 test = new JniDispatch32();
        test.test();
        test.destroy();
    }

    private void test() {
        String str = "BQADAggAxzHqH07gvkuZptzo1OjSi/6LI9LXorqXAICkO0f2ILbt//z0V/CGpy6k4m6JlehN5PA1AtqHz6QSJhN3mRXb9ip5QySI61kGDuYhXqBxxcpfcW+Va9l4DgkMLdczm5bBb3HTdchxgmlzmfZ0xtE2mhgug5V87hWZZHZyhd/qs9pc1zeBl51elaei9IHES5JEBtof0QsJp8TGDM7f6PXumwD7a8pDVrDQQovnDEhCMwQx503TE33z1YjUguq4w3HsraEgsrylbZfnFCW2vlu0a1wESE2HgY2DSIdc77v8XbUhe/XdTZM9wD+P2+tGtJU+m/1sL/n63EwPTE7g1qUH6uc7rwI6kINYbPh44QcbUgXBRa9E4Pfa7JSWVVC8eqHvFLka1uD/5DGGpMeQURT78OUkrodChAlFC2JziHhvGGQmE5Lo/XLSJ3OwGISEXWKRd2elyvUuG4v0ALRzmOaFRjGQV5v5Qr7hPeO8wNf9/6fDYvWpb0sVaGG86b/gsGSPfPZF2NzA+wADHwH405R8LeVAVmyNdlJQ5PvxxtV79HG88n0ZBIVzsPlaqyozyS5/nuYtundmTkM2Rr+0sMMd3x8qUHXIdIR5fzyJmEVPcSkrrb9KR1xeapcyGW4ueM54tL/d/QBoQOOgI0U14Zf1Ph350mI=";
        String key = "14zRM+40n2UGVx0DlI7hqDFjsxGR6eJsnnxUME5ZDT8=";

        Object version = cNative.callStaticJniMethodObject(emulator, "tfccDecrypt(ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String", 1, key, str);
    }

}
`

**Comment by zhkl0228** [comment]
像是0x27c对应的jni方法没实现

**Comment by tianxingzhou** [comment]
> 像是0x27c对应的jni方法没实现

您好，还是有点不太懂，麻烦可以再说的详细点么，谢谢了。
首先不太清楚0x27c代表什么，还有怎么实现对应的jni方法 👍

**Comment by zhkl0228** [comment]
最新版已实现，参考：https://github.com/zhkl0228/unidbg/commit/ff577521128554f0c4d96e2940e4ce4811a88fe5

**Comment by tianxingzhou** [comment]
> 最新版已实现，参考：[ff57752](https://github.com/zhkl0228/unidbg/commit/ff577521128554f0c4d96e2940e4ce4811a88fe5)

    @zhkl0228 您好，根据您最新的代码重新测试了一下，之前那个问题没有再出现了，非常感谢，但是又出现了一个新问题：
    您的项目com.github.unidbg.linux.android.dvm.jni.ProxyJni类的setStaticIntField方法，这行代码Class<?> clazz = classLoader.loadClass(dvmClass.getName());
    提示 com.ss.android.tfcc.Tfcc 加载类没有找到，这个类是我反编译apk后，JNI调用的native方法所在的类，按理说您的项目中确实应该不会有这个类，确实应该报错。
    我这边不太清楚，这是个bug还是我这边需要把那个类放到您的项目中，还望您有空的时候，帮忙解答一下，谢谢🙏，以下是报错代码：

    JNIEnv->GetArrayLength([B@34f9cff1 => 44) was called from RX@0x40008919[libtfcc.so]0x8919
    [21:58:23 110]  WARN [com.github.unidbg.linux.android.dvm.jni.ProxyJni] (ProxyJni:627) - setStaticIntField
    java.lang.ClassNotFoundException: com.ss.android.tfcc.Tfcc
	    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	    at java.security.AccessController.doPrivileged(Native Method)
	    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	    at com.github.unidbg.linux.android.dvm.jni.ProxyClassLoader.loadClass(ProxyClassLoader.java:22)
	    at com.github.unidbg.linux.android.dvm.jni.ProxyJni.setStaticIntField(ProxyJni.java:622)
	    at com.github.unidbg.linux.android.dvm.DvmField.setStaticIntField(DvmField.java:104)
	    at com.github.unidbg.linux.android.dvm.DalvikVM$65.handle(DalvikVM.java:1445)
	    at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:93)
	    at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
	    at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend32.callSVC(DynarmicBackend32.java:32)
	    at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
	    at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:60)
	    at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:72)
	    at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:395)
	    at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:472)
	    at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:217)
	    at com.github.unidbg.Module.emulateFunction(Module.java:154)
	    at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:128)
	    at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:291)
	    at com.dongchedi.JniDispatch32Dongchedi.test(JniDispatch32Dongchedi.java:66)
	    at com.dongchedi.JniDispatch32Dongchedi.main(JniDispatch32Dongchedi.java:59)
    [21:58:23 115]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:436) - handleInterrupt         intno=2, NR=-1073743992, svcNumber=0x140, PC=unidbg@0xfffe0494, syscall=null
    java.lang.UnsupportedOperationException: com/ss/android/tfcc/Tfcc->sError:I
	    at com.github.unidbg.linux.android.dvm.JniFunction.setStaticIntField(JniFunction.java:382)
	    at com.github.unidbg.linux.android.dvm.jni.ProxyJni.setStaticIntField(ProxyJni.java:629)
	    at com.github.unidbg.linux.android.dvm.DvmField.setStaticIntField(DvmField.java:104)
	    at com.github.unidbg.linux.android.dvm.DalvikVM$65.handle(DalvikVM.java:1445)
	    at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:93)
	    at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
	    at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend32.callSVC(DynarmicBackend32.java:32)
	    at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
	    at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:60)
	    at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:72)
	    at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:395)
	    at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:472)
	    at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:217)
	    at com.github.unidbg.Module.emulateFunction(Module.java:154)
	    at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:128)
	    at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:291)
	    at com.dongchedi.JniDispatch32Dongchedi.test(JniDispatch32Dongchedi.java:66)
	    at com.dongchedi.JniDispatch32Dongchedi.main(JniDispatch32Dongchedi.java:59)
    [21:58:23 115]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:414) - emulate     RX@0x40008f85[libtfcc.so]0x8f85 exception sp=unidbg@0xbffff760, msg=com/ss/android/tfcc/Tfcc->sError:I, offset=38ms
    destroy

    Process finished with exit code 0

**Comment by zhkl0228** [comment]
你设置了vm.setDvmClassFactory(new ProxyClassFactory());
表示JNI调用的java会反射调用，不存在的java类你补全就行

**Comment by greedy-worm** [comment]
> 你设置了vm.setDvmClassFactory(new ProxyClassFactory());
> 表示JNI调用的java会反射调用，不存在的java类你补全就行

@zhkl0228 您好，我这边换成了vm.setJni(this); 或者将提示少的类导入到您的项目中后，都会提示这个错误，不太理解这个错误都意思，还望解答，谢谢。

以下是报错信息，及源码

    JNIEnv->GetArrayLength([B@67e37e4a => 44) was called from RX@0x40008919[libtfcc.so]0x8919
    [00:52:23 769]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:436) - handleInterrupt     intno=2, NR=-1073743992, svcNumber=0x140, PC=unidbg@0xfffe0494, syscall=null
    java.lang.UnsupportedOperationException: com/ss/android/tfcc/Tfcc->sError:I
	    at com.github.unidbg.linux.android.dvm.AbstractJni.setStaticIntField(AbstractJni.java:785)
	    at com.github.unidbg.linux.android.dvm.AbstractJni.setStaticIntField(AbstractJni.java:780)
	    at com.github.unidbg.linux.android.dvm.DvmField.setStaticIntField(DvmField.java:104)
	    at com.github.unidbg.linux.android.dvm.DalvikVM$65.handle(DalvikVM.java:1445)
	    at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:93)
	    at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
	    at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend32.callSVC(DynarmicBackend32.java:32)
	    at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
	    at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:60)
	    at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:72)
	    at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:395)
	    at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:472)
	    at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:217)
	    at com.github.unidbg.Module.emulateFunction(Module.java:154)
	    at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:128)
	    at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:291)
	    at com.dongchedi.JniDispatch32Dongchedi.test(JniDispatch32Dongchedi.java:64)
	    at com.dongchedi.JniDispatch32Dongchedi.main(JniDispatch32Dongchedi.java:57)
    [00:52:23 774]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:414) - emulate     RX@0x40008f85[libtfcc.so]0x8f85 exception sp=unidbg@0xbffff760, msg=com/ss/android/tfcc/Tfcc->sError:I, offset=46ms
    destroy

    Process finished with exit code 0

源码：

    import com.github.unidbg.AndroidEmulator;
    import com.github.unidbg.LibraryResolver;
    import com.github.unidbg.Module;
    import com.github.unidbg.arm.backend.DynarmicFactory;
    import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
    import com.github.unidbg.linux.android.AndroidResolver;
    import com.github.unidbg.linux.android.dvm.*;
    import com.github.unidbg.memory.Memory;

    import java.io.File;
    import java.io.IOException;

    public class JniDispatch32Dongchedi extends AbstractJni {
        private static LibraryResolver createLibraryResolver() {
            return new AndroidResolver(23);
        }
    
        private static AndroidEmulator createARMEmulator() {
            return AndroidEmulatorBuilder.for32Bit()
                    .setProcessName("com.sun.jna")
                    .addBackendFactory(new DynarmicFactory(true))
                    .build();
        }

        private final AndroidEmulator emulator;
        private final Module module;
    
        private final DvmClass cNative;
    
        private JniDispatch32Dongchedi() {
            emulator = createARMEmulator();
            final Memory memory = emulator.getMemory();
            memory.setLibraryResolver(createLibraryResolver());

    //        VM vm = emulator.createDalvikVM(null);
    //        vm.setDvmClassFactory(new ProxyClassFactory());
            VM vm = emulator.createDalvikVM(new File("unidbg-android/src/test/resources/example_binaries/dongchedi-   4.0.0.apk"));
            vm.setJni(this);
    
            vm.setVerbose(true);
            DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/libtfcc.so"), false);
            dm.callJNI_OnLoad(emulator);
            module = dm.getModule();
    
            cNative = vm.resolveClass("com/ss/android/tfcc/Tfcc");
        }

        private void destroy() throws IOException {
            emulator.close();
            System.out.println("destroy");
        }
    
        public static void main(String[] args) throws Exception {
            JniDispatch32Dongchedi test = new JniDispatch32Dongchedi();
            test.test();
            test.destroy();
        }

        private void test() {
            String str =     "BQADAggAxzHqH07gvkuZptzo1OjSi/6LI9LXorqXAICkO0f2ILbt//z0V/CGpy6k4m6JlehN5PA1AtqHz6QSJhN3mRXb9ip5QySI61kGDuYhXqBxxcpfcW+Va9l4DgkMLdczm5bBb3HTdchxgmlzmfZ0xtE2mhgug5V87hWZZHZyhd/qs9pc1zeBl51elaei9IHES5JEBtof0QsJp8TGDM7f6PXumwD7a8pDVrDQQovnDEhCMwQx503TE33z1YjUguq4w3HsraEgsrylbZfnFCW2vlu0a1wESE2HgY2DSIdc77v8XbUhe/XdTZM9wD+P2+tGtJU+m/1sL/n63EwPTE7g1qUH6uc7rwI6kINYbPh44QcbUgXBRa9E4Pfa7JSWVVC8eqHvFLka1uD/5DGGpMeQURT78OUkrodChAlFC2JziHhvGGQmE5Lo/XLSJ3OwGISEXWKRd2elyvUuG4v0ALRzmOaFRjGQV5v5Qr7hPeO8wNf9/6fDYvWpb0sVaGG86b/gsGSPfPZF2NzA+wADHwH405R8LeVAVmyNdlJQ5PvxxtV79HG88n0ZBIVzsPlaqyozyS5/nuYtundmTkM2Rr+0sMMd3x8qUHXIdIR5fzyJmEVPcSkrrb9KR1xeapcyGW4ueM54tL/d/QBoQOOgI0U14Zf1Ph350mI=";
            String key = "14zRM+40n2UGVx0DlI7hqDFjsxGR6eJsnnxUME5ZDT8=";
            DvmObject<?> obj = cNative.callStaticJniMethodObject(emulator,     "tfccDecrypt(ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String", 1, key, str);
        }
    
    }
`

**Comment by zhkl0228** [comment]
这是最基本的使用问题，多参考示例

**Comment by tanchichong** [comment]
最初的问题已解决，正在查找其他错误。
