### ISSUE TITLE
so文件读取了/proc/self/maps的内容，但读到的内容貌似为空，是否可以在外部源码对虚拟机里的maps文件进行操作？

### ISSUE THREAD

**Issue by huake1984** [zhkl0228/unidbg#271]
@zhkl0228 
程序执行过程报如下错误：
File opened '/proc/self/maps' with oflags=0x20000 from RX@0x4001502b[libcms.so]0x1502b
Read 1004 bytes from '/proc/self/maps'
File closed '/proc/self/maps' from RX@0x40015767[libcms.so]0x15767
File opened '' with oflags=0x20000 from RX@0x4001502b[libcms.so]0x1502b
signature = java/lang/System->getProperty(Ljava/lang/String;)Ljava/lang/String;
[08:51:48 277]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:446) - handleInterrupt intno=2, NR=19, svcNumber=0x0, PC=RX@0x4000b354[libcms.so]0xb354, syscall=null
java.lang.AbstractMethodError: class=class com.github.unidbg.linux.file.DirectoryFileIO, offset=0x0, whence=0
	at com.github.unidbg.file.AbstractFileIO.lseek(AbstractFileIO.java:102)
	at com.github.unidbg.linux.ARM32SyscallHandler.lseek(ARM32SyscallHandler.java:1943)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:146)
	at com.github.unidbg.arm.backend.UnicornBackend$6.hook(UnicornBackend.java:299)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:325)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:369)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:445)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:217)
	at com.github.unidbg.Module.emulateFunction(Module.java:158)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:128)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:259)
	at com.jz.dy.XGenerator1300.dyXGGenerate(XGenerator1300.java:132)
	at com.jz.dy.XGenerator1300.main(XGenerator1300.java:42)

**Comment by tanzui** [comment]
implements IOResolver

@Override
    public FileResult resolve(Emulator emulator, String pathname, int oflags) {
        System.out.println("xxxxxxxxxxxx");
        System.out.println("----" + pathname);

        if(pathname.equals("/proc/self/maps"))
        {
            return FileResult.success(new ByteArrayFileIO(oflags,pathname,"--------- beginning of system".getBytes()));
        }

        return null;
    }
