### ISSUE TITLE
jni 调用java 层的函数，加了setDvmClassFactory 仍然不行，测试发下，这里有问题。

### ISSUE THREAD

**Issue by zqqq** [zhkl0228/unidbg#278]
`com/github/unidbg/linux/android/dvm/DvmClass.java     47行

@Override
    public DvmClass getObjectType() {

        //输出测试，className 是自己定义的内容，不是ROOT_CLASS的 java/lang/Class 这里永远不会返回 this，导致后面
        // com/github/unidbg/linux/android/dvm/DalvikVM64.java 里，所有的_callxxxMethod里的
        // DvmClass dvmClass = dvmObject == null ? null : dvmObject.getObjectType();  这一行 返回的是错的

        if (ROOT_CLASS.equals(className)) { //这里是不是错了？我改成   if (!ROOT_CLASS.equals(className)) { 之后才正常
            return this;
        }

        return super.getObjectType();
    }`

**Comment by zqqq** [comment]
改之前报错：
java.lang.UnsupportedOperationException: clk_id=2
at com.github.unidbg.linux.ARM64SyscallHandler.clock_gettime(ARM64SyscallHandler.java:1014)
at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:224)
at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend64.callSVC(DynarmicBackend64.java:42)
at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)

改之后报错：
java.lang.UnsupportedOperationException: com/xx/Ai->cpp_put()V
	at com.github.unidbg.linux.android.dvm.JniFunction.callVoidMethodV(JniFunction.java:152)
	at com.github.unidbg.linux.android.dvm.jni.ProxyJni.callVoidMethodV(ProxyJni.java:232)

这里已经能正常提示缺少的 函数了，自己对应的实现它就可以了。

**Comment by zhkl0228** [comment]
方便发测试用例吗？我跑下看看

**Comment by zqqq** [comment]
我的这个so回调的Java类，和jni注册的类是同一个，

调用jni的类比如是这个
nt = vm.resolveClass("com/and/NT");

那这个so里的回调java的函数是
com.and.NT.put_str

不知道是不是这个原因，我这个so没有办法上传，等我空了，我自己编写一个jni 测试下是不是因为 注册类和回调类相同的问题。
