### ISSUE TITLE
调用getFileDirMethodId的时候报了dvmMethod 为空的异常，代码及so已上传百度盘

### ISSUE THREAD

**Issue by mengmugai** [zhkl0228/unidbg#279]
so和java文件已打包
链接: https://pan.baidu.com/s/14fNZHX59Hen6PrRgyM9qQg  密码: a048

错误：
```
com.github.unidbg.arm.backend.BackendException: dvmObject=class com/yuanrenxue/onlinejudge2020/OnlineJudgeApp, dvmClass=class java/lang/Class, jmethodID=unidbg@0xe7b3e1b9
	at com.github.unidbg.linux.android.dvm.DalvikVM$21.handle(DalvikVM.java:400)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:103)
	at com.github.unidbg.arm.backend.UnicornBackend$6.hook(UnicornBackend.java:299)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:325)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:369)
        ..........后面还有一堆。。。。。。
```
代码异常位置也就是DalvikVM.java:400
```
DvmMethod dvmMethod = dvmClass == null ? null : dvmClass.getMethod(jmethodID.toIntPeer());
                if (dvmMethod == null) {
                            异常。。。
```
好像是没有获得方法
ida对应的函数
```
 v10 = sub_CD237A14(v3, v4, getFileDirMethodId, v9);
  v12 = sub_CD237A14(v3, v10, fileGetAbsolutePathMethodId, v11);
```
sub_CD237A14中是
```
int __fastcall sub_CD237A14(_JNIEnv *a1, int a2, int getFileDirMethodId, int a4)
{
  int vars8; // [sp+1Ch] [bp+8h]

  vars8 = a4;
  return (a1->functions->CallObjectMethodV)();
}
```

大佬  这种怎么解决555555555

**Comment by 592767809** [comment]
https://github.com/zhkl0228/unidbg/issues/267

**Comment by mengmugai** [comment]
> [＃267](https://github.com/zhkl0228/unidbg/issues/267)

有hook的代码吗  学习学习

**Comment by 592767809** [comment]
> > [＃267](https://github.com/zhkl0228/unidbg/issues/267)
> 
> 有hook的代码吗学习学习

hook其实不是一个好方法，只是临时解决的，还是希望作者可以修复一下getFileDirMethodId的问题

**Comment by zhkl0228** [comment]
两处地方要改：
一：DvmClass cContext = vm.resolveClass("android/content/Context");
        DvmClass cContextWrapper = vm.resolveClass("android/content/ContextWrapper", cContext);
        cNative = vm.resolveClass("com/yuanrenxue/onlinejudge2020/OnlineJudgeApp", cContextWrapper);
二：cNative.newObject(null).callJniMethodObject

**Comment by 592767809** [comment]
> 两处地方要改，第一步确认继承关系：
> 一：DvmClass cContext = vm.resolveClass("android/content/Context");
> DvmClass cContextWrapper = vm.resolveClass("android/content/ContextWrapper", cContext);
> cNative = vm.resolveClass("com/yuanrenxue/onlinejudge2020/OnlineJudgeApp", cContextWrapper);
> 二：cNative.newObject(null).callJniMethodObject

我尝试使用楼主提供的代码，并修改了这两处地方，在不HOOK函数的情况下，依然在相同的地方报错
代码链接：链接: https://pan.baidu.com/s/1E_r6qcuFoh1_anhlFDBgIA 提取码: 7hcc

**Comment by zhkl0228** [comment]
第一处修改要在调用JNI_OnLoad之前执行

**Comment by 592767809** [comment]
> 第一处修改要在调用JNI_OnLoad之前执行

感谢作者，修改后可以正常运行

**Comment by 592767809** [comment]
> > 第一处修改要在调用JNI_OnLoad之前执行
> 
> 感谢作者，修改后可以正常运行，不过关于修改一，还有个小问题想问一下。继承关系上面，为什么使用android/content/Context，因为我从jadx中看到OnlineJudgeApp类是继承自android/app/Application。最后果然用android/app/Application继承的话就会报错

**Comment by zhouxy158** [comment]
Application继承自android/content/ContextWrapper，因为在JNI_OnLoad中getMethodId使用的class是android/content/ContextWrapper，主要是要表明继承自android/content/ContextWrapper就能解决问题

**Comment by zhkl0228** [comment]
所以改成这样也可以：
DvmClass cContextWrapper = vm.resolveClass("android/content/ContextWrapper");
        cNative = vm.resolveClass("com/yuanrenxue/onlinejudge2020/OnlineJudgeApp", cContextWrapper);

**Comment by 592767809** [comment]
> Application继承自android/content/ContextWrapper，因为在JNI_OnLoad中getMethodId使用的class是android/content/ContextWrapper，主要是要表明继承自android/content/ContextWrapper就能解决问题

原来如此，明白了

**Comment by shuirouyan** [comment]
> > 第一处修改要在调用JNI_OnLoad之前执行
> 
> 感谢作者，修改后可以正常运行

你好，可以把你修改后的代码截图看看吗？

**Comment by shuirouyan** [comment]
> > 第一处修改要在调用JNI_OnLoad之前执行
> 
> 感谢作者，修改后可以正常运行

你好，可以把你修改后的代码截图看看吗？
