### ISSUE TITLE
HookZz如何修改方法返回值

### ISSUE THREAD

**Issue by xuanyangyang** [zhkl0228/unidbg#283]
请问怎么修改lrand48方法的返回值？在工程里没有发现有获取返回值并修改的demo，希望大佬可以指导一下，谢谢啦
如下两种写法代码，在`pointer.getInt`处会有UC_ERR_READ_UNMAPPED报错
```java
        Symbol lrand48 = module.findSymbolByName("lrand48");
        hookZz.replace(lrand48, new ReplaceCallback() {
            @Override
            public void postCall(Emulator<?> emulator, HookContext context) {
                UnidbgPointer pointer = context.getPointerArg(0);
                log.info("lrand48 return:" + pointer.getInt(0));
                pointer.setInt(0, 1);
            }
        }, true);
```
```java
        Symbol lrand48 = module.findSymbolByName("lrand48");
        hookZz.wrap(lrand48, new WrapCallback<>() {
            @Override
            public void preCall(Emulator<?> emulator, RegisterContext ctx, HookEntryInfo info) {
                log.info("lrand48");
            }

            @Override
            public void postCall(Emulator<?> emulator, RegisterContext ctx, HookEntryInfo info) {
                UnidbgPointer pointer = ctx.getPointerArg(0);
                log.info("lrand48 return:" + pointer.getInt(0));
                pointer.setInt(0, 1);
            }
        });
```
报错堆栈如下：
```
com.github.unidbg.arm.backend.BackendException: unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at com.github.unidbg.arm.backend.UnicornBackend.mem_read(UnicornBackend.java:108) ~[unidbg-api-0.9.3.jar:na]
	at com.github.unidbg.pointer.UnidbgPointer.getByteArray(UnidbgPointer.java:266) ~[unidbg-api-0.9.3.jar:na]
	at com.github.unidbg.pointer.UnidbgPointer.getByteBuffer(UnidbgPointer.java:284) ~[unidbg-api-0.9.3.jar:na]
	at com.github.unidbg.pointer.UnidbgPointer.getInt(UnidbgPointer.java:229) ~[unidbg-api-0.9.3.jar:na]
	at io.github.xuanyangyang.seckill.demo.JDSoService$2.postCall(JDSoService.java:97) ~[classes/:na]
	at com.github.unidbg.hook.BaseHook$2.handleCallback(BaseHook.java:50) ~[unidbg-api-0.9.3.jar:na]
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:84) ~[unidbg-android-0.9.3.jar:na]
	at com.github.unidbg.arm.backend.UnicornBackend$6.hook(UnicornBackend.java:291) ~[unidbg-api-0.9.3.jar:na]
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128) ~[unicorn-1.0.10.jar:na]
	at unicorn.Unicorn.emu_start(Native Method) ~[unicorn-1.0.10.jar:na]
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:316) ~[unidbg-api-0.9.3.jar:na]
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:395) ~[unidbg-api-0.9.3.jar:na]
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:472) ~[unidbg-api-0.9.3.jar:na]
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:217) ~[unidbg-api-0.9.3.jar:na]
	at com.github.unidbg.Module.emulateFunction(Module.java:154) ~[unidbg-api-0.9.3.jar:na]
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:128) ~[unidbg-android-0.9.3.jar:na]
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:291) ~[unidbg-android-0.9.3.jar:na]
```

**Comment by zhouxy158** [comment]
EditableArm32RegisterContext

**Comment by xuanyangyang** [comment]
> EditableArm32RegisterContext

可以详细点吗？

**Comment by xuanyangyang** [comment]
@zhkl0228 大佬可以解答一下吗？谢谢啦

**Comment by zhkl0228** [comment]
`Symbol lrand48 = module.findSymbolByName("lrand48");
        hookZz.wrap(lrand48, new WrapCallback<>() {
            @Override
            public void preCall(Emulator<?> emulator, EditableArm32RegisterContext ctx, HookEntryInfo info) {
                log.info("lrand48");
            }

            @Override
            public void postCall(Emulator<?> emulator, EditableArm32RegisterContext ctx, HookEntryInfo info) {
                int ret = ctx.getIntArg(0);
                log.info("lrand48 return:" + ret);
                ctx.setR0(1);
            }
        });`
