### ISSUE TITLE
您好，请问这个是什么原因呢，是我哪里没使用对吗

### ISSUE THREAD

**Issue by kevinsir** [zhkl0228/unidbg#288]
`JNIEnv->CallObjectMethodV(okio.Buffer@d2de489, writeString("deviceId=828946d1-b61d-37b2-ba53-cb2937737dae&identifier_flag=2&tz=Asia%2FShanghai&fid=1619148174103f454132a1240d373513823af784b876&device_fingerprint1=2021030315361930fb5eed688c476e338217f588d02005012f7f56e7bf9d6a&uis=light&launch_id=1619336844&device_fingerprint=2021030315361930fb5eed688c476e338217f588d02005012f7f56e7bf9d6a&versionName=6.68.1.1&platform=android&sid=session.1619148256908476285679&t=1619337147&x_trace_page_current=app_loading_page&lang=zh-Hans&channel=PMgdt11010428", java.nio.charset.Charset@2d52216b) => okio.Buffer@d2de489) was called from RX@0x40009885[libshield.so]0x9885
JNIEnv->CallObjectMethodV(okio.Buffer@d2de489, writeString("platform=android&build=6681005&deviceId=828946d1-b61d-37b2-ba53-cb2937737dae", java.nio.charset.Charset@2d52216b) => okio.Buffer@d2de489) was called from RX@0x40009885[libshield.so]0x9885
JNIEnv->CallObjectMethodV(okio.Buffer@d2de489, writeString("platform=android&build=6681005&deviceId=828946d1-b61d-37b2-ba53-cb2937737dae", java.nio.charset.Charset@2d52216b) => okio.Buffer@d2de489) was called from RX@0x40009885[libshield.so]0x9885
JNIEnv->CallVoidMethodV(okhttp3/RequestBody, writeTo(okio.Buffer@d2de489)) was called from RX@0x400098d5[libshield.so]0x98d5
JNIEnv->CallObjectMethodV(okio.Buffer@d2de489, clone() => Lokio.Buffer@5d908d47) was called from RX@0x40009885[libshield.so]0x9885
JNIEnv->NewByteArray(4096) was called from RX@0x4000abed[libshield.so]0xabed
[19:05:14 174]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:446) - handleInterrupt intno=2, NR=-1073744252, svcNumber=0x11a, PC=unidbg@0xfffe0234, syscall=null
com.github.unidbg.arm.backend.BackendException
	at com.github.unidbg.linux.android.dvm.DalvikVM$27.handle(DalvikVM.java:545)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:103)
	at com.github.unidbg.arm.backend.UnicornBackend$6.hook(UnicornBackend.java:299)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:325)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:369)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:445)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:217)
	at com.github.unidbg.Module.emulateFunction(Module.java:158)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:128)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethodObject(DvmObject.java:88)
	at com.xiaohongshu.ShieldService668.init(ShieldService668.java:158)
	at com.xiaohongshu.ShieldService668.main(ShieldService668.java:109)
[19:05:14 179]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:388) - emulate RX@0x40073b79[libshield.so]0x73b79 exception sp=unidbg@0xbffff678, msg=null, offset=2666ms
null`

**Comment by jpacg** [comment]
这是小红书的吧，小红书可以调用，应该是你代码写的不对。

**Comment by kevinsir** [comment]
是的，668可以的是吧，谢谢，至少感觉方向没有错。能否提示一下
okio/Buffer->writeString(Ljava/lang/String;Ljava/nio/charset/Charset;)Lokio/Buffer;
这块应该怎么写。感觉这里有问题

**Comment by kevinsir** [comment]
谢谢，我调试通过了，但是算出来的shield不一样，我找找什么原因

**Comment by kevinsir** [comment]
啊，已经成功了！谢谢！算法匹配上了
