### ISSUE TITLE
java.lang.UnsupportedOperationException: com/alibaba/wireless/security/framework/SGPluginExtras->slot:J 	at com.github.unidbg.linux.android.dvm.AbstractJni.getStaticLongField(AbstractJni.java:800)

### ISSUE THREAD

**Issue by xuejiandong** [zhkl0228/unidbg#294]
java.lang.UnsupportedOperationException: com/alibaba/wireless/security/framework/SGPluginExtras->slot:J
	at com.github.unidbg.linux.android.dvm.AbstractJni.getStaticLongField(AbstractJni.java:800)
这种怎么处理

**Comment by Jun-bit** [comment]
请问doCommandNative函数中的Object[]参数是如何传递的

**Comment by SuperYogurt** [comment]
> java.lang.UnsupportedOperationException: com/alibaba/wireless/security/framework/SGPluginExtras->slot:J
> at com.github.unidbg.linux.android.dvm.AbstractJni.getStaticLongField(AbstractJni.java:800)
> 这种怎么处理

解决了吗？老兄
