### ISSUE TITLE
项目集成到SpringBoot 引发 java.lang.NoSuchFieldError: OSX_ARM64 请问是什么原因呢

### ISSUE THREAD

**Issue by kevinsir** [zhkl0228/unidbg#296]
AndroidEmulatorBuilder.for32Bit()
                .setProcessName("com.xinjin.xhs")
                .addBackendFactory(new HypervisorFactory(true))
                .build();
在这里报错了
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.damei.xhs.xhsshield.controller.Xhs668Controller]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: OSX_ARM64
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1308)
	... 18 more
Caused by: java.lang.NoSuchFieldError: OSX_ARM64

**Comment by kevinsir** [comment]
我用了之前的0.9.2的没有这个问题，0.9.3这个就有问题

**Comment by killercc** [comment]
更新 unidbg-server pom 中的 unicorn 以及相关的 unidbg依赖 全部更至最新
