### ISSUE TITLE
关于”Pointer _GetStringUTFChars = svcMemory.registerSvc(“中NullPointerException的问题

### ISSUE THREAD

**Issue by hu-jinwen** [zhkl0228/unidbg#308]
请教一下大佬，小弟在调用so中的方法的时候，
`DalvikVM.`类中的`Pointer _GetStringUTFChars = svcMemory.registerSvc`中的 `StringObject string = getObject(UnicornPointer.register(emulator, ArmConst.UC_ARM_REG_R1).toUIntPeer());`获取到的string为null，导致下面出现空指针异常。
不知道这段代码的作用是什么，非常感激大佬指点迷津！！！
![](https://joe-data.oss-cn-hangzhou.aliyuncs.com/pic-bed/2021-05-18/37ab3618bf95d4871dd2378f29b0b2a9.png)
```bash
INFO: pthread_clone child_stack=RW@0x4025cdd0, thread_id=1, fn=RX@0x4009310d[libshield.so]0x9310d, arg=null, flags=[CLONE_VM, CLONE_FS, CLONE_FILES, CLONE_SIGHAND, CLONE_THREAD, CLONE_SYSVSEM]
JNIEnv->FindClass(android/app/ActivityThread) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->CallStaticObjectMethodV(class android/app/ActivityThread, currentApplication() => android.app.Application@a776e) was called from RX@0x40010025[libshield.so]0x10025
JNIEnv->FindClass(com/xingin/shield/http/XhsHttpInterceptor) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->RegisterNatives(com/xingin/shield/http/XhsHttpInterceptor, RW@0x400b4004[libshield.so]0xb4004, 4) was called from RX@0x40010211[libshield.so]0x10211
RegisterNative(com/xingin/shield/http/XhsHttpInterceptor, initializeNative()V, RX@0x40094289[libshield.so]0x94289)
RegisterNative(com/xingin/shield/http/XhsHttpInterceptor, intercept(Lokhttp3/Interceptor$Chain;J)Lokhttp3/Response;, RX@0x400939d9[libshield.so]0x939d9)
RegisterNative(com/xingin/shield/http/XhsHttpInterceptor, initialize(Ljava/lang/String;)J, RX@0x400937b1[libshield.so]0x937b1)
RegisterNative(com/xingin/shield/http/XhsHttpInterceptor, destroy(J)V, RX@0x40093745[libshield.so]0x93745)
JNIEnv->FindClass(android/content/Context) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(java/lang/String) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(android/content/SharedPreferences) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(android/content/SharedPreferences$Editor) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(android/content/pm/PackageManager) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(okhttp3/Request) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(okhttp3/HttpUrl) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(okhttp3/Request$Builder) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(okhttp3/RequestBody) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(okhttp3/Headers) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(okio/Buffer) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(okhttp3/Interceptor$Chain) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(java/util/List) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(java/nio/charset/Charset) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(com/xingin/shield/http/ContextHolder) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(okhttp3/Response) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(okhttp3/ResponseBody) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(com/xingin/shield/http/Base64Helper) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(android/app/Application) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->CallObjectMethodV(android.app.Application@a776e, getPackageManager() => android.content.pm.PackageManager@792bbc74) was called from RX@0x4000fab5[libshield.so]0xfab5
JNIEnv->FindClass(android/content/pm/PackageManager) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(android/app/Application) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->CallObjectMethodV(android.app.Application@a776e, getPackageName() => "com.xingin.xhs") was called from RX@0x4000fab5[libshield.so]0xfab5
JNIEnv->CallObjectMethodV(android.content.pm.PackageManager@792bbc74, getPackageInfo("com.xingin.xhs", 0x40) => android.content.pm.PackageInfo@33e01298) was called from RX@0x4000fab5[libshield.so]0xfab5
JNIEnv->FindClass(android/content/pm/PackageInfo) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->FindClass(android/content/pm/Signature) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->GetObjectField(android.content.pm.PackageInfo@33e01298, signatures [Landroid/content/pm/Signature; => [android.content.pm.Signature@2a3591c5]) was called from RX@0x4000fc0f[libshield.so]0xfc0f
JNIEnv->GetArrayLength([android.content.pm.Signature@2a3591c5] => 1) was called from RX@0x4000fc6b[libshield.so]0xfc6b
JNIEnv->GetObjectArrayElement([android.content.pm.Signature@2a3591c5], 0) was called from RX@0x4000fcc7[libshield.so]0xfcc7
JNIEnv->CallIntMethodV(android.content.pm.Signature@2a3591c5, hashCode() => 0xbf6f07ea) was called from RX@0x4000fd39[libshield.so]0xfd39
Find native function Java_com_xingin_shield_http_XhsHttpInterceptor_initializeNative()V => RX@0x40094289[libshield.so]0x94289
JNIEnv->CallStaticObjectMethodV(class java/nio/charset/Charset, defaultCharset() => java.nio.charset.Charset@346a361) was called from RX@0x40010025[libshield.so]0x10025
JNIEnv->CallObjectMethodV(android.app.Application@a776e, getPackageManager() => android.content.pm.PackageManager@107ed6fc) was called from RX@0x4000fab5[libshield.so]0xfab5
JNIEnv->CallObjectMethodV(android.app.Application@a776e, getPackageName() => "com.xingin.xhs") was called from RX@0x4000fab5[libshield.so]0xfab5
JNIEnv->CallObjectMethodV(android.content.pm.PackageManager@107ed6fc, getPackageInfo("com.xingin.xhs", 0x20000) => android.content.pm.PackageInfo@186978a6) was called from RX@0x4000fab5[libshield.so]0xfab5
JNIEnv->FindClass(android/content/pm/PackageInfo) was called from RX@0x4000ff41[libshield.so]0xff41
JNIEnv->GetIntField(android.content.pm.PackageInfo@186978a6, versionCode => 0x613334) was called from RX@0x40013cb7[libshield.so]0x13cb7
JNIEnv->GetStaticObjectField(class com/xingin/shield/http/ContextHolder, sDeviceId Ljava/lang/String; => "0666e38a-6c72-3dd9-8ec7-b30d87521f6c") was called from RX@0x40012537[libshield.so]0x12537
JNIEnv->GetStaticIntField(class com/xingin/shield/http/ContextHolder, sAppId => 0xecfaaf01) was called from RX@0x40012593[libshield.so]0x12593
May 18, 2021 9:26:52 PM com.github.unidbg.arm.AbstractARMEmulator hook
WARNING: memory failed: address=0x248, size=1, value=0x0, PC=unicorn@0x248, LR=RX@0x400125ef[libshield.so]0x125ef
May 18, 2021 9:26:52 PM com.github.unidbg.AbstractEmulator emulate
WARNING: emulate RX@0x40094289[libshield.so]0x94289 exception sp=unicorn@0xbffff418, msg=Invalid memory fetch (UC_ERR_FETCH_UNMAPPED), offset=33ms
Find native function Java_com_xingin_shield_http_XhsHttpInterceptor_initialize(Ljava/lang/String;)J => RX@0x400937b1[libshield.so]0x937b1
May 18, 2021 9:44:05 PM com.github.unidbg.linux.ARMSyscallHandler hook
WARNING: handleInterrupt intno=2, NR=-1073744168, svcNumber=0x13e, PC=unicorn@0xfffe0474, syscall=null
java.lang.NullPointerException
	at com.github.unidbg.linux.android.dvm.DalvikVM$63.handle(DalvikVM.java:1366)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:111)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:336)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:415)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:197)
	at com.github.unidbg.Module.emulateFunction(Module.java:153)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:58)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:35)
	at com.xhs.LibShieldTest.invokeTest(LibShieldTest.java:56)
	at com.xhs.LibShieldTest.main(LibShieldTest.java:120)

May 18, 2021 9:44:13 PM com.github.unidbg.AbstractEmulator emulate
WARNING: emulate RX@0x400937b1[libshield.so]0x937b1 exception sp=unicorn@0xbffff6a8, msg=null, offset=1037993ms
```

**Comment by zhkl0228** [comment]
发测试才能分析

**Comment by hu-jinwen** [comment]
> 发测试才能分析

这是我完整的测试代码，
里面用到的 so文件和apk在这：
链接: https://pan.baidu.com/s/1g1f929eaPU_nSMQaquNikA  密码: gsim
```java
package com.xhs;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Emulator;
import com.github.unidbg.Module;
import com.github.unidbg.file.FileResult;
import com.github.unidbg.file.IOResolver;
import com.github.unidbg.linux.android.AndroidARMEmulator;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.*;
import com.github.unidbg.memory.Memory;
import com.hujinwen.utils.FileUtils;

import java.io.File;
import java.nio.charset.Charset;

/**
 * Created by hu-jinwen on 2021/5/12
 */
public class LibShieldTest extends AbstractJni implements IOResolver {
    private final AndroidEmulator emulator;

    private final VM vm;

    private final Module module;

    private final DvmClass dvmClass;


    public LibShieldTest() {
        this.emulator = new AndroidARMEmulator("com.xingin.xhs");

        emulator.getSyscallHandler().addIOResolver(this);

        final Memory memory = emulator.getMemory();
        memory.setLibraryResolver(new AndroidResolver(19));

        this.vm = emulator.createDalvikVM(FileUtils.getResourceFile("xhs_6.70.0.a4851e2.apk"));
        this.vm.setVerbose(true);  // 打印详细的日志
        this.vm.setJni(this);

        final File resourceFile = FileUtils.getResourceFile("libshield.so");

        final DalvikModule dalvikModule = this.vm.loadLibrary(resourceFile, false);
        dalvikModule.callJNI_OnLoad(emulator);

        this.module = dalvikModule.getModule();

        dvmClass = this.vm.resolveClass("com/xingin/shield/http/XhsHttpInterceptor");
    }

    private void invokeTest() {
        try {
            dvmClass.callStaticJniMethod(this.emulator, "initializeNative()V");
            final DvmObject<?> dvmObject = dvmClass.newObject(null);
            final Number number = dvmObject.callJniMethod(this.emulator, "initialize(Ljava/lang/String;)J", "main");
            System.out.println();

            long address = number.intValue() & 0xffffffffL;
            final Object value = vm.getObject(address).getValue();
            System.out.println(value);
        } finally {
            if (emulator != null) {
                try {
                    emulator.close();
                } catch (Exception ignored) {
                }
            }
        }
    }

    @Override
    public DvmObject<?> callStaticObjectMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
        if ("java/nio/charset/Charset->defaultCharset()Ljava/nio/charset/Charset;".equals(signature)) {
            return this.vm.resolveClass("java/nio/charset/Charset").newObject(Charset.defaultCharset());
        }
        return super.callStaticObjectMethodV(vm, dvmClass, signature, vaList);
    }

    @Override
    public int getIntField(BaseVM vm, DvmObject<?> dvmObject, String signature) {
        if ("android/content/pm/PackageInfo->versionCode:I".equals(signature)) {
            return 6370100;
        }
        return super.getIntField(vm, dvmObject, signature);
    }

    @Override
    public DvmObject<?> getStaticObjectField(BaseVM vm, DvmClass dvmClass, String signature) {
        switch (signature) {
            case "com/xingin/shield/http/ContextHolder->sDeviceId:Ljava/lang/String;":
            case "com/xingin/shield/http/ContextHolder->deviceId:Ljava/lang/String;":
                return new StringObject(vm, "0666e38a-6c72-3dd9-8ec7-b30d87521f6c");
        }
        return super.getStaticObjectField(vm, dvmClass, signature);
    }

    @Override
    public int getStaticIntField(BaseVM vm, DvmClass dvmClass, String signature) {
        switch (signature) {
            case "com/xingin/shield/http/ContextHolder->sAppId:I":
                return -319115519;
        }
        return super.getStaticIntField(vm, dvmClass, signature);
    }

    @Override
    public FileResult resolve(Emulator emulator, String s, int i) {
        return null;
    }

    public static void main(String[] args) {
        final LibShieldTest testApp = new LibShieldTest();
        testApp.invokeTest();
    }
}

```

**Comment by hu-jinwen** [comment]
> > 发测试才能分析
> 
> 这是我完整的测试代码，
> 里面用到的 so文件和apk在这：
> 链接: https://pan.baidu.com/s/1g1f929eaPU_nSMQaquNikA 密码: gsim
> 
> ```java
> package com.xhs;
> 
> import com.github.unidbg.AndroidEmulator;
> import com.github.unidbg.Emulator;
> import com.github.unidbg.Module;
> import com.github.unidbg.file.FileResult;
> import com.github.unidbg.file.IOResolver;
> import com.github.unidbg.linux.android.AndroidARMEmulator;
> import com.github.unidbg.linux.android.AndroidResolver;
> import com.github.unidbg.linux.android.dvm.*;
> import com.github.unidbg.memory.Memory;
> import com.hujinwen.utils.FileUtils;
> 
> import java.io.File;
> import java.nio.charset.Charset;
> 
> /**
>  * Created by hu-jinwen on 2021/5/12
>  */
> public class LibShieldTest extends AbstractJni implements IOResolver {
>     private final AndroidEmulator emulator;
> 
>     private final VM vm;
> 
>     private final Module module;
> 
>     private final DvmClass dvmClass;
> 
> 
>     public LibShieldTest() {
>         this.emulator = new AndroidARMEmulator("com.xingin.xhs");
> 
>         emulator.getSyscallHandler().addIOResolver(this);
> 
>         final Memory memory = emulator.getMemory();
>         memory.setLibraryResolver(new AndroidResolver(19));
> 
>         this.vm = emulator.createDalvikVM(FileUtils.getResourceFile("xhs_6.70.0.a4851e2.apk"));
>         this.vm.setVerbose(true);  // 打印详细的日志
>         this.vm.setJni(this);
> 
>         final File resourceFile = FileUtils.getResourceFile("libshield.so");
> 
>         final DalvikModule dalvikModule = this.vm.loadLibrary(resourceFile, false);
>         dalvikModule.callJNI_OnLoad(emulator);
> 
>         this.module = dalvikModule.getModule();
> 
>         dvmClass = this.vm.resolveClass("com/xingin/shield/http/XhsHttpInterceptor");
>     }
> 
>     private void invokeTest() {
>         try {
>             dvmClass.callStaticJniMethod(this.emulator, "initializeNative()V");
>             final DvmObject<?> dvmObject = dvmClass.newObject(null);
>             final Number number = dvmObject.callJniMethod(this.emulator, "initialize(Ljava/lang/String;)J", "main");
>             System.out.println();
> 
>             long address = number.intValue() & 0xffffffffL;
>             final Object value = vm.getObject(address).getValue();
>             System.out.println(value);
>         } finally {
>             if (emulator != null) {
>                 try {
>                     emulator.close();
>                 } catch (Exception ignored) {
>                 }
>             }
>         }
>     }
> 
>     @Override
>     public DvmObject<?> callStaticObjectMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
>         if ("java/nio/charset/Charset->defaultCharset()Ljava/nio/charset/Charset;".equals(signature)) {
>             return this.vm.resolveClass("java/nio/charset/Charset").newObject(Charset.defaultCharset());
>         }
>         return super.callStaticObjectMethodV(vm, dvmClass, signature, vaList);
>     }
> 
>     @Override
>     public int getIntField(BaseVM vm, DvmObject<?> dvmObject, String signature) {
>         if ("android/content/pm/PackageInfo->versionCode:I".equals(signature)) {
>             return 6370100;
>         }
>         return super.getIntField(vm, dvmObject, signature);
>     }
> 
>     @Override
>     public DvmObject<?> getStaticObjectField(BaseVM vm, DvmClass dvmClass, String signature) {
>         switch (signature) {
>             case "com/xingin/shield/http/ContextHolder->sDeviceId:Ljava/lang/String;":
>             case "com/xingin/shield/http/ContextHolder->deviceId:Ljava/lang/String;":
>                 return new StringObject(vm, "0666e38a-6c72-3dd9-8ec7-b30d87521f6c");
>         }
>         return super.getStaticObjectField(vm, dvmClass, signature);
>     }
> 
>     @Override
>     public int getStaticIntField(BaseVM vm, DvmClass dvmClass, String signature) {
>         switch (signature) {
>             case "com/xingin/shield/http/ContextHolder->sAppId:I":
>                 return -319115519;
>         }
>         return super.getStaticIntField(vm, dvmClass, signature);
>     }
> 
>     @Override
>     public FileResult resolve(Emulator emulator, String s, int i) {
>         return null;
>     }
> 
>     public static void main(String[] args) {
>         final LibShieldTest testApp = new LibShieldTest();
>         testApp.invokeTest();
>     }
> }
> ```

大哥 我发现这个问题是因为用的maven repository上老版本jar包。用了最新代码后问题解决了，正在往下面继续测试。
有问题版本的依赖：
```xml
        <!-- https://mvnrepository.com/artifact/com.github.zhkl0228/unidbg -->
        <dependency>
            <groupId>com.github.zhkl0228</groupId>
            <artifactId>unidbg</artifactId>
            <version>0.3.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.github.zhkl0228/unidbg-android -->
        <dependency>
            <groupId>com.github.zhkl0228</groupId>
            <artifactId>unidbg-android</artifactId>
            <version>0.9.3</version>
        </dependency>
```
