### ISSUE TITLE
Unidbg 在 Linux64 上运行报错

### ISSUE THREAD

**Issue by dream-lmc** [zhkl0228/unidbg#322]
`Caused by: java.lang.UnsatisfiedLinkError: /var/test/lib/libunicorn_java.so: /var/test/lib/libunicorn_java.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_241]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934) ~[na:1.8.0_241]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850) ~[na:1.8.0_241]
        at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[na:1.8.0_241]
        at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_241]
        at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:136) ~[native-lib-loader-2.3.5.jar!/:2.3.5]
        ... 45 common frames omitted`
这个怎么解决啊

**Comment by dream-lmc** [comment]
解决了
