### ISSUE TITLE
so回调java异常

### ISSUE THREAD

**Issue by yunnigu** [zhkl0228/unidbg#333]
在调用一个so函数的过程中，该函数返回值类型为一个结构体，native中有对这个结构体类的回调，我已经将该类添加，FindClass没有问题了，目前报错如下：

> [16:37:44 109]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:467) - handleInterrupt intno=2, NR=-1073744008, svcNumber=0x12e, PC=unidbg@0xfffe0374, LR=RX@0x400172a9[libAPSE_1.5.9.so]0x172a9, syscall=null
> java.lang.NullPointerException
> 	at com.github.unidbg.linux.android.dvm.DalvikVM$47.handle(DalvikVM.java:1086)
> 	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:103)
> 	at com.github.unidbg.arm.backend.UnicornBackend$6.hook(UnicornBackend.java:299)
> 	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
> 	at unicorn.Unicorn.emu_start(Native Method)
> 	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:325)
> 	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
> 	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
> 	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:220)
> 	at com.github.unidbg.Module.emulateFunction(Module.java:158)
> 	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:133)
> 	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:289)
> 	at com.bytedance.frameworks.core.encrypt.Ali_SafeDecrypt.SafeDecrypt(Ali_SafeDecrypt.java:82)
> 	at com.bytedance.frameworks.core.encrypt.Ali_SafeDecrypt.main(Ali_SafeDecrypt.java:72)
> [16:37:44 113]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:389) - emulate RX@0x400170f9[libAPSE_1.5.9.so]0x170f9 exception sp=unidbg@0xbffff728, msg=null, offset=132ms

![image](https://user-images.githubusercontent.com/20830226/125919418-e2ba7408-7d68-4695-938c-64a6f518f4d3.png)

请问这样的情况我还该怎么处理，vm.setDvmClassFactory(new ProxyClassFactory());已添加，回调的类如下：

> public class SecStoreResult extends Object	// class@000c2c
> {
>     public int errCode;
>     public String value;
> 
>     public void SecStoreResult(){
>         new Object();
>         this.value = null;
>         this.errCode = 0;
>     }
> }

**Comment by yunnigu** [comment]
链接: https://pan.baidu.com/s/14EUi24JOOjopZFCHx3JmoA 提取码: by44

**Comment by yunnigu** [comment]
链接: https://pan.baidu.com/s/1xER8qEOBeKxkIzAlpynzBg 提取码: chr7 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Pr0214** [comment]
你好，这里是MethodID不匹配带来的问题。

**Comment by yunnigu** [comment]
> 你好，这里是MethodID不匹配带来的问题。

那这里有什么办法可以解决呢？

**Comment by Pr0214** [comment]
用你的代码没能复现你的问题
