### ISSUE TITLE
有人遇到过这个问题嘛？ com.github.unidbg.linux.file.PipedWriteFileIO

### ISSUE THREAD

**Issue by fanaohe** [zhkl0228/unidbg#342]
java.lang.AbstractMethodError: com.github.unidbg.linux.file.PipedWriteFileIO
	at com.github.unidbg.file.AbstractFileIO.dup2(AbstractFileIO.java:160)
	at com.github.unidbg.linux.ARM32SyscallHandler.dup3(ARM32SyscallHandler.java:2103)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:437)
	at com.github.unidbg.arm.backend.UnicornBackend$6.hook(UnicornBackend.java:299)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:325)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:220)
	at com.github.unidbg.Module.emulateFunction(Module.java:158)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:232)
	at com.tujia.hotel.Appfp.ep(Appfp.java:67)
	at com.tujia.hotel.Appfp.main(Appfp.java:73)
各位大佬，我在使用unidbg调试某APP时遇到了这个问题，我看报错感觉应该是so文件在某个地方进行了文件io的操作，那么我想问一下，如果遇到这种勤快怎么处理，如何补充该环境呢

**Comment by Pr0214** [comment]
你好，这个报错较大可能性是样本在通过popen或者execve执行命令，您可以在合适位置通过如下代码Hook确认。

        int popenAddress = (int) moduleLibc.findSymbolByName("popen").getAddress();
        emulator.attach().addBreakPoint(popenAddress, new BreakPointCallback() {
            @Override
            public boolean onHit(Emulator<?> emulator, long address) {
                RegisterContext registerContext = emulator.getContext();
                String cmdline = registerContext.getPointerArg(0).getString(0);
                System.out.println("fuck popen cmdline:"+cmdline);
                return false;
            }
        });

**Comment by dktobeno1** [comment]
请问执行popen该怎么补呢？

**Comment by AlexLiuSheng** [comment]
1

**Comment by kevinsir** [comment]
请问这个要怎么补呢。。。确认了

**Comment by kevinsir** [comment]
发现在执行cat 命令
