### ISSUE TITLE
尝试模拟运行 xigncode 时，NullPointerException

### ISSUE THREAD

**Issue by WanghongLin** [zhkl0228/unidbg#345]
尝试运行 Android arm64 版本的 `libxigncode.so` 时，碰到了系统调用的错误。查了以下，系统调用 `0x111` 对应的是 `finit_module` 这个调用，这个问题应该如何处理？

```
[09:19:23 785]  WARN [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:305) - handleInterrupt intno=2, NR=-130656, svcNumber=0x111, PC=unidbg@0xfffe01a4[libandroid.so]0x1a4, LR=RX@0x4004cbd4[libxigncode.so]0x4cbd4, syscall=null
java.lang.NullPointerException
	at com.github.unidbg.linux.android.dvm.DalvikVM64$18.handle(DalvikVM64.java:335)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:90)
	at com.github.unidbg.arm.backend.UnicornBackend$6.hook(UnicornBackend.java:299)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:325)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:220)
	at com.github.unidbg.Module.emulateFunction(Module.java:158)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:133)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodInt(DvmClass.java:274)
```

**Comment by Pr0214** [comment]
你好，样本可以发一下吗
