### ISSUE TITLE
JNI_Onload执行失败，并返回多处错误

### ISSUE THREAD

**Issue by Andyworker** [zhkl0228/unidbg#348]
# JNI_Onload执行失败，并返回多处错误

**对某SO运行模拟时出错, 原因不明还望作者大大能给予一定的指导**

**运行错误日志日志如下：**

```JAVA
JNIEnv->FindClass(android/app/ActivityThread) was called from RX@0x404857f0[libwhitebox.so]0xd87f0
JNIEnv->GetStaticMethodID(android/app/ActivityThread.currentActivityThread()Landroid/app/ActivityThread;) => 0xf7e11563 was called from RX@0x40488180[libwhitebox.so]0xdb180
[11:03:00 956]  WARN [com.github.unidbg.linux.android.dvm.jni.ProxyJni] (ProxyJni:221) - callStaticObjectMethodV
java.lang.ClassNotFoundException: android.app.ActivityThread
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.github.unidbg.linux.android.dvm.jni.ProxyClassLoader.loadClass(ProxyClassLoader.java:22)
	at com.github.unidbg.linux.android.dvm.jni.ProxyJni.callStaticObjectMethodV(ProxyJni.java:216)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callStaticObjectMethodV(DvmMethod.java:64)
	at com.github.unidbg.linux.android.dvm.DalvikVM$113.handle(DalvikVM.java:1771)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:103)
	at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
	at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend32.callSVC(DynarmicBackend32.java:32)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:61)
	at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:76)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:220)
	at com.github.unidbg.Module.emulateFunction(Module.java:158)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:232)
	at com.github.unidbg.linux.LinuxSymbol.call(LinuxSymbol.java:27)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:33)
	at com.wuba.xxzl.wb.WBCrypto.<init>(WBCrypto.java:42)
	at com.wuba.xxzl.wb.WBCrypto.main(WBCrypto.java:51)
[11:03:00 959]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:467) - handleInterrupt intno=2, NR=-502709370, svcNumber=0x170, PC=unidbg@0xfffe0794, LR=RX@0x4046faec[libwhitebox.so]0xc2aec, syscall=null
java.lang.UnsupportedOperationException: android/app/ActivityThread->currentActivityThread()Landroid/app/ActivityThread;
	at com.github.unidbg.linux.android.dvm.JniFunction.callStaticObjectMethodV(JniFunction.java:117)
	at com.github.unidbg.linux.android.dvm.jni.ProxyJni.callStaticObjectMethodV(ProxyJni.java:223)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callStaticObjectMethodV(DvmMethod.java:64)
	at com.github.unidbg.linux.android.dvm.DalvikVM$113.handle(DalvikVM.java:1771)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:103)
	at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
	at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend32.callSVC(DynarmicBackend32.java:32)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:61)
	at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:76)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:220)
	at com.github.unidbg.Module.emulateFunction(Module.java:158)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:232)
	at com.github.unidbg.linux.LinuxSymbol.call(LinuxSymbol.java:27)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:33)
	at com.wuba.xxzl.wb.WBCrypto.<init>(WBCrypto.java:42)
	at com.wuba.xxzl.wb.WBCrypto.main(WBCrypto.java:51)
[11:03:00 960]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:389) - emulate RX@0x40472694[libwhitebox.so]0xc5694 exception sp=unidbg@0xbffff660, msg=android/app/ActivityThread->currentActivityThread()Landroid/app/ActivityThread;, offset=26ms
Exception in thread "main" java.lang.IllegalStateException: Illegal JNI version: 0xffffffff
	at com.github.unidbg.linux.android.dvm.BaseVM.checkVersion(BaseVM.java:194)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:39)
	at com.wuba.xxzl.wb.WBCrypto.<init>(WBCrypto.java:42)
	at com.wuba.xxzl.wb.WBCrypto.main(WBCrypto.java:51)

Process finished with exit code 1
```

---

**代码如下：**

```java
import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.LibraryResolver;
import com.github.unidbg.arm.backend.DynarmicFactory;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.jni.ProxyClassFactory;
import com.github.unidbg.memory.Memory;

import java.io.File;
import java.io.IOException;

public class WBCrypto {

    private final AndroidEmulator emulator;

    public WBCrypto() {
        emulator = AndroidEmulatorBuilder
                .for32Bit().addBackendFactory(new DynarmicFactory(true))
                .build();
        Memory memory = emulator.getMemory();
        LibraryResolver resolver = new AndroidResolver(23);
        memory.setLibraryResolver(resolver);

        VM vm = emulator.createDalvikVM();
        vm.setDvmClassFactory(new ProxyClassFactory());
        vm.setVerbose(true);

        vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libc++_shared.so"), false);
        vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libxxzlproto.so"), false);
        vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libxxzlutd.so"), false);
        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libwhitebox.so"), false);
        int pid = emulator.getPid();
        System.out.println("===== current pid:" + pid + "==========");

//        DvmClass cSignUtil = vm.resolveClass("com/wuba/xxzl/wb/WBKey");

        dm.callJNI_OnLoad(emulator);

    }

    public void destroy() throws IOException {
        emulator.close();
    }

    public static void main(String[] args) throws Exception {
        WBCrypto wbCrypto = new WBCrypto();
        wbCrypto.destroy();
    }
}
```

---

APP样本下载链接：
[app-package.zip](https://github.com/zhkl0228/unidbg/files/7071853/app-package.zip)

**Comment by rozbo** [comment]
这些环境需要自己完善

**Comment by Andyworker** [comment]
具体缺什么环节呢？能否明确说一下嘛？

**Comment by Andyworker** [comment]
> 这些环境需要自己完善

通过一天的努力我已经解决了一部分环境问题了，但是有一个不知道怎么解决

```java
java.lang.UnsupportedOperationException: java/util/UUID-><init>(JJ)V
```
这个该怎么解决呢

**Comment by praiseqin** [comment]
> > 这些环境需要自己完善
> 
> 通过一天的努力我已经解决了一部分环境问题了，但是有一个不知道怎么解决
> 
> ```java
> java.lang.UnsupportedOperationException: java/util/UUID-><init>(JJ)V
> ```
> 
> 这个该怎么解决呢

            case "java/util/UUID-><init>(JJ)V": {
                return vm.resolveClass("java/lang/Long").newObject(vaList);
            }

**Comment by Andyworker** [comment]
> > 这些环境需要自己完善
> 
> 通过一天的努力我已经解决了一部分环境问题了，但是有一个不知道怎么解决
> 
> ```java
> java.lang.UnsupportedOperationException: java/util/UUID-><init>(JJ)V
> ```
> 
> 这个该怎么解决呢

这个已经解决了，使用`vm.resolveClass("java/util/UUID").newObject(signtrue)；`

---

估计没人会回复了，我自己记录一下吧，补环境过程中又遇到了新问题：

```java
unicorn.UnicornException: Invalid memory write (UC_ERR_WRITE_UNMAPPED)
```

**Comment by Andyworker** [comment]
上一个问题是由于`"android/media/MediaDrm->getPropertyByteArray(Ljava/lang/String;)[B"`, 我返回的值为**dvmObject**，根据查资料，JVM签名类型如下：

|JVAM签名| 签名类型|
|:-------:|:----------:|
|B | byte| 
|C | char|
|D | double| 
|F | float|
|I | int|
|J | long|
|S | short|
|V | void|
|Z | boolean|
|[ | array of the thing following the bracket|
|L [class name] ; | instance of this class, with dots becoming slashes|
|( [args] ) [return type] |method signature|

---
返回值为：`[B`, 也就是ByteArray类型，dvmObject是无法转化为byteArray类型，所以会报错，写模拟的时候需要对最后的返回值进行仔细检查，否则就会出错。

报错原因是返回
`vm.resolveClass("")`

---

继续记录错误：

```
[16:27:22 683]  WARN [com.github.unidbg.arm.AbstractARMEmulator] (AbstractARMEmulator$1:58) - memory failed: address=0x0, size=4, value=0x0, PC=RX@0x400a2c90[libc.so]0x18c90, LR=RX@0x40499ce8[libwhitebox.so]0xecce8
[16:27:22 687]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:389) - emulate RX@0x40472694[libwhitebox.so]0xc5694 exception sp=unidbg@0xbffff4f8, msg=unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED), offset=95ms
Exception in thread "main" java.lang.IllegalStateException: Illegal JNI version: 0xffffffff
	at com.github.unidbg.linux.android.dvm.BaseVM.checkVersion(BaseVM.java:194)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:39)
	at com.wuba.xxzl.WBCrypto.<init>(WBCrypto.java:99)
	at com.wuba.xxzl.WBCrypto.main(WBCrypto.java:163)
```
