### ISSUE TITLE
关于 cn.banny.unidbg.file.AbstractFileIO.ioctl(AbstractFileIO.java:66) 的异常

### ISSUE THREAD

**Issue by JiangJianCong** [zhkl0228/unidbg#35]
作者你好，在调试的时候遇到一个异常

```
  >>> r0=0x4 r1=0x8912 r2=0xbfffea84, r3=0xd358ee20 r4=0xd358ee20 r5=0xa994c780 r6=0xbfffea88 r7=0x36 r9=0xe896a2b1 r10=0x5970fe23 fp=0x427a336e ip=0xbfffea18 sp=0xbfffea08 lr=0x400245c1 pc=0x4002a65c cpsr: N=0, Z=1, C=1, V=0, T=0, mode=0b10000
[14:04:04 455] DEBUG [cn.banny.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1646) - ioctl fd=4, request=0x8912, argp=0xbfffea84
[14:05:01 084]  WARN [cn.banny.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:377) - handleInterrupt intno=2, NR=54, svcNumber=0x0, PC=unicorn@0x4002a65c[libcms.so]0x2a65c, syscall=null
java.lang.AbstractMethodError: cn.banny.unidbg.unix.file.UdpSocket: request=0x8912, argp=0xbfffea84
	at cn.banny.unidbg.file.AbstractFileIO.ioctl(AbstractFileIO.java:66)
	at cn.banny.unidbg.linux.ARMSyscallHandler.ioctl(ARMSyscallHandler.java:1658)
	at cn.banny.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:162)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:140)

```

我debug看的时候发现fd=4的时候，fdMap->""， 然后调用 file.ioctl(emulator, request, argp);就出现异常了，
![image](https://user-images.githubusercontent.com/24204467/61513220-01afe400-aa2f-11e9-8a2d-abcb80cee6ce.png)
具体异常信息：
![image](https://user-images.githubusercontent.com/24204467/61513322-53586e80-aa2f-11e9-9450-7b67921d96ea.png)

**Comment by zhkl0228** [comment]
在 UdpSocket里面覆盖ioctl方法，直接返回0

**Comment by zhkl0228** [comment]
方便的话把测试用例发上来跑一下

**Comment by JiangJianCong** [comment]
> 方便的话把测试用例发上来跑一下

apk有点大发不上来，发了测试用例
[test.zip](https://github.com/zhkl0228/unidbg/files/3411344/test.zip)

**Comment by JiangJianCong** [comment]
> 方便的话把测试用例发上来跑一下

apk是dy660的apk

**Comment by zhkl0228** [comment]
看了下资料，发现是ioctl要模拟实现SIOCGIFCONF操作，具体百度

**Comment by JiangJianCong** [comment]
> 看了下资料，发现是ioctl要模拟实现SIOCGIFCONF操作，具体百度

哦哦。好的具体可以再UdpSocket里面实现是吧？谢谢啦
