### ISSUE TITLE
求助unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED), offset=73ms

### ISSUE THREAD

**Issue by Andyworker** [zhkl0228/unidbg#357]
很多天了依然没有解决，特此来求助，错误访问日志如下：

```
Open Path with /dev/__properties__
Open Path with /proc/stat
JNIEnv->FindClass(android/app/ActivityThread) was called from RX@0x40384a35[libxxzlutd.so]0xea35
JNIEnv->GetStaticMethodID(android/app/ActivityThread.currentActivityThread()Landroid/app/ActivityThread;) => 0xf7e11563 was called from RX@0x40386675[libxxzlutd.so]0x10675
JNIEnv->CallStaticObjectMethodV(class android/app/ActivityThread, currentActivityThread() => Landroid.app.ActivityThread@38e79ae3) was called from RX@0x403869cd[libxxzlutd.so]0x109cd
JNIEnv->NewGlobalRef(Landroid.app.ActivityThread@38e79ae3) was called from RX@0x4038554f[libxxzlutd.so]0xf54f
JNIEnv->GetMethodID(Landroid/app/ActivityThread.getApplication()Landroid/app/Application;) => 0xf5a74ac6 was called from RX@0x403864ad[libxxzlutd.so]0x104ad
JNIEnv->CallObjectMethodV(Landroid.app.ActivityThread@38e79ae3, getApplication() => android.app.Application@15ca7889) was called from RX@0x40379aad[libxxzlutd.so]0x3aad
JNIEnv->NewGlobalRef(android.app.Application@15ca7889) was called from RX@0x4038554f[libxxzlutd.so]0xf54f
JNIEnv->GetMethodID(android/app/Application.getClassLoader()Ljava/lang/ClassLoader;) => 0xbe9a307 was called from RX@0x403853b5[libxxzlutd.so]0xf3b5
JNIEnv->CallObjectMethodV(android.app.Application@15ca7889, getClassLoader() => dalvik.system.PathClassLoader@d21a74c) was called from RX@0x40379aad[libxxzlutd.so]0x3aad
JNIEnv->NewGlobalRef(dalvik.system.PathClassLoader@d21a74c) was called from RX@0x4038554f[libxxzlutd.so]0xf54f
JNIEnv->FindClass(java/lang/ClassLoader) was called from RX@0x40384a35[libxxzlutd.so]0xea35
JNIEnv->GetMethodID(java/lang/ClassLoader.findClass(Ljava/lang/String;)Ljava/lang/Class;) => 0xb1fafbf5 was called from RX@0x403855af[libxxzlutd.so]0xf5af
JNIEnv->FindClass(com/wuba/xxzl/utdid/UUID) was called from RX@0x40384a35[libxxzlutd.so]0xea35
JNIEnv->GetStaticMethodID(com/wuba/xxzl/utdid/UUID.native_setup(Lcom/wuba/xxzl/utdid/UUID;)V) => 0x17b59118 was called from RX@0x4039579f[libxxzlutd.so]0x1f79f
JNIEnv->FindClass(com/wuba/xxzl/utdid/UUID) was called from RX@0x40384a35[libxxzlutd.so]0xea35
JNIEnv->RegisterNatives(com/wuba/xxzl/utdid/UUID, unidbg@0xbffff6d8, 1) was called from RX@0x40383227[libxxzlutd.so]0xd227
RegisterNative(com/wuba/xxzl/utdid/UUID, native_setup(Lcom/wuba/xxzl/utdid/UUID;)V, RX@0x403956ed[libxxzlutd.so]0x1f6ed)
JNIEnv->FindClass(android/app/ActivityThread) was called from RX@0x404857f0[libwhitebox.so]0xd87f0
JNIEnv->GetStaticMethodID(android/app/ActivityThread.currentActivityThread()Landroid/app/ActivityThread;) => 0xf7e11563 was called from RX@0x40488180[libwhitebox.so]0xdb180
JNIEnv->CallStaticObjectMethodV(class android/app/ActivityThread, currentActivityThread() => Landroid.app.ActivityThread@6e509ffa) was called from RX@0x4046faec[libwhitebox.so]0xc2aec
JNIEnv->NewGlobalRef(Landroid.app.ActivityThread@6e509ffa) was called from RX@0x40486860[libwhitebox.so]0xd9860
JNIEnv->GetMethodID(Landroid/app/ActivityThread.getApplication()Landroid/app/Application;) => 0xf5a74ac6 was called from RX@0x40487edc[libwhitebox.so]0xdaedc
JNIEnv->CallObjectMethodV(Landroid.app.ActivityThread@6e509ffa, getApplication() => android.app.Application@2898ac89) was called from RX@0x4046de60[libwhitebox.so]0xc0e60
JNIEnv->NewGlobalRef(android.app.Application@2898ac89) was called from RX@0x40486860[libwhitebox.so]0xd9860
JNIEnv->GetMethodID(android/app/Application.getClassLoader()Ljava/lang/ClassLoader;) => 0xbe9a307 was called from RX@0x404865dc[libwhitebox.so]0xd95dc
JNIEnv->CallObjectMethodV(android.app.Application@2898ac89, getClassLoader() => dalvik.system.PathClassLoader@683dbc2c) was called from RX@0x4046de60[libwhitebox.so]0xc0e60
JNIEnv->NewGlobalRef(dalvik.system.PathClassLoader@683dbc2c) was called from RX@0x40486860[libwhitebox.so]0xd9860
JNIEnv->FindClass(java/lang/ClassLoader) was called from RX@0x404857f0[libwhitebox.so]0xd87f0
JNIEnv->GetMethodID(java/lang/ClassLoader.findClass(Ljava/lang/String;)Ljava/lang/Class;) => 0xb1fafbf5 was called from RX@0x404868e8[libwhitebox.so]0xd98e8
JNIEnv->FindClass(com/wuba/xxzl/wb/WBKey) was called from RX@0x404857f0[libwhitebox.so]0xd87f0
JNIEnv->GetStaticMethodID(com/wuba/xxzl/wb/WBKey.native_setup(Lcom/wuba/xxzl/wb/WBKey;)V) => 0xd915ad8c was called from RX@0x404740cc[libwhitebox.so]0xc70cc
JNIEnv->FindClass(com/wuba/xxzl/wb/WBKey) was called from RX@0x404857f0[libwhitebox.so]0xd87f0
JNIEnv->RegisterNatives(com/wuba/xxzl/wb/WBKey, unidbg@0xbffff6a0, 1) was called from RX@0x40482794[libwhitebox.so]0xd5794
RegisterNative(com/wuba/xxzl/wb/WBKey, native_setup(Lcom/wuba/xxzl/wb/WBKey;)V, RX@0x40473bf8[libwhitebox.so]0xc6bf8)
JNIEnv->FindClass(com/wuba/xxzl/wb/WBKey) was called from RX@0x404857f0[libwhitebox.so]0xd87f0
JNIEnv->GetStaticMethodID(com/wuba/xxzl/wb/WBKey.native_finalize(Lcom/wuba/xxzl/wb/WBKey;)V) => 0x3cb756f was called from RX@0x404740cc[libwhitebox.so]0xc70cc
JNIEnv->FindClass(com/wuba/xxzl/wb/WBKey) was called from RX@0x404857f0[libwhitebox.so]0xd87f0
JNIEnv->RegisterNatives(com/wuba/xxzl/wb/WBKey, unidbg@0xbffff6a0, 1) was called from RX@0x40482794[libwhitebox.so]0xd5794
RegisterNative(com/wuba/xxzl/wb/WBKey, native_finalize(Lcom/wuba/xxzl/wb/WBKey;)V, RX@0x40473ed4[libwhitebox.so]0xc6ed4)
JNIEnv->FindClass(com/wuba/xxzl/wb/WBCrypto) was called from RX@0x404857f0[libwhitebox.so]0xd87f0
JNIEnv->RegisterNatives(com/wuba/xxzl/wb/WBCrypto, unidbg@0xbffff6e8, 1) was called from RX@0x40482794[libwhitebox.so]0xd5794
RegisterNative(com/wuba/xxzl/wb/WBCrypto, encrypt(ILcom/wuba/xxzl/wb/WBKey;[BLjava/lang/String;)[B, RX@0x40468d5c[libwhitebox.so]0xbbd5c)
JNIEnv->FindClass(com/wuba/xxzl/wb/WBCrypto) was called from RX@0x404857f0[libwhitebox.so]0xd87f0
JNIEnv->RegisterNatives(com/wuba/xxzl/wb/WBCrypto, unidbg@0xbffff6e8, 1) was called from RX@0x40482794[libwhitebox.so]0xd5794
RegisterNative(com/wuba/xxzl/wb/WBCrypto, decrypt(ILcom/wuba/xxzl/wb/WBKey;[BLjava/lang/String;)[B, RX@0x40468db8[libwhitebox.so]0xbbdb8)
JNIEnv->FindClass(com/wuba/xxzl/wb/Encrypt) was called from RX@0x404857f0[libwhitebox.so]0xd87f0
JNIEnv->RegisterNatives(com/wuba/xxzl/wb/Encrypt, unidbg@0xbffff6e8, 1) was called from RX@0x40482794[libwhitebox.so]0xd5794
RegisterNative(com/wuba/xxzl/wb/Encrypt, native_loop()V, RX@0x40468384[libwhitebox.so]0xbb384)
JNIEnv->FindClass(android/media/MediaDrm) was called from RX@0x40384a35[libxxzlutd.so]0xea35
JNIEnv->GetStaticMethodID(android/media/MediaDrm.isCryptoSchemeSupported(Ljava/util/UUID;)Z) => 0x70389726 was called from RX@0x403939c5[libxxzlutd.so]0x1d9c5
JNIEnv->FindClass(java/util/UUID) was called from RX@0x40384a35[libxxzlutd.so]0xea35
JNIEnv->GetMethodID(java/util/UUID.<init>(JJ)V) => 0x68a7f717 was called from RX@0x40393dab[libxxzlutd.so]0x1ddab
JNIEnv->NewObjectV(class java/util/UUID, <init>(0xedef8ba979d64aceL, 0xa3c827dcd51d21edL) => java.util.UUID-><init>@2638011) was called from RX@0x4038111d[libxxzlutd.so]0xb11d
JNIEnv->CallStaticBooleanMethodV(class android/media/MediaDrm, isCryptoSchemeSupported(java.util.UUID-><init>@2638011) => true) was called from RX@0x4039422d[libxxzlutd.so]0x1e22d
JNIEnv->FindClass(android/media/MediaDrm) was called from RX@0x40384a35[libxxzlutd.so]0xea35
JNIEnv->GetMethodID(android/media/MediaDrm.<init>(Ljava/util/UUID;)V) => 0x70ee91a0 was called from RX@0x403942b1[libxxzlutd.so]0x1e2b1
JNIEnv->NewObjectV(class android/media/MediaDrm, <init>(java.util.UUID-><init>@2638011) => android.media.MediaDrm@6ff29830) was called from RX@0x4038111d[libxxzlutd.so]0xb11d
JNIEnv->NewGlobalRef(android.media.MediaDrm@6ff29830) was called from RX@0x40378929[libxxzlutd.so]0x2929
JNIEnv->NewStringUTF("deviceUniqueId") was called from RX@0x40379be1[libxxzlutd.so]0x3be1
JNIEnv->GetMethodID(android/media/MediaDrm.getPropertyByteArray(Ljava/lang/String;)[B) => 0x41bb2d7b was called from RX@0x40394a53[libxxzlutd.so]0x1ea53
JNIEnv->CallObjectMethodV(android.media.MediaDrm@6ff29830, getPropertyByteArray("deviceUniqueId") => [B@175b9425) was called from RX@0x40379aad[libxxzlutd.so]0x3aad
JNIEnv->GetArrayLength([B@175b9425 => 14) was called from RX@0x403937cf[libxxzlutd.so]0x1d7cf
JNIEnv->GetArrayLength([B@175b9425 => 14) was called from RX@0x4037a03f[libxxzlutd.so]0x403f
JNIEnv->DeleteGlobalRef(android.media.MediaDrm@6ff29830) was called from RX@0x40378971[libxxzlutd.so]0x2971
Open Path with /proc/self/cmdline
Open Path with /proc/self/maps
[18:59:29 200]  WARN [com.github.unidbg.arm.AbstractARMEmulator] (AbstractARMEmulator$1:58) - memory failed: address=0x0, size=4, value=0x0, PC=RX@0x400a2c90[libc.so]0x18c90, LR=RX@0x40499ce8[libwhitebox.so]0xecce8
[18:59:29 204]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:389) - emulate RX@0x40472694[libwhitebox.so]0xc5694 exception sp=unidbg@0xbffff4f8, msg=unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED), offset=73ms
Exception in thread "main" java.lang.IllegalStateException: Illegal JNI version: 0xffffffff
	at com.github.unidbg.linux.android.dvm.BaseVM.checkVersion(BaseVM.java:194)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:39)
	at com.wuba.xxzl.WBCrypto.<init>(WBCrypto.java:98)
	at com.wuba.xxzl.WBCrypto.main(WBCrypto.java:162)
```

**Comment by Andyworker** [comment]
代码如下：

```
package com.wuba.xxzl;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.Emulator;
import com.github.unidbg.arm.ArmSvc;
import com.github.unidbg.file.FileResult;
import com.github.unidbg.file.IOResolver;
import com.github.unidbg.file.linux.AndroidFileIO;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.*;
import com.github.unidbg.linux.android.dvm.api.ClassLoader;
import com.github.unidbg.linux.android.dvm.array.ByteArray;
import com.github.unidbg.linux.file.ByteArrayFileIO;
import com.github.unidbg.memory.Memory;
import com.github.unidbg.memory.SvcMemory;
import com.github.unidbg.pointer.UnidbgPointer;
import com.github.unidbg.virtualmodule.VirtualModule;
import com.github.unidbg.virtualmodule.android.AndroidModule;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Map;


public class WBCrypto extends AbstractJni implements IOResolver<AndroidFileIO> {
    private final AndroidEmulator emulator;
    private final DvmClass cNative;
    private VM vm;

    @Override
    public FileResult<AndroidFileIO> resolve(Emulator<AndroidFileIO> emulator, String pathname, int oflags) {
        System.out.println("Open Path with " + pathname);
        if (pathname.equals("/proc/self/cmdline")) {
            return FileResult.success(new ByteArrayFileIO(oflags, pathname, "com.anjuke.android.app".getBytes()));
        }
        return null;
    }

    private static class UserEnvModule extends VirtualModule<Object> {

        protected UserEnvModule(Emulator<?> emulator) {
            super(emulator, null, "libUserEnv.so");
        }

        @Override
        protected void onInitialize(Emulator<?> emulator, Object extra, Map<String, UnidbgPointer> symbols) {
            SvcMemory svcMemory = emulator.getSvcMemory();
            symbols.put("GetUserEnvStr", svcMemory.registerSvc(new ArmSvc() {
                @Override
                public long handle(Emulator<?> emulator) {
                    throw new UnsupportedOperationException();
                }
            }));
            symbols.put("FreeUserEnvStr", svcMemory.registerSvc(new ArmSvc() {
                @Override
                public long handle(Emulator<?> emulator) {
                    throw new UnsupportedOperationException();
                }
            }));
            symbols.put("InitUserEnv", svcMemory.registerSvc(new ArmSvc() {
                @Override
                public long handle(Emulator<?> emulator) {
                    throw new UnsupportedOperationException();
                }
            }));
        }
    }


    public WBCrypto() {
        emulator = AndroidEmulatorBuilder.for32Bit()
                .setProcessName("com.anjuke.android.app")
                .build();

        Memory memory = emulator.getMemory();
        memory.setLibraryResolver(new AndroidResolver(23));
        new UserEnvModule(emulator).register(memory);
        new AndroidModule(emulator, vm).register(memory);
        emulator.getSyscallHandler().addIOResolver(this);
        VM vm = emulator.createDalvikVM(new File("unidbg-android/src/test/resources/app-debug.apk"));
        vm.setJni(this);

        cNative = vm.resolveClass("com/wuba/xxzl/wb/WBKey");

//        vm.setDvmClassFactory(new ProxyClassFactory());

        vm.setVerbose(true);
        vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libc++_shared.so"), false);
        vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libxxzlproto.so"), false);
        DalvikModule libUid = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libxxzlutd.so"), false);
        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libwhitebox.so"), true);


        libUid.callJNI_OnLoad(emulator);
//        emulator.traceCode(dm.getModule().base, dm.getModule().base + dm.getModule().size);
        dm.callJNI_OnLoad(emulator);
    }

    @Override
    public DvmObject<?> newObjectV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {

        switch (signature) {
            case "java/util/UUID-><init>(JJ)V":
                return vm.resolveClass("java/util/UUID-><init>").newObject(null);

            case "android/media/MediaDrm-><init>(Ljava/util/UUID;)V":
                return vm.resolveClass("android/media/MediaDrm").newObject(signature);
        }
        return super.newObjectV(vm, dvmClass, signature, vaList);
    }

    @Override
    public boolean callStaticBooleanMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
        if ("android/media/MediaDrm->isCryptoSchemeSupported(Ljava/util/UUID;)Z".equals(signature)) {
            return true;
        }
        return super.callStaticBooleanMethodV(vm, dvmClass, signature, vaList);
    }


    @Override
    public DvmObject<?> callObjectMethodV(BaseVM vm, DvmObject<?> dvmObject, String signature, VaList vaList) {
        switch (signature) {

            case "Landroid/app/ActivityThread->getApplication()Landroid/app/Application;":
                return vm.resolveClass("android/app/Application").newObject(signature);
            case "android/app/ActivityThread->getApplication->getClassLoader()Ljava/lang/ClassLoader;":
                return new ClassLoader(vm, signature);

            case "android/app/ActivityThread->getApplication()Landroid/app/Application;":
                return vm.resolveClass("android/app/ActivityThread", vm.resolveClass("Landroid/app/Application;")).newObject(signature);

            case "android/media/MediaDrm->getPropertyByteArray(Ljava/lang/String;)[B":
                StringObject va = vaList.getObjectArg(0);
                return new ByteArray(vm, va.getValue().getBytes());

            case "android/app/ActivityThread->getClassLoader()Ljava/lang/ClassLoader;":
                return vm.resolveClass("android/app/ActivityThread",
                        vm.resolveClass("java/lang/ClassLoader")).newObject(dvmObject);

            case "android/app/ActivityThread.currentActivityThread()Landroid/app/ActivityThread;":
                return vm.resolveClass("android/app/ActivityThread.currentActivityThread",
                        vm.resolveClass("android/app/ActivityThread")).newObject(signature);
        }

        return super.callObjectMethodV(vm, dvmObject, signature, vaList);
    }

    public void destroy() throws IOException {
        emulator.close();
    }

    public void getId() {
        String method = "getId()Ljava/lang/String;";
        StringObject obj = cNative.callJniMethodObject(emulator, method);
        System.out.println("Get token with " + obj.getValue());
    }

    public static void main(String[] args) throws Exception {
        WBCrypto key = new WBCrypto();
        key.getId();
        key.destroy();
    }
}
```

---
涉及SO如下：

[libwhitebox.so.zip](https://github.com/zhkl0228/unidbg/files/7143358/libwhitebox.so.zip)

**Comment by Pr0214** [comment]
你好，我怀疑这里是因为你没有补maps，于是样本使用Unidbg自带的maps而造成的相关问题

**Comment by Andyworker** [comment]
> maps

十分感谢回复，maps该怎么补呢?目前我是用测试用例中的例子，然后依然没有效果

```java
@Override
    public FileResult<AndroidFileIO> resolve(Emulator<AndroidFileIO> emulator, String pathname, int oflags) {
        System.out.println("Open Path with " + pathname);
        if (pathname.equals("/proc/self/cmdline")) {
            return FileResult.success(new ByteArrayFileIO(oflags, pathname, "com.anjuke.android.app".getBytes()));
        } else if (pathname.equals("/proc/self/maps")){
          return FileResult.success(new MapsFileIO(oflags, pathname, emulator.getMemory().getLoadedModules()));
        }
        return null;
    }
```

**Comment by Pr0214** [comment]
你好，将样本的maps cp到sdcard，然后adb pull出来，在Unidbg中使用，样例如下
    @Override
    public FileResult resolve(Emulator emulator, String pathname, int oflags) {
        switch (pathname){
            case "/proc/self/maps":{
                return FileResult.<AndroidFileIO>success(new SimpleFileIO(oflags, new File("unidbg-android/src/test/resources/xxx/maps"), pathname));
            }
        }
        return null;
    }

**Comment by Pr0214** [comment]
你可以附带一下样本吗

**Comment by Andyworker** [comment]
该问题已经解决，通过运行app，把/proc/{pid}/maps文件让`unidbg`载入就可以了
