### ISSUE TITLE
[案例]自荐一个spring boot+unidbg的多线程高并发的开源server项目

### ISSUE THREAD

**Issue by anjia0532** [zhkl0228/unidbg#366]
项目地址 https://github.com/anjia0532/unidbg-boot-server

关键字 spring boot , unidbg-server, 高并发, 高性能, 多线程, 无锁

基于[unidbg 的TTEncryptWorker.java 多线程案例](https://github.com/zhkl0228/unidbg/blob/master/unidbg-android/src/test/java/com/bytedance/frameworks/core/encrypt/TTEncryptWorker.java) 实现的无锁多线程

在我开发机压测QPS能到4000，[详见 ](https://github.com/anjia0532/unidbg-boot-server#%E5%8E%8B%E6%B5%8B)

依赖极少，只要装了java8 jdk即可，maven都可以不装(会自动安装并配置maven) [详见](https://github.com/anjia0532/unidbg-boot-server#java-%E6%89%93%E5%8C%85)

支持极简java打包 ，[详见](https://github.com/anjia0532/unidbg-boot-server#java-%E6%89%93%E5%8C%85)

支持docker打包并运行(机器可以不安装docker也能打包)，[详见](https://github.com/anjia0532/unidbg-boot-server#java-%E6%89%93%E5%8C%85) 

整理了常见的问题，会持续更新，[详见](https://github.com/anjia0532/unidbg-boot-server/blob/main/QA.md)

**Comment by a810291783** [comment]
大佬本地unidbg正常 spring boot报错怎么回事  帮忙看下
lilac open file:/storage/emulated/0/Music
lilac open file:/storage/emulated/0/Pictures
lilac open file:/storage/emulated/0/Movies
lilac open file:/storage/emulated/0/Download
lilac open file:/storage/emulated/0/DCIM
lilac open file:/sys/class/android_usb
lilac open file:/sys/class/regulator/regulator.8
2024-06-03 12:16:02.794  WARN 6108 --- [         task-1] c.g.unidbg.linux.ARM64SyscallHandler     : handleInterrupt intno=2, NR=113, svcNumber=0x0, PC=RX@0x40bfa86c[libc.so]0x6a86c, LR=RX@0x40bad888[libc.so]0x1d888, syscall=null

java.lang.UnsupportedOperationException: clk_id=3
	at com.github.unidbg.linux.ARM64SyscallHandler.clock_gettime(ARM64SyscallHandler.java:1125)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:311)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethodObject(DvmObject.java:93)
	at com.anjia.unidbgserver.service.MobileQQService.getXwDebugID(MobileQQService.java:99)
	at com.anjia.unidbgserver.service.MobileQQServiceWorker.doWork(MobileQQServiceWorker.java:85)
	at com.anjia.unidbgserver.service.MobileQQServiceWorker.getXwDebugID(MobileQQServiceWorker.java:78)
	at com.anjia.unidbgserver.service.MobileQQServiceWorker$$FastClassBySpringCGLIB$$2ae6b84c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2024-06-03 12:16:02.795  WARN 6108 --- [         task-1] com.github.unidbg.AbstractEmulator       : emulate RX@0x400d456c[libfekit.so]0xd456c exception sp=unidbg@0xbfff3f00, msg=clk_id=3, offset=192ms
