### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: Illegal JNI version: 0xffffffff

### ISSUE THREAD

**Issue by twMarriot** [zhkl0228/unidbg#372]
java.lang.IllegalStateException: Please vm.setJni(jni)
	at com.github.unidbg.linux.android.dvm.Hashable.checkJni(Hashable.java:8)
	at com.github.unidbg.linux.android.dvm.DvmClass.getStaticMethodID(DvmClass.java:101)
	at com.github.unidbg.linux.android.dvm.DalvikVM$110.handle(DalvikVM.java:1697)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:103)
	at com.github.unidbg.arm.backend.UnicornBackend$6.hook(UnicornBackend.java:305)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:331)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:220)
	at com.github.unidbg.Module.emulateFunction(Module.java:158)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:232)
	at com.github.unidbg.linux.LinuxSymbol.call(LinuxSymbol.java:27)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:33)
	at com.bytedance.frameworks.core.encrypt.TTEncrypt.<init>(TTEncrypt.java:54)
	at com.bytedance.frameworks.core.encrypt.TTEncrypt.main(TTEncrypt.java:70)

**Comment by hhxdestiny** [comment]
> 代码已经给出提示了，代码中加上vm.setJni(this)

请问下面的报错可能是什么原因？
`JNIEnv->GetMethodID(android/content/pm/PackageManager.getPackageInfo(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;) => 0x3bca8377 was called from RX@0x4000388c[libtest.so]0x388c
[08:56:35 699]  WARN [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:368) - handleInterrupt intno=2, NR=-1073744232, svcNumber=0x11e, PC=unidbg@0xfffe0274, LR=RX@0x400038b0[libtest.so]0x38b0, syscall=null
java.lang.ClassCastException: class com.github.unidbg.linux.android.dvm.DvmObject cannot be cast to class com.github.unidbg.linux.android.dvm.StringObject (com.github.unidbg.linux.android.dvm.DvmObject and com.github.unidbg.linux.android.dvm.StringObject are in unnamed module of loader 'app')
	at com.github.unidbg.linux.android.dvm.AbstractJni.callObjectMethod(AbstractJni.java:785)`
