### ISSUE TITLE
unidbg更新前的没问题，最近版更新unidbg后会包java.lang.NullPointerException

### ISSUE THREAD

**Issue by rookiexjl** [zhkl0228/unidbg#376]
[13:51:37 129]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:469) - handleInterrupt intno=2, NR=-1073744456, svcNumber=0x11e, PC=unidbg@0xfffe0274, LR=RX@0x40001bad[libnative-lib.so]0x1bad, syscall=null
java.lang.NullPointerException
	at com.github.unidbg.linux.android.dvm.AbstractJni.callObjectMethod(AbstractJni.java:783)
	at com.github.unidbg.linux.android.dvm.AbstractJni.callObjectMethod(AbstractJni.java:747)

**Comment by rookiexjl** [comment]
有 lilac的博客 小黑盒 https://blog.csdn.net/qq_38851536/article/details/118115569?spm=1001.2014.3001.5501

**Comment by rookiexjl** [comment]
case "android/content/pm/PackageManager->getPackageInfo(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;": {
                StringObject packageName = varArg.getObjectArg(0);//varArg.getObjectArg(0); ##这里开始为null
                int flags = varArg.getIntArg(1);
                if (log.isDebugEnabled()) {
                    log.debug("getPackageInfo packageName=" +packageName.getValue()+ ", flags=0x" + Integer.toHexString(flags));
                }
                return new PackageInfo(vm, packageName.value, flags);
            }

**Comment by zhkl0228** [comment]
用仓库master最新版可以正常执行

**Comment by rookiexjl** [comment]
感谢
