### ISSUE TITLE
学习中，遇到报错unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)

### ISSUE THREAD

**Issue by yxbbing123** [zhkl0228/unidbg#377]
学习中遇到报错，无从下手解决。请问大各位大神这是什么问题
INFO [com.github.unidbg.linux.android.ArmLD] (ArmLD:293) - dlopen failed: libijm_linker.so, LR=RX@0x40004aa9[libso_demo.so]0x4aa9
INFO [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1890) - openat dirfd=-100, pathname=/proc/self/cmdline, oflags=0x20000, mode=0
 WARN [com.github.unidbg.arm.AbstractARMEmulator] (AbstractARMEmulator$1:58) - memory failed: address=0x30, size=4, value=0x0, PC=RX@0x4010cd3c[libc.so]0x37d3c, LR=RX@0x40004a5b[libso_demo.so]0x4a5b
WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:380) - emulate RX@0x40004a7d[libso_demo.so]0x4a7d failed: sp=unidbg@0xbffff4f0, offset=23ms
com.github.unidbg.arm.backend.BackendException: unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:356)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARMEmulator.eInit(AbstractARMEmulator.java:232)
	at com.github.unidbg.linux.LinuxInitFunction.call(LinuxInitFunction.java:31)
	at com.github.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:140)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:203)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:63)
	at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:219)
	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:296)
	at com.huolala.HuolalaJni.<init>(HuolalaJni.java:36)
	at com.huolala.HuolalaJni.main(HuolalaJni.java:55)
Caused by: unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:354)

**Comment by Pr0214** [comment]
补一下/proc/self/cmdline文件访问，除此之外，加固厂商的SO不建议用Unidbg跑，问题多多。
