### ISSUE TITLE
请问这个报错是什么原因导致的, 在调用so库的init函数的时候抛出的

### ISSUE THREAD

**Issue by 1273082756** [zhkl0228/unidbg#378]
WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:469) - handleInterrupt intno=2, NR=-1073744148, svcNumber=0x17e, PC=unidbg@0xfffe0874, LR=RX@0x4000986d[libwater-lib.so]0x986d, syscall=null
java.lang.UnsupportedOperationException: android/os/Binder->getCallingUid()I
	at com.github.unidbg.linux.android.dvm.AbstractJni.callStaticIntMethodV(AbstractJni.java:189)
	at com.github.unidbg.linux.android.dvm.AbstractJni.callStaticIntMethodV(AbstractJni.java:184)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callStaticIntMethodV(DvmMethod.java:159)
	at com.github.unidbg.linux.android.dvm.DalvikVM$127.handle(DalvikVM.java:1976)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:105)
	at com.github.unidbg.arm.backend.UnicornBackend$10.hook(UnicornBackend.java:323)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:354)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:220)
	at com.github.unidbg.Module.emulateFunction(Module.java:159)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:253)
	at com.fenfei.test.MyTest.xPreAuthencode(MyTest.java:47)
	at com.fenfei.test.MyTest.main(MyTest.java:68)
[11:51:43 396]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:389) - emulate RX@0x400095bd[libwater-lib.so]0x95bd exception sp=unidbg@0xbffff6d8, msg=android/os/Binder->getCallingUid()I, offset=9ms

**Comment by Pr0214** [comment]
正常的补java环境
