### ISSUE TITLE
写了个Demo 测试 Native 调用Java代码 报错

### ISSUE THREAD

**Issue by dicallc** [zhkl0228/unidbg#379]
c代码： 里面很简单就是一个hello word +调用java获取包名
``` c
#include <jni.h>
#include <string>
#include <android/log.h>
#define LOG_TAG "hgllog.h"
#define TAG "NativeTestNative"
#define LOGE(fmt, ...)  ((void)__android_log_print(ANDROID_LOG_ERROR, TAG, "%s: " fmt, __FUNCTION__, ## __VA_ARGS__))


const char *get_packagename(JNIEnv *env, jobject context);

extern "C" JNIEXPORT jstring JNICALL
Java_com_dicallc_unidbg_MainActivity_stringFromJNI(
        JNIEnv *env,
        jobject /* this */, jobject context) {

    std::string hello = "Hello from C++";
    for (int i = 0; i < hello.length(); i++) {
        hello[i] = hello[i] ^ hello.length();
    }
    const char *pkgname = get_packagename(env, context);
    if (strcmp(pkgname, "com.dicallc.unidbg") != -1) {
        LOGE("pkg name => %s", pkgname);
    }

    return env->NewStringUTF(hello.c_str());
}

const char *get_packagename(JNIEnv *env, jobject context) {
    jclass content_class = env->FindClass("android/content/Context");
    if (content_class == nullptr) {
        LOGE("find class error");
        return "";
    }
    jmethodID getPackageName_method = env->GetMethodID(content_class, "getPackageName",
                                                       "()Ljava/lang/String;");
    if (getPackageName_method == nullptr) {
        LOGE("find method error");
        return "";
    }
    if (env->ExceptionCheck()) {
        return "";
    }
    jstring pkgname_string = (jstring) env->CallObjectMethod(context, getPackageName_method);
    const char *ret = env->GetStringUTFChars(pkgname_string,
                                             JNI_FALSE);
    LOGE("pkgname => %s", ret);
    return ret;
}

```

测试代码: 测试代码也很难简单就是模拟so调用 
``` java
public class Hello extends AbstractJni {

    private final VM vm;
    private final DvmClass dvmClass;
    private AndroidEmulator emulator;
    private String processName = "com.dicallc.unidbg";
    private String className = "com/dicallc/unidbg/MainActivity";
    private Memory memory;

    @Override
    public DvmObject<?> callObjectMethodV(BaseVM vm, DvmObject<?> dvmObject, String signature, VaList vaList) {
        if (signature.equals("android/content/Context->getPackageName()Ljava/lang/String;")) {
            //添加代码，让他返回一个争取的值。
            return new StringObject(vm, processName);
        }
        return super.callObjectMethodV(vm, dvmObject, signature, vaList);
    }

    public Hello() {
        // 1. 创建一个Android虚拟机
        emulator = AndroidEmulatorBuilder.for64Bit().setProcessName(processName).build();
        // 2. 获取虚拟机的内存
        memory = emulator.getMemory();
        // 3. 配置Android sdk api版本
        memory.setLibraryResolver(createLibraryResolver(23));
        // 4. 创建Dalvik虚拟环境
        vm = createVM(null);
        // 5. 设置jni
        vm.setJni(this);
        // 6. 设置log
        vm.setVerbose(true);
        vm.setDvmClassFactory(new ProxyClassFactory());
        // 7. 加载目标so文件
        DalvikModule dalvikModule = vm.loadLibrary(new File("unidbg-android/src/test/resources/myso/libnative-lib1.so"), false);
        // 8. 配置native方法类名
        dvmClass = vm.resolveClass(className);
    }

    private LibraryResolver createLibraryResolver(int ver) {
        return new AndroidResolver(ver);
    }

    public static void main(String[] args) throws IOException {
        // 测试
        Hello test01 = new Hello();
        test01.start();
        test01.stop();
    }

    private VM createVM(File apk) {
        return emulator.createDalvikVM(apk);
    }

    private void start() {
        // 9. 调用jni方法
        DvmObject result = dvmClass.callStaticJniMethodObject(emulator, "stringFromJNI()Ljava/lang/String");
        // 10. 打印结果
        System.out.println("result = " + result.getValue());
    }

    private void stop() throws IOException {
        emulator.close();
    }
}
```

跟你issue里说的
vm.setDvmClassFactory(new ProxyClassFactory());

然后写相应的代码
``` java
    @Override
    public DvmObject<?> callObjectMethodV(BaseVM vm, DvmObject<?> dvmObject, String signature, VaList vaList) {
        if (signature.equals("android/content/Context->getPackageName()Ljava/lang/String;")) {
            //添加代码，让他返回一个争取的值。
            return new StringObject(vm, processName);
        }
        return super.callObjectMethodV(vm, dvmObject, signature, vaList);
    }
```

压根没有执行到callObjectMethodV

源码中就报错了

``` shell

com.github.unidbg.arm.backend.BackendException: dvmObject=null, dvmClass=null, jmethodID=unidbg@0xfffffffff6590850
	at com.github.unidbg.linux.android.dvm.DalvikVM64$32.handle(DalvikVM64.java:525)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:92)
	at com.github.unidbg.arm.backend.UnicornBackend$10.hook(UnicornBackend.java:323)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:354)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:220)
	at com.github.unidbg.Module.emulateFunction(Module.java:159)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:139)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:297)
	at com.bytedance.frameworks.core.encrypt.Hello.start(Hello.java:71)
	at com.bytedance.frameworks.core.encrypt.Hello.main(Hello.java:61)
[10:13:40 944]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:389) - emulate RX@0x4000e778[libnative-lib.so]0xe778 exception sp=unidbg@0xbffff4d0, msg=dvmObject=null, dvmClass=null, jmethodID=unidbg@0xfffffffff6590850, offset=8ms
Exception in thread "main" java.lang.NullPointerException
	at com.bytedance.frameworks.core.encrypt.Hello.start(Hello.java:73)
	at com.bytedance.frameworks.core.encrypt.Hello.main(Hello.java:61)
```

能否提供一个例子 这个一直没有搞懂为啥就报错了

so 下载地址:
链接: https://pan.baidu.com/s/1IgIRa_y6FkfvJbPRAuBqnQ 提取码: 3b3n 
--来自百度网盘超级会员v5的分享

**Comment by SeeFlowerX** [comment]
把`vm.setDvmClassFactory(new ProxyClassFactory());`注释调试试

**Comment by dicallc** [comment]
@SeeFlowerX  不行 刚刚试了

**Comment by SeeFlowerX** [comment]
你的jni函数需要一个context参数，但是你的unidbg调用没有给这个参数

推荐练习一下这个系列的教程

- https://blog.csdn.net/qq_38851536/category_11102404.html

**Comment by dicallc** [comment]
@SeeFlowerX  谢谢  我看了
