### ISSUE TITLE
native方法调用返回值是int，调用后如何拿到返回值呢？

### ISSUE THREAD

**Issue by oceanzhang01** [zhkl0228/unidbg#38]
Number ret = TTEncryptUtils.callStaticJniMethod(emulator, "init(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)I"
                , vm.addLocalObject(context),
                vm.addLocalObject(new StringObject(vm, "1.1")),
                vm.addLocalObject(new StringObject(vm, "")),
                vm.addLocalObject(new StringObject(vm, "")),
                vm.addLocalObject(new StringObject(vm, "")),
                vm.addLocalObject(new StringObject(vm, "./")),
                vm.addLocalObject(new StringObject(vm, "./")),
                0, 2
        );

如上，init 方法调用返回值是int类型，我这边调用后如何拿到返回值呢？

**Comment by oceanzhang01** [comment]
补充一下，好像是vm.getObject(hash).getValue()返回null应该是调用失败了
[10:04:42 055]  WARN [cn.banny.unidbg.AbstractEmulator] (AbstractEmulator:271) - emulate unicorn@0x404aac8c[libghostcachedown.so]0xedc8c failed: sp=unicorn@0xbffff784, offset=3ms
unicorn.UnicornException: Invalid instruction (UC_ERR_INSN_INVALID)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eInit(AbstractARMEmulator.java:213)
	at cn.banny.unidbg.linux.AbsoluteInitFunction.call(AbsoluteInitFunction.java:33)
	at cn.banny.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:46)
	at cn.banny.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:171)
	at cn.banny.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:30)
	at cn.banny.unidbg.spi.AbstractLoader.load(AbstractLoader.java:211)
	at cn.banny.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:249)
	at com.bytedance.frameworks.core.encrypt.TTEncrypt.<init>(TTEncrypt.java:60)
	at com.bytedance.frameworks.core.encrypt.TTEncrypt.main(TTEncrypt.java:73)
[10:04:53 828]  WARN [cn.banny.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:377) - handleInterrupt intno=2, NR=-1073745092, svcNumber=0x126, PC=unicorn@0xfffe02f4, syscall=null
java.lang.NullPointerException
	at cn.banny.unidbg.linux.android.dvm.DvmMethod.callStaticObjectMethodV(DvmMethod.java:35)
	at cn.banny.unidbg.linux.android.dvm.DalvikVM$39.handle(DalvikVM.java:714)
	at cn.banny.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:90)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:140)
	at com.bytedance.frameworks.core.encrypt.TTEncrypt.ttEncrypt(TTEncrypt.java:84)
	at com.bytedance.frameworks.core.encrypt.TTEncrypt.main(TTEncrypt.java:75)

这个异常有大神帮忙看下吗 ？

**Comment by zhkl0228** [comment]
带上测试用例
