### ISSUE TITLE
请问大佬，callVoidMethodV 会调用判断文件是否存在这些，如何进行重定向、且绑定更新到 dvmObject

### ISSUE THREAD

**Issue by qqizai** [zhkl0228/unidbg#382]
文件重定向我已经设置了，继承了 IOResolver，绑定了 IO 重定向
```
emulator.getSyscallHandler().addIOResolver(this); // 绑定IO重定向接口
```

但是还是遇到这些文件操作相关的问题

下面标记了 todo  的那几个都是不知道如何构造、如何替换为自己的，烦请大佬指点一下，谢谢。
```
    @Override
    public void callVoidMethodV(BaseVM vm, DvmObject<?> dvmObject, String signature, VaList vaList) {
       
        switch (signature) {
            //todo  这种也是暂不知道如何写
            case "java/lang/StringBuilder-><init>()V":
                vm.resolveClass("java/lang/StringBuilder").newObject(null);
                return;
            //todo 这种，是改如何构造，当前这个方法是无返回的，所以改如何实现文件重定向，并且绑定到原来的值 dvmObject
            case "java/io/File-><init>(Ljava/lang/String;)V":
                System.out.println("new File-><init>: " + vaList.getObjectArg(0).getValue());
                switch (vaList.getObjectArg(0).getValue() + "") {
                    case "/sys/class/power_supply/battery/voltage_now":
                        vm.resolveClass("java/io/File").newObject("unidbg-android/src/test/resources/xxx/battery/voltage_now");
                        return ;
                    case "/sys/class/power_supply/battery/temp":
                        vm.resolveClass("java/io/File").newObject("unidbg-android/src/test/resources/xxx/battery/temp");
                        return ;
                }
            //todo 这种，是改如何构造，当前这个方法是无返回的，所以改如何实现文件重定向，并且绑定到原来的值 dvmObject
            case "java/io/FileInputStream-><init>(Ljava/lang/String;)V":
                switch (vaList.getObjectArg(0).getValue() + "") {
                    case "/proc/cpuinfo":
                        vm.resolveClass("java/io/FileInputStream").newObject(null);// 猜测的写法
                        return;
                }
            case "java/io/InputStreamReader-><init>(Ljava/io/InputStream;)V":
                vm.resolveClass("java/io/InputStreamReader").newObject(null);
                return;
            case "java/io/BufferedReader-><init>(Ljava/io/Reader;)V":
                vm.resolveClass("java/io/BufferedReader").newObject(null);
                return;

        }
        super.callVoidMethodV(vm, dvmObject, signature, vaList);
    }
```

如果，按照我上面的补环境，会报错 ```IndexOutOfBoundsException``` ，大概就是在文件打开的地方  ```java/io/File-><init>(Ljava/lang/String;)V```

```
JNIEnv->CallVoidMethodA(java.io.File@2a18f23c, <init>("/sys/class/power_supply/battery/voltage_now")) was called from RX@0x4015d887[libmtguard.so]0x1d887
JNIEnv->GetMethodID(java/io/File.exists()Z) => 0xebb5c614 was called from RX@0x40146369[libmtguard.so]0x6369
[14:34:57 653]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:469) - handleInterrupt intno=2, NR=-1073744184, svcNumber=0x123, PC=unidbg@0xfffe02c4, LR=RX@0x4015dc27[libmtguard.so]0x1dc27, syscall=null
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.github.unidbg.linux.android.dvm.VarArg.getIntArg(VarArg.java:33)
	at com.github.unidbg.linux.android.dvm.VarArg.getObjectArg(VarArg.java:25)
	at com.dianping.NBridge41.callBooleanMethodV(NBridge41.java:491)
	at com.github.unidbg.linux.android.dvm.AbstractJni.callBooleanMethodV(AbstractJni.java:525)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callBooleanMethodA(DvmMethod.java:124)
	at com.github.unidbg.linux.android.dvm.DalvikVM$36.handle(DalvikVM.java:630)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:105)
	at com.github.unidbg.arm.backend.UnicornBackend$10.hook(UnicornBackend.java:323)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:354)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:235)
	at com.github.unidbg.Module.emulateFunction(Module.java:159)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:133)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethodObject(DvmObject.java:93)
	at com.dianping.NBridge41.callSIUA(NBridge41.java:611)
	at com.dianping.NBridge41.main(NBridge41.java:638)
[14:34:57 657]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:389) - emulate RX@0x4019ab41[libmtguard.so]0x5ab41 exception sp=unidbg@0xbffff600, msg=Index: 0, Size: 0, offset=141ms
```

文件重定向代码：
```
    @Override
    public FileResult resolve(Emulator emulator, String pathname, int oflags) {
        System.out.println("lilac path:" + pathname);
        return null;
    }


打印输出的文件路径有这些：
lilac path:stdin
lilac path:stdout
lilac path:stderr
lilac path:/dev/__properties__
lilac systemkey:ro.kernel.qemu
lilac systemkey:libc.debug.malloc
lilac path:/proc/stat


但并没有监控到我上面的文件路径：
/sys/class/power_supply/battery/voltage_now
/sys/class/power_supply/battery/temp
```

**Comment by qqizai** [comment]
打扰了

**Comment by heyanglin** [comment]
怎么解决的呢？
