### ISSUE TITLE
exit_group status=106和IllegalStateException: Illegal JNI version: 0xffffffff 报错

### ISSUE THREAD

**Issue by CyberShihigami** [zhkl0228/unidbg#390]
运行附加的二进制文件时显示此错误 :
<code>File opened 'stdin' with oflags=0x0 from null
File opened 'stdout' with oflags=0x1 from null
File opened 'stderr' with oflags=0x1 from null
[17:09:27 670]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 673]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 674]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 674]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 674]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 674]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 674]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 674]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 675]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 675]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 675]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 675]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 675]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 676]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 676]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 676]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 677]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 678]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 678]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 678]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 678]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 678]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 679]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 679]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 679]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 679]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 679]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 679]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 680]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 680]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 680]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 680]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 680]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 680]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 680]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 681]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 681]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 681]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 681]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 681]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 681]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 681]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 681]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 681]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 681]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 682]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 682]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 682]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 682]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 682]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 682]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 682]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 683]  WARN [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:514) - Unhandled relocation type 0
[17:09:27 688] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1918) - openat dirfd=-100, pathname=/dev/__properties__, oflags=0xa8000, mode=0
File opened '/dev/__properties__' with oflags=0xa8000 from RX@0x403a7e75[libc.so]0x1be75
[17:09:27 694] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:2043) - fstat file=/dev/__properties__, stat=unidbg@0xbffff690, from=RX@0x403a9c61[libc.so]0x1dc61
[17:09:27 699] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1855) - mmap2 start=0x0, length=131107, prot=0x1, flags=0x1, fd=3, offset=0, from=RX@0x403aa7a3[libc.so]0x1e7a3
[17:09:27 707] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:2001) - close fd=3
File closed '/dev/__properties__' from RX@0x403a5fe1[libc.so]0x19fe1
[17:09:27 720] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1820) - brk address=0x0
[17:09:27 724] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1855) - mmap2 start=0x0, length=262144, prot=0x3, flags=0x22, fd=-1, offset=0, from=RX@0x403aa7a3[libc.so]0x1e7a3
[17:09:27 725] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1699) - prctl option=0x53564d41, arg2=0x0
[17:09:27 725] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1730) - prctl set vma addr=RW@0x40453000, len=262144, pointer=RX@0x403f7021[libc.so]0x6b021, name=libc_malloc
[17:09:27 728] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1683) - munmap start=0x40453000, length=262144, offset=0, from=RX@0x403da909[libc.so]0x4e909
[17:09:27 732] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1855) - mmap2 start=0x0, length=520192, prot=0x3, flags=0x22, fd=-1, offset=0, from=RX@0x403aa7a3[libc.so]0x1e7a3
[17:09:27 733] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1699) - prctl option=0x53564d41, arg2=0x0
[17:09:27 733] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1730) - prctl set vma addr=RW@0x40453000, len=520192, pointer=RX@0x403f7021[libc.so]0x6b021, name=libc_malloc
[17:09:27 734] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1683) - munmap start=0x40453000, length=184320, offset=1, from=RX@0x403da93d[libc.so]0x4e93d
[17:09:27 736] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1683) - munmap start=0x404c0000, length=73728, offset=0, from=RX@0x403da953[libc.so]0x4e953
[17:09:27 744] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1855) - mmap2 start=0x0, length=4096, prot=0x3, flags=0x22, fd=-1, offset=0, from=RX@0x403aa7a3[libc.so]0x1e7a3
[17:09:27 745] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1834) - mprotect address=0x402f7000, alignedAddress=0x402f7000, offset=0, length=4096, alignedLength=4096, prot=0x1
[17:09:27 746] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1918) - openat dirfd=-100, pathname=/proc/stat, oflags=0xa0000, mode=0
File opened '/proc/stat' with oflags=0xa0000 from RX@0x403a7e75[libc.so]0x1be75
[17:09:27 750] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:2043) - fstat file=/proc/stat, stat=unidbg@0xbffff4b8, from=RX@0x403c4f3f[libc.so]0x38f3f
[17:09:27 754] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1855) - mmap2 start=0x0, length=262144, prot=0x3, flags=0x22, fd=-1, offset=0, from=RX@0x403aa7a3[libc.so]0x1e7a3
[17:09:27 755] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1699) - prctl option=0x53564d41, arg2=0x0
[17:09:27 755] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1730) - prctl set vma addr=RW@0x404c0000, len=262144, pointer=RX@0x403f7021[libc.so]0x6b021, name=libc_malloc
[17:09:27 759] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404c3000, count=4096, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 1884 bytes from '/proc/stat'
[17:09:27 772] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404c3000, count=4096, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 0 bytes from '/proc/stat'
[17:09:27 773] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:2001) - close fd=3
File closed '/proc/stat' from RX@0x403a5fe1[libc.so]0x19fe1
[17:09:27 788] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1834) - mprotect address=0x402f7000, alignedAddress=0x402f7000, offset=0, length=4096, alignedLength=4096, prot=0x3
[17:09:27 788] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1834) - mprotect address=0x402f7000, alignedAddress=0x402f7000, offset=0, length=4096, alignedLength=4096, prot=0x1
[17:09:27 795] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1918) - openat dirfd=-100, pathname=/proc/self/maps, oflags=0x20000, mode=0
File opened '/proc/self/maps' with oflags=0x20000 from RX@0x403a7e75[libc.so]0x1be75
[17:09:27 803] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:2043) - fstat file=/proc/self/maps, stat=unidbg@0xbfffec78, from=RX@0x403c4f3f[libc.so]0x38f3f
[17:09:27 804] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404c4000, count=4096, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 864 bytes from '/proc/self/maps'
[17:09:27 811] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:2001) - close fd=3
File closed '/proc/self/maps' from RX@0x403a5fe1[libc.so]0x19fe1
[17:09:27 812] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1918) - openat dirfd=-100, pathname=/system/lib/libc.so, oflags=0x20000, mode=0
File opened '/system/lib/libc.so' with oflags=0x20000 from RX@0x403a7e75[libc.so]0x1be75
[17:09:27 813] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:2043) - fstat file=/system/lib/libc.so, stat=unidbg@0xbfffec80, from=RX@0x403c4f3f[libc.so]0x38f3f
[17:09:27 817] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404c4000, count=4096, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 4096 bytes from '/system/lib/libc.so'
[17:09:27 818] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1992) - lseek fd=3, offset=0, whence=1, pos=4096, from=RX@0x403d4037[libc.so]0x48037
[17:09:27 818] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1992) - lseek fd=3, offset=675840, whence=0, pos=675840, from=RX@0x403d4037[libc.so]0x48037
[17:09:27 819] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404c4000, count=4096, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 2576 bytes from '/system/lib/libc.so'
[17:09:27 819] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1992) - lseek fd=3, offset=491520, whence=0, pos=491520, from=RX@0x403d4037[libc.so]0x48037
[17:09:27 819] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404c4000, count=4096, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 4096 bytes from '/system/lib/libc.so'
[17:09:27 821] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1992) - lseek fd=3, offset=0, whence=0, pos=0, from=RX@0x403d4037[libc.so]0x48037
[17:09:27 821] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404c4000, count=4096, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 4096 bytes from '/system/lib/libc.so'
[17:09:27 821] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404e3e40, count=19216, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 19216 bytes from '/system/lib/libc.so'
[17:09:27 822] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1992) - lseek fd=3, offset=20480, whence=0, pos=20480, from=RX@0x403d4037[libc.so]0x48037
[17:09:27 822] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404c4000, count=4096, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 4096 bytes from '/system/lib/libc.so'
[17:09:27 822] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404e94f0, count=15355, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 15355 bytes from '/system/lib/libc.so'
[17:09:27 823] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:2001) - close fd=3
File closed '/system/lib/libc.so' from RX@0x403a5fe1[libc.so]0x19fe1
[17:09:27 908] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1918) - openat dirfd=-100, pathname=/proc/self/maps, oflags=0x20000, mode=0
File opened '/proc/self/maps' with oflags=0x20000 from RX@0x403a7e75[libc.so]0x1be75
[17:09:27 911] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:2043) - fstat file=/proc/self/maps, stat=unidbg@0xbfffeb90, from=RX@0x403c4f3f[libc.so]0x38f3f
[17:09:27 912] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404c3000, count=4096, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 864 bytes from '/proc/self/maps'
[17:09:27 915] DEBUG [com.github.unidbg.unix.UnixSyscallHandler] (UnixSyscallHandler:259) - read fd=3, buffer=RW@0x404c3000, count=4096, from=RX@0x403d3fa5[libc.so]0x47fa5
Read 0 bytes from '/proc/self/maps'
[17:09:27 916] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:2001) - close fd=3
File closed '/proc/self/maps' from RX@0x403a5fe1[libc.so]0x19fe1
[17:09:27 919] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1834) - mprotect address=0x402f7000, alignedAddress=0x402f7000, offset=0, length=4096, alignedLength=4096, prot=0x3
[17:09:27 920] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1834) - mprotect address=0x402f7000, alignedAddress=0x402f7000, offset=0, length=4096, alignedLength=4096, prot=0x1
[17:09:27 922] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1834) - mprotect address=0x402f7000, alignedAddress=0x402f7000, offset=0, length=4096, alignedLength=4096, prot=0x3
[17:09:27 922] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1834) - mprotect address=0x402f7000, alignedAddress=0x402f7000, offset=0, length=4096, alignedLength=4096, prot=0x1
[17:09:27 923] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1683) - munmap start=0x402f7000, length=4096, offset=0, from=RX@0x403d421d[libc.so]0x4821d
[17:09:27 924] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1663) - exit with code: 106
java.lang.Exception: exit_group status=106
	at com.github.unidbg.linux.ARM32SyscallHandler.exit_group(ARM32SyscallHandler.java:1663)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:402)
	at com.github.unidbg.arm.backend.UnicornBackend$10.hook(UnicornBackend.java:323)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:354)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:375)
	at com.github.unidbg.thread.Function32.run(Function32.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:156)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:92)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:232)
	at com.github.unidbg.linux.AbsoluteInitFunction.call(AbsoluteInitFunction.java:55)
	at com.github.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:140)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:209)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:65)
	at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:219)
	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:300)
	at com.shield.LibSheildEmulation.<init>(LibSheildEmulation.java:34)
	at com.shield.LibSheildEmulation.main(LibSheildEmulation.java:43)
[17:09:27 926]  WARN [com.github.unidbg.arm.AbstractARMEmulator] (AbstractARMEmulator$1:65) - memory failed: address=0x4, size=2, value=0x0, PC=RX@0x40239544[libgmfkpikfijcm.so]0x239544, LR=unidbg@0xffff0000
[17:09:27 927]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:506) - emulate RX@0x40239545[libgmfkpikfijcm.so]0x239545 exception sp=unidbg@0xbffff720, msg=unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED), offset=1ms
Exception in thread "main" java.lang.IllegalStateException: Illegal JNI version: 0xffffffff
	at com.github.unidbg.linux.android.dvm.BaseVM.checkVersion(BaseVM.java:198)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:39)
	at com.shield.LibSheildEmulation.<init>(LibSheildEmulation.java:37)
	at com.shield.LibSheildEmulation.main(LibSheildEmulation.java:43)

Process finished with exit code 1</code>
[libshield32.zip](https://github.com/zhkl0228/unidbg/files/7802625/libshield32.zip)

**Comment by CyberShihigami** [comment]
我的代码:
`

        emulator= AndroidEmulatorBuilder.for32Bit().build();
        emulator.getSyscallHandler().setVerbose(true);
        final Memory memory= emulator.getMemory();
        memory.setLibraryResolver(new AndroidResolver(23));
        vm = emulator.createDalvikVM();
        vm.setVerbose(true);
        DalvikModule dm=vm.loadLibrary(new File("libshield32.so"),true);
        module=dm.getModule();
        vm.setJni(this);
        dm.callJNI_OnLoad(emulator);
    }
    public static void main(String[] args) {
        Logger.getLogger("com.github.unidbg.linux.ARM32SyscallHandler").setLevel(Level.DEBUG);
        Logger.getLogger("com.github.unidbg.unix.UnixSyscallHandler").setLevel(Level.DEBUG);
        LibSheildEmulation shieldEmulation = new LibSheildEmulation();
    }
}`

**Comment by Pr0214** [comment]
shield? https://blog.csdn.net/qq_38851536/article/details/118794351

**Comment by a810291783** [comment]
怎么解决的，我遇到了同样的问题。
