### ISSUE TITLE
Invalid memory read (UC_ERR_READ_UNMAPPED)

### ISSUE THREAD

**Issue by lyndon12** [zhkl0228/unidbg#394]
大佬能够通过这个日志帮我看下是什么问题呢 ,万分感激.
Connected to the target VM, address: '127.0.0.1:57394', transport: 'socket'
Find native function Java_com_bcoin_ns_S_releaseJNIRes => RX@0x40009b0d[libns.so]0x9b0d
JNIEnv->DeleteGlobalRef(null) was called from RX@0x40009b1f[libns.so]0x9b1f
Find native function Java_com_bcoin_ns_S_ft => RX@0x40009a5d[libns.so]0x9a5d
JNIEnv->DeleteGlobalRef(null) was called from RX@0x40009a89[libns.so]0x9a89
JNIEnv->NewGlobalRef("4f0a64739ebb351b34203876286b64d8") was called from RX@0x40009a93[libns.so]0x9a93
JNIEnv->GetStringUtfChars("4f0a64739ebb351b34203876286b64d8") was called from RX@0x40009aa3[libns.so]0x9aa3
Find native function Java_com_bcoin_ns_S_s => RX@0x400096f5[libns.so]0x96f5
JNIEnv->GetStringUtfChars("16424214754388getUserAccountInfoBySecretNew") was called from RX@0x40009723[libns.so]0x9723
JNIEnv->GetStringUtfChars("4f0a64739ebb351b34203876286b64d8") was called from RX@0x40009739[libns.so]0x9739
JNIEnv->ReleaseStringUTFChars("16424214754388getUserAccountInfoBySecretNew") was called from RX@0x40009749[libns.so]0x9749
JNIEnv->ReleaseStringUTFChars("4f0a64739ebb351b34203876286b64d8") was called from RX@0x40009757[libns.so]0x9757
[01:08:45 296]  WARN [com.github.unidbg.arm.AbstractARMEmulator] (AbstractARMEmulator$1:64) - Read memory failed: address=0x40185000, size=4, value=0x0, PC=RX@0x400d6c90[libc.so]0x18c90, LR=RX@0x4000b0d1[libns.so]0xb0d1
[01:08:45 302]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:426) - emulate RX@0x400096f5[libns.so]0x96f5 exception sp=unidbg@0xbffff6d0, msg=unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED), offset=10ms
Exception in thread "main" java.lang.NullPointerException
	at com.anjuke.mobile.sign.S.getSign0(S.java:62)
	at com.anjuke.mobile.sign.S.main(S.java:85)

**Comment by ctycode** [comment]
日志打开看看

**Comment by RockLee0719** [comment]
大佬，这个问题有解决吗？遇到了同样的问题
