### ISSUE TITLE
读取完/proc/self/maps后r0寄存器为0xffffffff

### ISSUE THREAD

**Issue by JiangJianCong** [zhkl0228/unidbg#40]
今天跑一下dy720版本的meta的时候，发现系统调用read了/proc/self/maps这个文件后，r0=0xffffffff r1=0x0 r2=0xffffffff, r3=0x0 r4=0x6991e777 r5=0x98，r0直接变成了0xffffffff，我看这个文件读取了好几次，前面都没问题，下面就出问题了。
报错日志：
![image](https://user-images.githubusercontent.com/24204467/62003403-1be17480-b149-11e9-9b9a-5e260d8695df.png)

不清楚是什么错误，大佬有空帮手看看！
测试用例相关文件：
[test.zip](https://github.com/zhkl0228/unidbg/files/3438915/test.zip)

**Comment by zhkl0228** [comment]
com/ss/sys/ces/a->njss(ILjava/lang/Object;)Ljava/lang/Object; -----, param1 = [124], param2 = [null]

**Comment by zhkl0228** [comment]
以上应该返回什么值？

**Comment by JiangJianCong** [comment]
> 以上应该返回什么值？
返回的是这些 有些没有的可以为空
[njss.txt](https://github.com/zhkl0228/unidbg/files/3440224/njss.txt)

**Comment by JiangJianCong** [comment]
case 131 :
                        return new StringObject(vm, "eyJvcyI6IkFuZHJvaWQiLCJ2ZXJzaW9uIjoiMS4wLjMiLCJ0b2tlbl9pZCI6IiIsImNvZGUiOjUwNH0=");
                    case 130:
                        return new StringObject(vm, "9c:a6:15:6c:82:d6[<!>] aa3 [<!>]-167663424[<!>]");
                    case 125:
                        return new StringObject(vm, "");
                    case 129:
                        return new StringObject(vm, "480[<!>]1080*1920[<!>]");
                    case 126:
                        return new StringObject(vm, "3010");
                    case 120:
                        return new StringObject(vm, "\"core\":4,\"hw\":\"Qualcomm MSM8974PRO-AC\",\"max\":\"2457600\",\"min\":\"300000\",\"ft\":\"swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt\"}");
                    case 127:
                        return new StringObject(vm, "460024199099440");
                    case 128:
                        return new StringObject(vm, "");
                    case 123:
                        return new StringObject(vm, "13014e51334a3937561006d16cfb7400");
                    case 122:
                        return new StringObject(vm, "GMT+08:00");
                    case 121:
                        return new StringObject(vm, "zh_CN");

**Comment by zhkl0228** [comment]
case 124返回的也是String吗？

**Comment by zhkl0228** [comment]
上次UdpSocket的0x8912你是怎么实现的？

**Comment by JiangJianCong** [comment]
> 上次UdpSocket的0x8912你是怎么实现的？

case SocketIO.SOCK_DGRAM:
                        // TODO - 修改了这个值
                        emulator.getMemory().setErrno(UnixEmulator.ENOTTY);
                        return -1;
//                        fd = getMinFd();

//                        fdMap.put(fd, new UdpSocket(emulator));
//                        return fd;
我在他读取这个网卡的时候直接修改返回-1了 ，他就不读取0x8912了

**Comment by JiangJianCong** [comment]
case 124 返回也是string

**Comment by JiangJianCong** [comment]
[13:53:51 663] DEBUG [cn.banny.unidbg.linux.android.dvm.DvmClass] (DvmClass:41) - getStaticMethodID name=com/ss/sys/ces/a->Bill()V, hash=0xc9aa15dd
[13:53:51 663] DEBUG [cn.banny.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$17:269) - GetMethodID class=unicorn@0x257d715f, methodName=Francies, args=()V
[13:53:51 663] DEBUG [cn.banny.unidbg.linux.android.dvm.DvmClass] (DvmClass:53) - getMethodID name=com/ss/sys/ces/a->Francies()V, hash=0x13094b97
[13:53:51 663] DEBUG [cn.banny.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$37:690) - GetStaticMethodID class=unicorn@0x257d715f, methodName=Louis, args=()V
[13:53:51 663] DEBUG [cn.banny.unidbg.linux.android.dvm.DvmClass] (DvmClass:41) - getStaticMethodID name=com/ss/sys/ces/a->Louis()V, hash=0xc71d300a
[13:53:51 663] DEBUG [cn.banny.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$37:690) - GetStaticMethodID class=unicorn@0x257d715f, methodName=Zeoy, args=()V
[13:53:51 663] DEBUG [cn.banny.unidbg.linux.android.dvm.DvmClass] (DvmClass:41) - getStaticMethodID name=com/ss/sys/ces/a->Zeoy()V, hash=0xb89c70cf
[13:53:51 663] DEBUG [cn.banny.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$78:1406) - ExceptionCheck jthrowable=null
unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:140)
	at com.ces.TestMa.meta(TestMa.java:194)
	at com.ces.TestMa.main(TestMa.java:217)
debugger break at: 0x400314dc
 r0=0x40 r1=0x4 r2=0x0, r3=0x12d r4=0x13 r5=0x42cc r6=0xbfffc6b8 r7=0xbfffc7d0 sb=0x17 sl=0xe8 fp=0x2a ip=0x12d sp=0xbfffc3c0 lr=0x1b6 pc=0x400314dc cpsr: N=0, Z=0, C=0, V=0, T=1, mode=0b10000
=> *[        libcms.so]*[0x314dd]*[ 38 f8 02 10 ]*0x400314dc:*ldrh.w r1, [r8, r2]
    [        libcms.so] [0x314e1] [ 47 f8 ac ac ] 0x400314e0: str sl, [r7, #-0xac]
    [        libcms.so] [0x314e5] [ 47 f8 b0 9c ] 0x400314e4: str sb, [r7, #-0xb0]
    [        libcms.so] [0x314e9] [ 57 f8 ac 5c ] 0x400314e8: ldr r5, [r7, #-0xac]
    [        libcms.so] [0x314ed] [ 57 f8 b0 4c ] 0x400314ec: ldr r4, [r7, #-0xb0]
    [        libcms.so] [0x314f1] [       6d 43 ] 0x400314f0: muls r5, r5, r5
    [        libcms.so] [0x314f3] [       64 43 ] 0x400314f2: muls r4, r4, r4
    [        libcms.so] [0x314f5] [       01 35 ] 0x400314f4: adds r5, #1
    [        libcms.so] [0x314f7] [ c4 eb c4 04 ] 0x400314f6: rsb r4, r4, r4, lsl #3
    [        libcms.so] [0x314fb] [       a5 42 ] 0x400314fa: cmp r5, r4


这个是我注释掉自己传的maps的时候，发现[r8, r2]这里指向一段不存在的地方
