### ISSUE TITLE
Caused by: java.lang.IllegalStateException: java.io.IOException: Couldn't load library library unicorn_java

### ISSUE THREAD

**Issue by tiktokerman** [zhkl0228/unidbg#409]
Exception in thread "Thread-2" java.lang.ExceptionInInitializerError
	at com.github.unidbg.AbstractEmulator.<init>(AbstractEmulator.java:80)
	at com.github.unidbg.arm.AbstractARMEmulator.<init>(AbstractARMEmulator.java:47)
	at com.github.unidbg.linux.android.AndroidARMEmulator.<init>(AndroidARMEmulator.java:50)
	at com.github.unidbg.linux.android.AndroidARMEmulator.<init>(AndroidARMEmulator.java:42)
	at com.sun.jna.Gorgon.createARMEmulator(Gorgon.java:24)
	at com.sun.jna.Gorgon.<init>(Gorgon.java:35)
	at com.sun.jna.SimpleHttpServer$gorgon.handle(SimpleHttpServer.java:253)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:705)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:677)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalStateException: java.io.IOException: Couldn't load library library unicorn_java
	at unicorn.Unicorn.<clinit>(Unicorn.java:161)
	... 17 more
Caused by: java.io.IOException: Couldn't load library library unicorn_java
	at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:141)
	at unicorn.Unicorn.<clinit>(Unicorn.java:159)
	... 17 more
Caused by: java.lang.UnsatisfiedLinkError: no unicorn_java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:136)
	... 18 more

**Comment by zhkl0228** [comment]
Can you try unicorn2 backend? what os?

**Comment by githuu5y5u** [comment]
You need to put unicorn_java.dll (win32) into user.dir or do
-Djava.library.path=
