### ISSUE TITLE
混淆的so能hook吗

### ISSUE THREAD

**Issue by proxiti** [zhkl0228/unidbg#41]
作者大大求助，在hook一个so中的方法时出现了异常：
private void encrypt() {
        long hash;
        StringObject obj;
        Number ret = dvmTest.callStaticJniMethod(emulator, "getSign(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
                vm.addLocalObject(new StringObject(vm, "test1")),
                vm.addLocalObject(new StringObject(vm, "test2")),
                vm.addLocalObject(new StringObject(vm, "test3")),
                vm.addLocalObject(new StringObject(vm, "test4")),
                vm.addLocalObject(new StringObject(vm, "test5")));
        hash = ret.intValue() & 0xffffffffL;
        obj = vm.getObject(hash);
        vm.deleteLocalRefs();
        // System.out.println(obj.getValue());
    }
提示找不到方法，这边要用什么写法？

这是异常：
[02:48:54 340]  INFO [cn.banny.unidbg.linux.android.ArmLD] (ArmLD$4:95) - dladdr addr=0x4001ca20, info=unicorn@0xbffff600
[02:48:54 346]  WARN [cn.banny.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:377) - handleInterrupt intno=2, NR=1075875520, svcNumber=0x156, PC=unicorn@0xfffe09e4, syscall=null
unicorn.UnicornException
	at cn.banny.unidbg.linux.android.ArmLD$4.handle(ArmLD.java:96)
	at cn.banny.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:90)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eInit(AbstractARMEmulator.java:213)
	at cn.banny.unidbg.linux.AbsoluteInitFunction.call(AbsoluteInitFunction.java:33)
	at cn.banny.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:46)
	at cn.banny.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:171)
	at cn.banny.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:30)
	at cn.banny.unidbg.spi.AbstractLoader.load(AbstractLoader.java:211)
	at cn.banny.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:167)

用例：
[so.zip](https://github.com/zhkl0228/unidbg/files/3441395/so.zip)

**Comment by zhkl0228** [comment]
java native方法原型是什么？

**Comment by zhkl0228** [comment]
更新最新代码再试下

**Comment by proxiti** [comment]
@Override
    public DvmObject callStaticObjectMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
        switch (signature) {
            case "android/os/SystemProperties->get(Ljava/lang/String;)Ljava/lang/String;" :
                return new StringObject(vm, "");

            case "java/lang/System->getProperty(Ljava/lang/String;)Ljava/lang/String;" :
                return new StringObject(vm, "");
        }
        return super.callStaticObjectMethodV(vm, dvmClass, signature, vaList);
    }

    @Override
    public DvmObject getStaticObjectField(BaseVM vm, DvmClass dvmClass, String signature) {
        switch (signature) {
            case "android/os/Build->MODEL:Ljava/lang/String;" :
                return new StringObject(vm, "MI3");

            case "android/os/Build->CPU_ABI:Ljava/lang/String;" :
                return new StringObject(vm, "armeabi-v7a");

            case "android/os/Build->CPU_ABI2:Ljava/lang/String;" :
                return new StringObject(vm, "none");

            case "android/os/Build$VERSION->RELEASE:Ljava/lang/String;" :
                return new StringObject(vm, "6.0");
        }
        return super.getStaticObjectField(vm, dvmClass, signature);
    }

    @Override
    public int getStaticIntField(BaseVM vm, DvmClass dvmClass, String signature) {
        switch (signature) {
            case "android/os/Build$VERSION->SDK_INT:I" :
                return 20;
        }
        return super.getStaticIntField(vm, dvmClass, signature);
    }

作者大大，我重写了这些方法后，报了这个异常，我没法判断这是哪出了问题：
[14:58:54 814]  INFO [cn.banny.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1562) - openat dirfd=-100, pathname=/proc/version, oflags=0x20000, mode=0
__bionic_open_tzdata_path: ANDROID_DATA not set!
__bionic_open_tzdata_path: ANDROID_ROOT not set!
__bionic_open_tzdata_path: ANDROID_DATA not set!
__bionic_open_tzdata_path: ANDROID_ROOT not set!
__bionic_open_tzdata_path: ANDROID_DATA not set!
__bionic_open_tzdata_path: ANDROID_ROOT not set!
[14:58:54 861]  INFO [cn.banny.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1562) - openat dirfd=-100, pathname=/sys/class/net/wlan0/address, oflags=0x20000, mode=0
[14:58:54 869]  INFO [cn.banny.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1562) - openat dirfd=-100, pathname=/sys/class/net/eth0/address, oflags=0x20000, mode=0
[14:58:54 917]  INFO [cn.banny.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:644) - pthread_clone child_stack=unicorn@0x4047e930, thread_id=1, fn=unicorn@0x401cd7f5[libc.so]0x3f7f5, arg=unicorn@0x4047e930, flags=[CLONE_VM, CLONE_FS, CLONE_FILES, CLONE_SIGHAND, CLONE_THREAD, CLONE_SYSVSEM, CLONE_SETTLS, CLONE_PARENT_SETTID, CLONE_CHILD_CLEARTID]
[14:58:55 222]  WARN [cn.banny.unidbg.AbstractEmulator] (AbstractEmulator:281) - emulate unicorn@0x40063730[lib1542325729-5bee05e146431_20181116154303.so]0x63730 exception sp=unicorn@0xbffff48c, msg=Invalid instruction (UC_ERR_INSN_INVALID), offset=449ms
Exception in thread "main" java.lang.IllegalArgumentException: find method failed: getSign(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at cn.banny.unidbg.linux.android.dvm.DvmClass.findNativeFunction(DvmClass.java:121)
	at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:127)

**Comment by zhkl0228** [comment]
这情况是要自己去逆向分析为什么会这样了，这不是unidbg的问题

**Comment by proxiti** [comment]
异常提示没有找到方法，是某些验证没过所以导致so文件没正确加载吗。

**Comment by zhkl0228** [comment]
要先把前面出现的各种情况解决

**Comment by zhkl0228** [comment]
比如说：各种文件的映射，为什么会提示Invalid instruction (UC_ERR_INSN_INVALID)

**Comment by proxiti** [comment]
好的，明白了

**Comment by proxiti** [comment]
我查了一下unicorn遇到无效指令时才会导致Invalid instruction (UC_ERR_INSN_INVALID)，意思是PC值不正确吗

**Comment by zhkl0228** [comment]
具体要看为什么会转到无效指令

**Comment by proxiti** [comment]
我重新把so dump出来运行，之前的一场没有了，报了这两个异常
[00:53:00 504]  WARN [cn.banny.unidbg.AbstractEmulator] (AbstractEmulator:271) - emulate unicorn@0x401a468d[libc.so]0x1668d failed: sp=unicorn@0x4a8e88fc, offset=47ms
unicorn.UnicornException: Invalid memory write (UC_ERR_WRITE_UNMAPPED)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eInit(AbstractARMEmulator.java:213)
	at cn.banny.unidbg.linux.AbsoluteInitFunction.call(AbsoluteInitFunction.java:33)
	at cn.banny.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:46)
	at cn.banny.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:171)
	at cn.banny.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:30)
	at cn.banny.unidbg.spi.AbstractLoader.load(AbstractLoader.java:211)
	at cn.banny.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:167)
	at com.realcloud.loochadroid.college.MyTest6.<init>(MyTest6.java:42)
	at com.realcloud.loochadroid.college.MyTest6.main(MyTest6.java:56)
[00:53:00 627]  WARN [cn.banny.unidbg.AbstractEmulator] (AbstractEmulator:281) - emulate unicorn@0x40063730[lib1542325729-5bee05e146431_20181116154303.so]0x63730 exception sp=unicorn@0xbffff6b4, msg=Invalid memory fetch (UC_ERR_FETCH_UNMAPPED), offset=123ms
[so.zip](https://github.com/zhkl0228/unidbg/files/3448004/so.zip)

**Comment by zhkl0228** [comment]
dump出来的so运行会引入更多的内存问题

**Comment by proxiti** [comment]
那这个so是不是基本无解了。

**Comment by proxiti** [comment]
我放弃了，还是谢谢老哥了。
