### ISSUE TITLE
求助这个报错是因为什么？mem_protect address=0xd76a6000, size=4096, perms=0x5

### ISSUE THREAD

**Issue by LearnAndy** [zhkl0228/unidbg#413]
JNIEnv->CallStaticObjectMethod(class com/alibaba/one/android/sdk/OneMain, play(0x0, 0x0, 0x3aa7167, java.lang.Integer@5dfcfece) => "e7hLKDZLOocY5zV/2xAP4dlFJ7sUwPKd") was called from RX@0x40397ebd[libsecuritybody.so]0x19ebd
JNIEnv->GetStringUtfChars("e7hLKDZLOocY5zV/2xAP4dlFJ7sUwPKd") was called from RX@0x403a65c7[libsecuritybody.so]0x285c7
JNIEnv->ReleaseStringUTFChars("e7hLKDZLOocY5zV/2xAP4dlFJ7sUwPKd") was called from RX@0x403a6627[libsecuritybody.so]0x28627
[main]I/ValarMorghulis: __1759
[17:51:47 066]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:530) - handleInterrupt intno=2, NR=125, svcNumber=0x0, PC=RX@0x401f7284[libc.so]0x41284, LR=RX@0x400a00a1[libmain.so]0xa00a1, syscall=null
com.github.unidbg.arm.backend.BackendException: mem_protect address=0xd76a6000, size=4096, perms=0x5
	at com.github.unidbg.arm.backend.UnicornBackend.mem_protect(UnicornBackend.java:145)
	at com.github.unidbg.spi.AbstractLoader.mprotect(AbstractLoader.java:196)
	at com.github.unidbg.linux.ARM32SyscallHandler.mprotect(ARM32SyscallHandler.java:1831)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:272)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:386)
	at com.github.unidbg.thread.BaseTask.continueRun(BaseTask.java:94)
	at com.github.unidbg.thread.ThreadTask.dispatch(ThreadTask.java:36)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:346)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:229)
	at com.github.unidbg.Module.emulateFunction(Module.java:159)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:139)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:292)
	at com.com.taobao.litetao.sgmain.LiteTaoEncrypt.init(LiteTaoEncrypt.java:209)
	at com.com.taobao.litetao.sgmain.LiteTaoEncrypt.main(LiteTaoEncrypt.java:782)
Caused by: unicorn.UnicornException: No memory available or memory not present (UC_ERR_NOMEM)
	at unicorn.Unicorn.mem_protect(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.mem_protect(UnicornBackend.java:143)
	... 19 more

**Comment by LearnAndy** [comment]
@zhkl0228  大佬帮忙看一下？

**Comment by LearnAndy** [comment]
Caused by: unicorn.UnicornException: No memory available or memory not present (UC_ERR_NOMEM)
	at unicorn.Unicorn.mem_protect(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.mem_protect(UnicornBackend.java:143)

**Comment by Pr0214** [comment]
访问了你传入的maps

**Comment by LearnAndy** [comment]
> 访问了你传入的maps

这个问题我也知道问题了， 其实是so文件的加载顺序很重要，否则就会报UC_ERR_NOMEM的错

**Comment by Jun-bit** [comment]
搞定签名了吗，我这边感觉算出来的签名是有问题的

**Comment by Jun-bit** [comment]
Have you got the signature? I feel that there is something wrong with the calculated signature.
