### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9

### ISSUE THREAD

**Issue by LearnAndy** [zhkl0228/unidbg#416]
_遇到一个新的报错，明明是传递了9个参数，为啥数组会超出了？

[00:54:04 254] DEBUG [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$165:2681) - GetObjectArrayElement array=["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], index=4
JNIEnv->GetObjectArrayElement(["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], 4) => "mtop.taobao.wireless.home.xianyu.awesome.get" was called from RX@0x4043a573[libmiddletier.so]0x33573
JNIEnv->GetStringUtfChars("mtop.taobao.wireless.home.xianyu.awesome.get") was called from RX@0x4043a589[libmiddletier.so]0x33589
[00:54:04 254] DEBUG [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$161:2605) - GetStringUTFChars string="mtop.taobao.wireless.home.xianyu.awesome.get", isCopy=null, value=mtop.taobao.wireless.home.xianyu.awesome.get, lr=RX@0x4043a589[libmiddletier.so]0x33589
JNIEnv->ReleaseStringUTFChars("mtop.taobao.wireless.home.xianyu.awesome.get") was called from RX@0x4043a5d1[libmiddletier.so]0x335d1
[00:54:04 254] DEBUG [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$162:2625) - ReleaseStringUTFChars string="mtop.taobao.wireless.home.xianyu.awesome.get", pointer=RW@0x402a0000, lr=RX@0x4043a5d1[libmiddletier.so]0x335d1
[00:54:04 255] DEBUG [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$165:2681) - GetObjectArrayElement array=["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], index=5
JNIEnv->GetObjectArrayElement(["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], 5) => "pageName=&pageId=" was called from RX@0x4043a573[libmiddletier.so]0x33573
JNIEnv->GetStringUtfChars("pageName=&pageId=") was called from RX@0x4043a589[libmiddletier.so]0x33589
[00:54:04 255] DEBUG [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$161:2605) - GetStringUTFChars string="pageName=&pageId=", isCopy=null, value=pageName=&pageId=, lr=RX@0x4043a589[libmiddletier.so]0x33589
JNIEnv->ReleaseStringUTFChars("pageName=&pageId=") was called from RX@0x4043a5d1[libmiddletier.so]0x335d1
[00:54:04 255] DEBUG [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$162:2625) - ReleaseStringUTFChars string="pageName=&pageId=", pointer=RW@0x402a0000, lr=RX@0x4043a5d1[libmiddletier.so]0x335d1
[00:54:04 255] DEBUG [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$165:2681) - GetObjectArrayElement array=["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], index=6
JNIEnv->GetObjectArrayElement(["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], 6) => null was called from RX@0x4043a573[libmiddletier.so]0x33573
[00:54:04 256] DEBUG [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$165:2681) - GetObjectArrayElement array=["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], index=7
JNIEnv->GetObjectArrayElement(["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], 7) => null was called from RX@0x4043a573[libmiddletier.so]0x33573
[00:54:04 256] DEBUG [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$165:2681) - GetObjectArrayElement array=["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], index=8
JNIEnv->GetObjectArrayElement(["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], 8) => null was called from RX@0x4043a573[libmiddletier.so]0x33573
[00:54:04 256] DEBUG [com.github.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$165:2681) - GetObjectArrayElement array=["21407387", "YIJLRyY/7fgDAMOPtQCGzfRu&2611780298&&21407387&bcb92105cb51b33688ddc24f0e0b2b6c&1633104280&mtop.taobao.paramservice.request&1.0&16203701c0d59a38cf5c88b165a75b78&36137321407387@fleamarket_android_7.1.60&AlKfW_VGtm3mJXAYHwUErKPkq41dPGN2vXWlskFJDb2Y&0&0&openappkey=DEFAULT_AUTH&27&&&&&&&", false, java.lang.Integer@34f5090e, "mtop.taobao.wireless.home.xianyu.awesome.get", "pageName=&pageId=", null, null, null], index=9
[00:54:04 262]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:530) - handleInterrupt intno=2, NR=-1073745856, svcNumber=0x1a4, PC=unidbg@0xfffe0ad4, LR=RX@0x4043a573[libmiddletier.so]0x33573, syscall=null
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
	at com.github.unidbg.linux.android.dvm.DalvikVM$165.handle(DalvikVM.java:2683)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:132)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:377)
	at com.github.unidbg.thread.Function32.run(Function32.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:337)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:229)
	at com.github.unidbg.Module.emulateFunction(Module.java:166)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:139)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:292)
	at com.taobao.litetao.LibsgEncrypt.getSign(LibsgEncrypt.java:138)
	at com.taobao.litetao.LibsgEncrypt.main(LibsgEncrypt.java:160)
[00:54:04 266]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:417) - emulate RX@0x400120dd[libmain.so]0x120dd exception sp=unidbg@0xbffff028, msg=Index 9 out of bounds for length 9, offset=19ms
xianyu, 70102: null
Exception in thread "main" java.lang.NullPointerException
	at com.taobao.litetao.LibsgEncrypt.getSign(LibsgEncrypt.java:153)
	at com.taobao.litetao.LibsgEncrypt.main(LibsgEncrypt.java:160)

Process finished with exit code 1

**Comment by LearnAndy** [comment]
有人帮忙看看吗？

**Comment by wan1y** [comment]
老哥解决了吗

**Comment by wan1y** [comment]
> 有人帮忙看看吗？
好像是因为参数不够，你凑齐12个好像报错就不一样了

**Comment by LearnAndy** [comment]
我解决了，后面发现是so文件版本的问题，有的版本是9个参数，有的版本是12个参数

**Comment by LearnAndy** [comment]
@wan1y  解决了

**Comment by wan1y** [comment]
> @wan1y 解决了

那请问你能运行了吗，我遇到了2403的错误码

**Comment by anylayer** [comment]
> > @wan1y 解决了
> 
> 那请问你能运行了吗，我遇到了2403的错误码

2403解决了吗，求教
