### ISSUE TITLE
java.lang.UnsupportedOperationException: android/content/SharedPreferences->getInt(Ljava/lang/String;I)I

### ISSUE THREAD

**Issue by kaixinwangzi1982** [zhkl0228/unidbg#417]
java.lang.UnsupportedOperationException: android/content/SharedPreferences->getInt(Ljava/lang/String;I)I
        at com.github.unidbg.utils.WuBaAppSignUtils$1.callIntMethod(WuBaAppSignUtils.java:76)
        at com.github.unidbg.linux.android.dvm.DvmMethod.callIntMethod(DvmMethod.java:139)
        at com.github.unidbg.linux.android.dvm.DalvikVM$25.handle(DalvikVM.java:485)
        at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:103)
        at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
        at unicorn.Unicorn.emu_start(Native Method)
这种代码怎么写，有完整的参考案例吗？
@Override
            public int callIntMethod(BaseVM vm, DvmObject<?> dvmObject, String signature, VarArg varArg) {
                if (signature.equals("java/util/HashMap->size()I")) {
                    Map<?, ?> map = (Map<?, ?>) dvmObject.getValue();
                    return map.size();
                } else if("android/content/SharedPreferences->getInt(Ljava/lang/String;I)I".equals(signature)) {
                	
                }
                throw new UnsupportedOperationException(signature);
            }

**Comment by kaixinwangzi1982** [comment]
@zhkl0228 帮忙看看呗
