### ISSUE TITLE
libcms.so java.lang.AbstractMethodError: class=class com.github.unidbg.linux.file.DirectoryFileIO, offset=0x0, whence=0, path=

### ISSUE THREAD

**Issue by vader-sama** [zhkl0228/unidbg#418]
This error occurs after executing `leviathan` function from `libcms.so` file
I've traced it and the error occurs here:
I have no idea why!
Error:
```
[18:44:08 857]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:533) - handleInterrupt intno=2, NR=19, svcNumber=0x0, PC=RX@0x40009190[libcms.so]0x9190, LR=RX@0x400149f9[libcms.so]0x149f9, syscall=null
java.lang.AbstractMethodError: class=class com.github.unidbg.linux.file.DirectoryFileIO, offset=0x0, whence=0, path=
	at com.github.unidbg.file.AbstractFileIO.lseek(AbstractFileIO.java:102)
	at com.github.unidbg.linux.ARM32SyscallHandler.lseek(ARM32SyscallHandler.java:1972)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:173)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:376)
	at com.github.unidbg.thread.Function32.run(Function32.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:336)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:229)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:260)
	at com.sun.jna.JniDispatch32.test(JniDispatch32.java:173)
	at com.sun.jna.JniDispatch32.main(JniDispatch32.java:156)

```

**Comment by vader-sama** [comment]
It tries to get this file
<img width="1440" alt="Screen Shot 2022-04-14 at 11 14 50 PM" src="https://user-images.githubusercontent.com/87572427/163456419-0ff319b8-2aa5-49d4-b52a-f67501f01318.png">

**Comment by vader-sama** [comment]
It tries to reach this thing
<img width="1440" alt="Screen Shot 2022-04-14 at 11 16 00 PM" src="https://user-images.githubusercontent.com/87572427/163456517-16934e38-b71d-48bf-b2c7-6fcb7da66e2c.png">
