### ISSUE TITLE
求助java.lang.UnsatisfiedLinkError: com.github.unidbg.arm.backend.dynarmic.Dynarmic.context_alloc(J)J

### ISSUE THREAD

**Issue by itheimaqingfeng** [zhkl0228/unidbg#420]
java.lang.UnsatisfiedLinkError: com.github.unidbg.arm.backend.dynarmic.Dynarmic.context_alloc(J)J
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.context_alloc(Native Method)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.context_alloc(Dynarmic.java:55)
	at com.github.unidbg.arm.backend.DynarmicBackend.context_alloc(DynarmicBackend.java:195)
	at com.github.unidbg.thread.BaseTask.saveContext(BaseTask.java:54)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:184)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:346)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:229)
	at com.github.unidbg.Module.emulateFunction(Module.java:166)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:139)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodInt(DvmClass.java:274)
	at com.qingfeng.tiger.TigerCall._genericNt2(TigerCall.java:335)
	at com.qingfeng.tiger.TigerCall.genericNt2(TigerCall.java:329)
	at com.qingfeng.tiger.TigerCall.init(TigerCall.java:273)
	at com.qingfeng.tiger.TigerCall.main(TigerCall.java:259)

**Comment by moondrink** [comment]
maybe /proc/self/exe error

**Comment by colderwd** [comment]
dynarmic.dll这个库没更新，导致新接口context_alloc找不到

**Comment by CoderProducer** [comment]
> dynarmic.dll这个库没更新，导致新接口context_alloc找不到

现在解决了没有？
