### ISSUE TITLE
运行Utilities64 报错 所有test都报错 idea win64

### ISSUE THREAD

**Issue by lgxlovett** [zhkl0228/unidbg#44]
[17:11:26 957]  WARN [cn.banny.unidbg.AbstractEmulator] (AbstractEmulator:271) - emulate unicorn@0x40a19a74[libc.so]0x1aa74 failed: sp=unicorn@0xbffff7b8, offset=3ms
unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARM64Emulator.eInit(AbstractARM64Emulator.java:202)
	at cn.banny.unidbg.linux.AbsoluteInitFunction.call(AbsoluteInitFunction.java:33)
	at cn.banny.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:46)
	at cn.banny.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:171)
	at cn.banny.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:30)
	at cn.banny.unidbg.spi.AbstractLoader.load(AbstractLoader.java:211)
	at cn.banny.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:249)
	at org.telegram.messenger.Utilities64.<init>(Utilities64.java:39)
	at org.telegram.messenger.Utilities64.main(Utilities64.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by lgxlovett** [comment]
我已经将win64 文件夹下的3个dll 放到system32  调用也加上了-Djava.library.path=prebuilt/win64

**Comment by lgxlovett** [comment]
如果不放dll到 system32 之前报这个错

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'capstone': Native library (win32-x86-64/capstone.dll) not found in resource path ([file:/C:/Program%20Files/Java/jdk1.8.0_131/jre/lib/charsets.jar, file:/C:/Program%20Files/Java/jdk1.8.0_131/jre/lib/deploy.jar, file:/C:/Program%20Files/Java/jdk1.8.0_131/jre/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jdk1.8.0_131/jre/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_131/jre/lib/ext/dnsns

**Comment by zhkl0228** [comment]
我这测试跑着没问题
