### ISSUE TITLE
so 调用方法    init 报错

### ISSUE THREAD

**Issue by Jacobi2017** [zhkl0228/unidbg#441]
[14:21:21 250]  WARN [net.fornwall.jelf.ElfDynamicStructure] (ElfDynamicStructure:254) - Unsupported android tag: 0x7ffffffd
[14:21:21 815]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libmtguard.so]symbol ElfSymbol[name=AMediaDrm_getPropertyString, type=function, size=0] is missing relocationAddr=RW@0x400ccf8c[libmtguard.so]0xccf8c, offset=0x0
[14:21:21 958]  INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:96) - [libmtguard.so]AMediaDrm_getPropertyString symbol is missing before init relocationAddr=RW@0x400ccf8c[libmtguard.so]0xccf8c
Exception in thread "main" java.lang.IllegalArgumentException: find method failed: main(I[Ljava/lang/Object)[Ljava/lang/Object
	at com.github.unidbg.linux.android.dvm.DvmClass.findNativeFunction(DvmClass.java:249)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:96)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:291)
	at com.sankuai.meituan.takeoutnew.meituanSign.meituan_sign(meituanSign.java:77)

	at com.sankuai.meituan.takeoutnew.meituanSign.main(meituanSign.java:66)

这个是需要补环境？

**Comment by Pr0214** [comment]
Unsupported android tag: 0x7ffffffd 这个没见过

**Comment by zhkl0228** [comment]
> [14:21:21 250] WARN [net.fornwall.jelf.ElfDynamicStructure] (ElfDynamicStructure:254) - Unsupported android tag: 0x7ffffffd [14:21:21 815] INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:204) - [libmtguard.so]symbol ElfSymbol[name=AMediaDrm_getPropertyString, type=function, size=0] is missing relocationAddr=RW@0x400ccf8c[libmtguard.so]0xccf8c, offset=0x0 [14:21:21 958] INFO [com.github.unidbg.linux.LinuxModule] (LinuxModule:96) - [libmtguard.so]AMediaDrm_getPropertyString symbol is missing before init relocationAddr=RW@0x400ccf8c[libmtguard.so]0xccf8c Exception in thread "main" java.lang.IllegalArgumentException: find method failed: main(I[Ljava/lang/Object)[Ljava/lang/Object at com.github.unidbg.linux.android.dvm.DvmClass.findNativeFunction(DvmClass.java:249) at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:96) at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:291) at com.sankuai.meituan.takeoutnew.meituanSign.meituan_sign(meituanSign.java:77)
> 
> ```
> at com.sankuai.meituan.takeoutnew.meituanSign.main(meituanSign.java:66)
> ```
> 
> 这个是需要补环境？

提供样本代码及相关文件到邮件
