### ISSUE TITLE
请教 报这两个错要怎么补全呢。

### ISSUE THREAD

**Issue by kevinsir** [zhkl0228/unidbg#442]
发现是  第一个是系统没有处理190这个消息。第二个是 PipedWriteFileIO 没有dup2这个实现，请问一下应该怎么补全呢，万分感谢 
 

`[14:18:09 506]  INFO [com.github.unidbg.linux.AndroidSyscallHandler] (AndroidSyscallHandler:456) - Return default pipe pair.
[14:18:11 288]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:533) - handleInterrupt intno=2, NR=190, svcNumber=0x0, PC=RWX@0x40157b5c[libc.so]0x41b5c, LR=RWX@0x401455cb[libc.so]0x2f5cb, syscall=null
[14:18:14 226]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:533) - handleInterrupt intno=2, NR=358, svcNumber=0x0, PC=RWX@0x40157db0[libc.so]0x41db0, LR=RWX@0x40145635[libc.so]0x2f635, syscall=null
java.lang.AbstractMethodError: com.github.unidbg.linux.file.PipedWriteFileIO
java.lang.AbstractMethodError: com.github.unidbg.linux.file.PipedWriteFileIO
	at com.github.unidbg.file.AbstractFileIO.dup2(AbstractFileIO.java:160)
	at com.github.unidbg.linux.ARM32SyscallHandler.dup3(ARM32SyscallHandler.java:2123)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:500)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:376)
	at com.github.unidbg.thread.Function32.run(Function32.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:336)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:229)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethodObject(DvmObject.java:93)
	at com.xhs.ShuMeiService.y1(ShuMeiService.java:71)
	at com.xhs.ShuMeiService.<init>(ShuMeiService.java:274)
	at com.xhs.ShuMeiService.main(ShuMeiService.java:63)`

**Comment by Pr0214** [comment]
这是popen问题

**Comment by Pr0214** [comment]
参照 https://github.com/zhkl0228/unidbg/issues/84

**Comment by kevinsir** [comment]
好的，非常感谢，我试一下

**Comment by winner-hue** [comment]
@kevinsir 问下你的问题解决了吗？我也遇到了同样的问题，能否请教下

**Comment by nanshihui** [comment]
the same as me
