### ISSUE TITLE
 请问 NSArray 该如何构造？ 

### ISSUE THREAD

**Issue by lastdinner22** [zhkl0228/unidbg#455]
如题， 请各位指教

**Comment by lastdinner22** [comment]
本人一介小白，无mac电脑, 有丁点java web 和前端开发经验

1、尝试修改  class-dump文件 , 添加转换类，测试了一下，不行，识别不了添加的类，看了下目录，应该是要重新运行build.sh生成二进制文件的， 但无mac电脑，xcrun 命令无法运行，此方案作罢
2、查找ObjectC NSArray ,NSMutableArray 相关函数，尝试调用, 依旧报错，错误代码如下

代码段：

        ObjcClass _NSString = objc.getClass("NSString");
        ObjcClass _NSMutableArray = objc.getClass("NSMutableArray");
        ObjcObject arr = _NSMutableArray.callObjc("array");

        ObjcObject testStr1 = _NSString.callObjc("stringWithCString:encoding:","str1",4);
        ObjcObject testStr2 = _NSString.callObjc("stringWithCString:encoding:","str2",4);

        arr.call("addObject",testStr1);
        arr.call("addObject",testStr2);


报错信息：

Jul  4 08:47:53 unidbg.local unidbg[14468] <Error>: -[__NSArrayM addObject]: unrecognized selector sent to instance 0x10be5cb60
2022-07-04 08:47:52.594 unidbg[14468:3] -[__NSArrayM addObject]: unrecognized selector sent to instance 0x10be5cb60

请大佬们拨甬指导

**Comment by lastdinner22** [comment]
创建虚拟机加上这几个选项，       
        builder.addBackendFactory(new HypervisorFactory(true));
        builder.addBackendFactory(new DynarmicFactory(true));
        builder.addBackendFactory(new KvmFactory(true));

报错变成如下信息：
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long com.github.unidbg.arm.backend.dynarmic.Dynarmic.context_alloc(long)'
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.context_alloc(Native Method)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.context_alloc(Dynarmic.java:55)
	at com.github.unidbg.arm.backend.DynarmicBackend.context_alloc(DynarmicBackend.java:195)
	at com.github.unidbg.thread.BaseTask.saveContext(BaseTask.java:54)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:184)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.ios.MachOModule.callFunction(MachOModule.java:563)
	at com.github.unidbg.ios.MachOSymbol.call(MachOSymbol.java:21)
	at com.github.unidbg.ios.objc.ObjcImpl.msgSend(ObjcImpl.java:153)
	at com.github.unidbg.ios.struct.objc.ObjcObject.call(ObjcObject.java:59)
	at com.github.unidbg.ios.struct.objc.ObjcObject.callObjc(ObjcObject.java:64)
   。。。。。

**Comment by sunisland** [comment]
> 已解决，打扰了

问一下，你是咋解决的？ 可否贴一下代码
