### ISSUE TITLE
JNi回调方法缺少

### ISSUE THREAD

**Issue by fwb7014** [zhkl0228/unidbg#457]
toReflectedMethod缺少如下实现
java.lang.UnsupportedOperationException: java/lang/Class->getDeclaredMethod(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;
	at com.github.unidbg.linux.android.dvm.AbstractJni.toReflectedMethod(AbstractJni.java:956)
	at com.github.unidbg.linux.android.dvm.AbstractJni.toReflectedMethod(AbstractJni.java:951)
	at com.github.unidbg.linux.android.dvm.DvmMethod.toReflectedMethod(DvmMethod.java:247)
	at com.github.unidbg.linux.android.dvm.DalvikVM64$6.handle(DalvikVM64.java:127)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:118)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)

**Comment by Pr0214** [comment]
这不是正常补环境吗

**Comment by ElieenAndBella** [comment]
这 toReflectedMethod 到底是咋补的

**Comment by 1ens** [comment]
兄弟你这个补好没？
