### ISSUE TITLE
libxxxxxxxxxxx.so load dependency liblog.so failed，依赖so加载失败？

### ISSUE THREAD

**Issue by FBLeee** [zhkl0228/unidbg#461]
```
[17:54:16 647]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:464) - libxxxxxxxxxxx.so load dependency liblog.so failed
[17:54:16 648]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:464) - libxxxxxxxxxxx.so load dependency libstdc++.so failed
[17:54:16 649]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:464) - libxxxxxxxxxxx.so load dependency libm.so failed
[17:54:16 649]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:464) - libxxxxxxxxxxx.so load dependency libc.so failed
[17:54:16 649]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:464) - libxxxxxxxxxxx.so load dependency libdl.so failed
[17:54:16 664]  WARN [com.github.unidbg.arm.AbstractARMEmulator] (AbstractARMEmulator$1:64) - Read memory failed: address=0x0, size=4, value=0x0, PC=RX@0x40012802[libxxxxxxxxxxx.so]0x12802, LR=unidbg@0xffff0000
[17:54:16 665]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:426) - emulate RX@0x400028b5[libxxxxxxxxxxx.so]0x28b5 exception sp=unidbg@0xbffff558, msg=unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED), offset=1ms
Exception in thread "main" java.lang.NullPointerException
	at com.lesson1Try.kanXue.getS(kanXue.java:68)
	at com.lesson1Try.kanXue.main(kanXue.java:44)

```

frida hook是正常的，我这里模仿frida代码去主动调用so库中的导出函数
![image](https://user-images.githubusercontent.com/50468890/182124132-5b003f34-9134-48ff-ae36-708bb67b37d9.png)
请问这个应该怎么解决？

**Comment by Irhtn** [comment]
怎么解决的
