### ISSUE TITLE
Couldn't find resource natives/windows_64/demumble.dll

### ISSUE THREAD

**Issue by Sabirjan** [zhkl0228/unidbg#473]
19:25:29.514 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is WINDOWS_64 os.name is windows 10
19:25:29.514 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/windows_64/
19:25:29.514 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is demumble.dll
19:25:29.514 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource natives/windows_64/demumble.dll
19:25:29.514 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is windows_64/
19:25:29.514 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is demumble.dll
19:25:29.514 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource windows_64/demumble.dll
19:25:29.514 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is META-INF/lib/windows_64/
19:25:29.514 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is demumble.dll
19:25:29.515 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource META-INF/lib/windows_64/demumble.dll
objc[6804]: INITIALIZE: NSFileWritingClaim is fully +initialized
19:25:29.522 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is WINDOWS_64 os.name is windows 10
19:25:29.522 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/windows_64/
19:25:29.522 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is disassembler.dll
19:25:29.522 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource natives/windows_64/disassembler.dll
19:25:29.522 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is windows_64/
19:25:29.522 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is disassembler.dll
19:25:29.522 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource windows_64/disassembler.dll
19:25:29.522 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is META-INF/lib/windows_64/
19:25:29.522 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is disassembler.dll
19:25:29.522 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource META-INF/lib/windows_64/disassembler.dll

下面的是linux环境下的
20:22:07.443 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
20:22:07.443 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/linux_64/
20:22:07.443 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libdemumble.so
20:22:07.443 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - URL is jar:file:/root/.m2/repository/com/github/zhkl0228/demumble/1.0.4/demumble-1.0.4.jar!/natives/linux_64/libdemumble.so
20:22:07.443 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - URL path is file:/root/.m2/repository/com/github/zhkl0228/demumble/1.0.4/demumble-1.0.4.jar!/natives/linux_64/libdemumble.so
20:22:07.443 [main] DEBUG org.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/root/.m2/repository/com/github/zhkl0228/demumble/1.0.4/demumble-1.0.4.jar!/natives/linux_64/libdemumble.so' to '/tmp/nativelib-loader_15500265514075615989/libdemumble.so'
20:22:07.446 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - Problem with library
java.lang.UnsatisfiedLinkError: /tmp/nativelib-loader_15500265514075615989/libdemumble.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/nativelib-loader_15500265514075615989/libdemumble.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)

不知道怎么补了
@zhkl0228

**Comment by y666j999** [comment]
解决了吗？我也遇到这种问题，加载so报这个错

**Comment by Anxuan-CN** [comment]
@y666j999 你解决了吗，我也碰到这个了
