### ISSUE TITLE
 WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:533) - handleInterrupt intno=2, NR=-1073748128, svcNumber=0x12d, PC=unidbg@0xfffe0364, LR=RX@0x4001061b[libpdd_secure.so]0x1061b, syscall=null com.github.unidbg.arm.backend.BackendException 	at com.github.unidbg.linux.android.dvm.DalvikVM$46.handle(DalvikVM.java:792) 	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:132) 	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345) 	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128) 	at unicorn.Unicorn.emu_start(Native Method) 	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376) 	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380) 

### ISSUE THREAD

**Issue by hottech-jxd** [zhkl0228/unidbg#478]
小弟遇到下面的异常就懵逼了，只会简单的补环境，请各位大佬，帮忙看看，小弟非常感谢！！！

[main]I/pdd_secure_native: JNI_OnLoad yubeng_secure data :Feb 25 2022 16:33:05
JNIEnv->NewStringUTF("pdd_secure_native") was called from RX@0x4000f0fd[libpdd_secure.so]0xf0fd
JNIEnv->NewStringUTF("JNI_OnLoad pdd_secure data :Feb 25 2022 16:33:05") was called from RX@0x4000f11f[libpdd_secure.so]0xf11f
JNIEnv->FindClass(com/tencent/mars/xlog/PLog) was called from RX@0x40022d3f[libpdd_secure.so]0x22d3f
JNIEnv->GetStaticMethodID(com/tencent/mars/xlog/PLog.i(Ljava/lang/String;Ljava/lang/String;)V) => 0x40ba56c6 was called from RX@0x40022d6d[libpdd_secure.so]0x22d6d
JNIEnv->FindClass(com/tencent/mars/xlog/PLog) was called from RX@0x400233cd[libpdd_secure.so]0x233cd
arg:"pdd_secure_native" "JNI_OnLoad pdd_secure data :Feb 25 2022 16:33:05"
JNIEnv->CallStaticVoidMethodV(class com/tencent/mars/xlog/PLog, i("pdd_secure_native", "JNI_OnLoad pdd_secure data :Feb 25 2022 16:33:05")) was called from RX@0x400234ab[libpdd_secure.so]0x234ab
JNIEnv->FindClass(com/xunmeng/pinduoduo/secure/DeviceNative) was called from RX@0x4000d8ef[libpdd_secure.so]0xd8ef
JNIEnv->RegisterNatives(com/xunmeng/pinduoduo/secure/DeviceNative, unidbg@0xbffff698, 2) was called from RX@0x4000d95d[libpdd_secure.so]0xd95d
RegisterNative(com/xunmeng/pinduoduo/secure/DeviceNative, info2(Landroid/content/Context;J)Ljava/lang/String;, RX@0x4000a8ed[libpdd_secure.so]0xa8ed)
RegisterNative(com/xunmeng/pinduoduo/secure/DeviceNative, info3(Landroid/content/Context;JLjava/lang/String;)Ljava/lang/String;, RX@0x4000b6f9[libpdd_secure.so]0xb6f9)
JNIEnv->FindClass(android/content/Context) was called from RX@0x40022cb7[libpdd_secure.so]0x22cb7
JNIEnv->GetMethodID(android/content/Context.checkSelfPermission(Ljava/lang/String;)I) => 0xf180a439 was called from RX@0x40022ce5[libpdd_secure.so]0x22ce5
JNIEnv->NewStringUTF("android.permission.READ_PHONE_STATE") was called from RX@0x40010607[libpdd_secure.so]0x10607
[17:40:55 780]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:533) - handleInterrupt intno=2, NR=-1073748128, svcNumber=0x12d, PC=unidbg@0xfffe0364, LR=RX@0x4001061b[libpdd_secure.so]0x1061b, syscall=null
com.github.unidbg.arm.backend.BackendException
	at com.github.unidbg.linux.android.dvm.DalvikVM$46.handle(DalvikVM.java:792)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:132)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.Function32.run(Function32.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:229)
	at com.github.unidbg.Module.emulateFunction(Module.java:162)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:258)
	at com.pdd.Pdd6100.getAntiToken_ByInfo2(Pdd6100.java:212)
	at com.pdd.Pdd6100.getUserProfile(Pdd6100.java:384)
	at com.pdd.Pdd6100.main(Pdd6100.java:311)
[17:40:55 797]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:420) - emulate RX@0x4000a8ed[libpdd_secure.so]0xa8ed exception sp=unidbg@0xbfffe710, msg=com.github.unidbg.arm.backend.BackendException, offset=897ms
Exception in thread "main" java.lang.NullPointerException
	at com.pdd.Pdd6100.getAntiToken_ByInfo2(Pdd6100.java:213)
	at com.pdd.Pdd6100.getUserProfile(Pdd6100.java:384)
	at com.pdd.Pdd6100.main(Pdd6100.java:311)
Disconnected from the target VM, address: '127.0.0.1:62229', transport: 'socket'

Process finished with exit code 1

**Comment by Pr0214** [comment]
methodID 问题

**Comment by okdabenniu** [comment]
> methodID 问题

请问这个mtehodID问题要怎么解决呢

**Comment by chfguozilu** [comment]
可能是vm.resolveClass里面的类的签名写错了
