### ISSUE TITLE
调用JNI函数出现 UC_ERR_FETCH_UNMAPPED

### ISSUE THREAD

**Issue by poping520** [zhkl0228/unidbg#48]
```
[14:07:15 632]  WARN [cn.banny.unidbg.AbstractEmulator] (AbstractEmulator:281) - emulate unicorn@0x40002909[libmpaas_crypto.so]0x2909 exception sp=unicorn@0xbffff758, msg=Invalid memory fetch (UC_ERR_FETCH_UNMAPPED), offset=109ms
debugger break at: 0x2b0
>>> r0=0xfffe0930 r1=0x3 r2=0xb66, r3=0x0 r4=0xfffe0930 r5=0x2b0 r6=0xbffff780 r7=0xbffff78c r8=0x0 r9=0xfb2c38 r10=0x8048020 fp=0xbffff798 ip=0xfffe04c0 sp=0xbffff758 lr=0x40002a03 pc=0x2b0 cpsr: N=0, Z=0, C=1, V=0, T=0, mode=0b10000
```
```
unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at unicorn.Unicorn.mem_read(Native Method)
	at cn.banny.unidbg.arm.AbstractARMEmulator.disassemble(AbstractARMEmulator.java:175)
	at cn.banny.unidbg.arm.AbstractARMDebugger.disassemble(AbstractARMDebugger.java:250)
	at cn.banny.unidbg.arm.SimpleARMDebugger.loop(SimpleARMDebugger.java:34)
	at cn.banny.unidbg.arm.AbstractARMDebugger.debug(AbstractARMDebugger.java:178)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:282)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:361)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:48)
	at test.MpaasCryptoClient.encode(MpaasCryptoClient.java:93)
	at test.MpaasCryptoClient.main(MpaasCryptoClient.java:40)
```
单步调发现是在调用 openssl 的 `EC_POINT_mul`函数报错的
麻烦作者大神看看什么原因
![png](https://user-images.githubusercontent.com/26307327/63322421-f74a7800-c355-11e9-97f0-6d63c7f26d0f.PNG)

[issue.zip](https://github.com/zhkl0228/unidbg/files/3518987/issue.zip)

**Comment by JiangJianCong** [comment]
遇到一样的问题，楼主知道是什么情况么

**Comment by poping520** [comment]
> 遇到一样的问题，楼主知道是什么情况么

不知道

**Comment by poping520** [comment]
> 遇到一样的问题，楼主知道是什么情况么

0x2b0 对应的 JNI 函数没有实现 自己实现下就行了
