### ISSUE TITLE
java.lang.IllegalArgumentException: find method failed

### ISSUE THREAD

**Issue by chiwenheng** [zhkl0228/unidbg#488]
**代码**
`

package com.autohome.mainlib.common.util;

import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.LibraryResolver;
import com.github.unidbg.arm.backend.DynarmicFactory;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmObject;
import com.github.unidbg.linux.android.dvm.StringObject;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.memory.Memory;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;

public class TestBlackBoxSoMethod {

    private final AndroidEmulator emulator;
    private final VM vm;

    private TestBlackBoxSoMethod() {
        emulator = AndroidEmulatorBuilder
            .for32Bit()
            .addBackendFactory(new DynarmicFactory(true))
            .setProcessName("com.cubic.autohome")
            .build();
        // 模拟器的内存操作接口
        Memory memory = emulator.getMemory();
        LibraryResolver resolver = new AndroidResolver(19);
        memory.setLibraryResolver(resolver);
        // 4. 创建Dalvik虚拟环境
        // 5. 设置jni
        vm = emulator.createDalvikVM(new File("/Users/apple/IdeaProjects/unidbg/unidbg-android/src/test/resources/autohome.apk"));
        // 6. 设置log
        vm.setVerbose(true);
        // 加载好的libttEncrypt.so对应为一个模块
        DalvikModule dm =
            vm.loadLibrary(new File("/Users/apple/IdeaProjects/unidbg/unidbg-android/src/test/resources/example_binaries/armeabi-v7a/libblackBox.so"),
                false);
        // 手动执行JNI_OnLoad函数
        dm.callJNI_OnLoad(emulator);
    }

    public static void main(String[] args) {
        long start = System.currentTimeMillis();
        TestBlackBoxSoMethod mainActivity = new TestBlackBoxSoMethod();
        System.out.println("load offset=" + (System.currentTimeMillis() - start) + "ms");
        mainActivity.crack();
    }

    private void crack() {
        //DvmObject<?> obj = ProxyDvmObject.createObject(vm, this);
        DvmObject<?> obj = vm.resolveClass("com/autohome/mainlib/common/util/BlackBox");    //将要调用的so文件在java层的哪一个类中被调用，类的路径
        long start = System.currentTimeMillis();
        List<NameValuePair> paramList = new ArrayList<>();
        //android:versionName="11.30.0"
        paramList.add(new BasicNameValuePair("ss","4802"));
        paramList.add(new BasicNameValuePair("v","11.30.5"));
        paramList.add(new BasicNameValuePair("n","0"));
        paramList.add(new BasicNameValuePair("b","4802"));
        paramList.add(new BasicNameValuePair("c","0"));
        paramList.add(new BasicNameValuePair("bt","c"));
        paramList.add(new BasicNameValuePair("_timestamp","1665988512"));
        paramList.add(new BasicNameValuePair("d","84a4e75e_d721_4a01_a454_89420f2558bb"));
        paramList.add(new BasicNameValuePair("pm","2"));
        paramList.add(new BasicNameValuePair("model","1"));
        DvmObject<String> dvmObject =obj.callJniMethodObject(emulator, "getInterfaceSign(Ljava/util/List;Ljava/lang/String;)Ljava/lang/String;",
                paramList, new StringObject(vm, "XXXX"));
        System.out.println(dvmObject.getValue());
    }
}

`

### **日志**
RegisterNative(com/autohome/mainlib/common/util/BlackBox, dataDynamicDecrypt(Ljava/lang/String;)Ljava/lang/String;, RX@0x4002d591[libblackBox.so]0x2d591)
load offset=599ms
Exception in thread "main" java.lang.IllegalArgumentException: find method failed: getInterfaceSign(Ljava/util/List;Ljava/lang/String;)Ljava/lang/String;
	at com.github.unidbg.linux.android.dvm.DvmClass.findNativeFunction(DvmClass.java:263)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:101)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethodObject(DvmObject.java:93)
	at com.autohome.mainlib.common.util.TestBlackBoxSoMethod.crack(TestBlackBoxSoMethod.java:89)
	at com.autohome.mainlib.common.util.TestBlackBoxSoMethod.main(TestBlackBoxSoMethod.java:54)
Unhandled EXC_BAD_ACCESS at rip 0x00000108e4ded0
dynarmic: macOS MachHandler: Failed to receive mach message. error: 0x10004006 ((ipc/rcv) port changed)

--------------------------------------------------------
打开 log
JNIEnv->FindClass(com/autohome/mainlib/common/util/BlackBox) was called from RX@0x4002df9d[libblackBox.so]0x2df9d
JNIEnv->RegisterNatives(com/autohome/mainlib/common/util/BlackBox, RW@0x400d1008[libblackBox.so]0xd1008, 18) was called from RX@0x4002dfb3[libblackBox.so]0x2dfb3
RegisterNative(com/autohome/mainlib/common/util/BlackBox, interfaceResponseEnCrypt(Ljava/lang/String;)Ljava/lang/String;, RX@0x4002cff1[libblackBox.so]0x2cff1)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, interfaceResponseDeCrypt(Ljava/lang/String;)Ljava/lang/String;, RX@0x4002d099[libblackBox.so]0x2d099)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, data2Encrypt(Ljava/lang/String;)Ljava/lang/String;, RX@0x4002d16d[libblackBox.so]0x2d16d)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, data2Decrypt(Ljava/lang/String;I)Ljava/lang/String;, RX@0x4002d245[libblackBox.so]0x2d245)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, data2EncryptWithSeed(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, RX@0x4002d335[libblackBox.so]0x2d335)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, data2DecryptWithSeed(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;, RX@0x4002d44d[libblackBox.so]0x2d44d)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, boom()Lcom/autohome/mainlib/common/location/LocationHelperHook;, RX@0x4002d87d[libblackBox.so]0x2d87d)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, cancelBoom()Lcom/autohome/mainlib/common/location/LocationHelperHook;, RX@0x4002c9ed[libblackBox.so]0x2c9ed)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, getk()Ljava/lang/String;, RX@0x4002ca3d[libblackBox.so]0x2ca3d)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, getak()Ljava/lang/String;, RX@0x4002cb59[libblackBox.so]0x2cb59)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, getStringSign(Ljava/lang/String;)Ljava/lang/String;, RX@0x4002de8d[libblackBox.so]0x2de8d)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, getStringSign(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, RX@0x4002de99[libblackBox.so]0x2de99)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, getInterfaceSign(Ljava/util/List;I)Ljava/lang/String;, RX@0x4002dc4d[libblackBox.so]0x2dc4d)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, getInterfaceSign(Ljava/util/List;)Ljava/lang/String;, RX@0x4002da69[libblackBox.so]0x2da69)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, getInterfaceSignRSA(Ljava/util/List;Ljava/lang/String;)Ljava/lang/String;, RX@0x4002db61[libblackBox.so]0x2db61)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, getInterfaceSign(Ljava/util/List;Ljava/lang/String;)Ljava/lang/String;, RX@0x4002da85[libblackBox.so]0x2da85)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, data818Encrypt(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;, RX@0x4002d675[libblackBox.so]0x2d675)
RegisterNative(com/autohome/mainlib/common/util/BlackBox, dataDynamicDecrypt(Ljava/lang/String;)Ljava/lang/String;, RX@0x4002d591[libblackBox.so]0x2d591)
load offset=599ms

能找到上面的方法

apk 和 so 相关 见附件
链接: https://pan.baidu.com/s/1vU7GOLhFqguxh_bh9U2XnQ 提取码: plfw

**Comment by chiwenheng** [comment]
DvmObject<?> obj = ProxyDvmObject.createObject(vm, this);
long start = System.currentTimeMillis();
List<NameValuePair> paramList = new ArrayList<>();
//android:versionName="11.30.0"
paramList.add(new BasicNameValuePair("XXX","1"));
DvmObject<String> dvmObject =
obj.callJniMethodObject(emulator, "getInterfaceSign(Ljava/util/List;Ljava/lang/String;)Ljava/lang/String;",
paramList, "XXXXX");

System.out.println(dvmObject.getValue());

**Comment by chiwenheng** [comment]
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/5625556/196119143-87d5b8b2-172b-477e-a108-24b7c6801a22.png">

**Comment by chiwenheng** [comment]
修改目前逻辑进行实现
