### ISSUE TITLE
银联SDK 中 handleInterrupt intno=2, NR=226, svcNumber=0x196  operator new 操作报错

### ISSUE THREAD

**Issue by killercc** [zhkl0228/unidbg#491]
完整异常堆栈
Find native function Java_com_unionpay_utils_UPUtils_forWap => RX@0x4001959c[libentryexpro.so]0x1959c
JNIEnv->GetStringUtfChars("awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww") was called from RX@0x400195e0[libentryexpro.so]0x195e0
JNIEnv->FindClass(com/unionpay/uppay/PayActivity) was called from RX@0x400195fc[libentryexpro.so]0x195fc
JNIEnv->GetStaticFieldID(com/unionpay/uppay/PayActivity.aLjava/lang/String;) => 0x5fb04b41 was called from RX@0x40019628[libentryexpro.so]0x19628
[08:26:39 056]  WARN [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:371) - handleInterrupt intno=2, NR=226, svcNumber=0x196, PC=unidbg@0xfffe09f4, LR=RX@0x40019644[libentryexpro.so]0x19644, syscall=null
java.lang.UnsupportedOperationException
	at com.github.unidbg.linux.android.dvm.DalvikVM64$151.handle(DalvikVM64.java:2360)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:117)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:162)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:316)
	at com.JDsign.UnionPay_so.forUrl(UnionPay_so.java:75)
	at com.JDsign.UnionPay_so.main(UnionPay_so.java:67)
[08:26:39 062]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:420) - emulate RX@0x4001959c[libentryexpro.so]0x1959c exception sp=unidbg@0xbffff6b0, msg=java.lang.UnsupportedOperationException, offset=10ms
Exception in thread "main" java.lang.NullPointerException
	at com.JDsign.UnionPay_so.forUrl(UnionPay_so.java:80)
	at com.JDsign.UnionPay_so.main(UnionPay_so.java:67)

定位到so的异常位置 0x1959c 为 v11 = operator new(0x50uLL);
so样本+unidbg 代码 https://wwm.lanzoux.com/i2hx00f8iite
java层函数签名
public static native String forConfig(int i, String str);

public static native String forUrl(int i);

public static native String forWap(int i, String str);

public static native String getIssuer(int i);

public static native String getSubject(int i);

public static native String getTalkingDataIdForAssist(int i);

**Comment by zhkl0228** [comment]
https://github.com/zhkl0228/unidbg/commit/574d36f588f9d211015a2088a9a749905008443f
这个提交看下是否能解决

**Comment by killercc** [comment]
> [574d36f](https://github.com/zhkl0228/unidbg/commit/574d36f588f9d211015a2088a9a749905008443f) 这个提交看下是否能解决

可以了  谢谢大佬
