### ISSUE TITLE
unidbg decodeArgsShorty 错误

### ISSUE THREAD

**Issue by winner-hue** [zhkl0228/unidbg#503]
@zhkl0228 求大佬指教，在模拟执行so的时候，在解码参数的时候报了这个错误，该怎么处理
JNIEnv->GetMethodID(android/telephony/TelephonyManager.getDeviceIdLjava/lang/String;) => 0x4928fbf4 was called from RX@0x400233fd[libpdd_secure.so]0x233fd
[20:48:13 468]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:533) - handleInterrupt intno=2, NR=-1073753424, svcNumber=0x11f, PC=unidbg@0xfffe0284, LR=RX@0x40023445[libpdd_secure.so]0x23445, syscall=null
java.lang.IllegalStateException: i=1, char=j, args=Ljava/lang/String;
	at com.github.unidbg.linux.android.dvm.DvmMethod.decodeArgsShorty(DvmMethod.java:301)
	at com.github.unidbg.linux.android.dvm.VarArg.<init>(VarArg.java:15)
	at com.github.unidbg.linux.android.dvm.VaList.<init>(VaList.java:6)
	at com.github.unidbg.linux.android.dvm.VaList32.<init>(VaList32.java:15)
	at com.github.unidbg.linux.android.dvm.DalvikVM$32.handle(DalvikVM.java:546)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:132)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.Function32.run(Function32.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:229)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:316)
	at com.einnovation.temu.NG2Token.ng2(NG2Token.java:59)
	at com.einnovation.temu.NG2Token.main(NG2Token.java:177)

**Comment by makkartik4** [comment]
I have the solution dm me i had run this library for temu app i know its aes encryption
