### ISSUE TITLE
各位前辈大家好,有个问题一直没有能解决已经卡了好几天了,不知道怎么处理,能教教我吗?

### ISSUE THREAD

**Issue by okdabenniu** [zhkl0228/unidbg#505]
[main]I/R/VY*ZTUk: R/VY*ZTUV+]
[01:44:57 261]  WARN [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:399) - handleInterrupt intno=2, NR=-130432, svcNumber=0x11f, PC=unidbg@0xfffe0284, LR=RX@0x400051f4[libJMEncryptBox.so]0x51f4, syscall=null
com.github.unidbg.arm.backend.BackendException: dvmObject=android.app.Application@4c309d4d, dvmClass=class android/app/Application, jmethodID=unidbg@0xfffffffff6590850
	at com.github.unidbg.linux.android.dvm.DalvikVM64$32.handle(DalvikVM64.java:527)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:118)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:262)
	at com.github.unidbg.linux.LinuxSymbol.call(LinuxSymbol.java:27)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:33)
	at com.ijiami.ceshi.likeliang.<init>(likeliang.java:47)
	at com.ijiami.ceshi.likeliang.main(likeliang.java:53)
[01:44:57 267]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:420) - emulate RX@0x40005ffc[libJMEncryptBox.so]0x5ffc exception sp=unidbg@0xbffff440, msg=dvmObject=android.app.Application@4c309d4d, dvmClass=class android/app/Application, jmethodID=unidbg@0xfffffffff6590850, offset=14ms
Exception in thread "main" java.lang.IllegalStateException: Illegal JNI version: 0xffffffff
	at com.github.unidbg.linux.android.dvm.BaseVM.checkVersion(BaseVM.java:210)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:39)
	at com.ijiami.ceshi.likeliang.<init>(likeliang.java:47)
	at com.ijiami.ceshi.likeliang.main(likeliang.java:53)

**Comment by okdabenniu** [comment]
缺了两个环境我补上了 但是还是不行 完整代码如下


`package com.ijiami.ceshi;

import com.github.unidbg.Module;
import com.github.unidbg.linux.android.AndroidEmulatorBuilder;
import com.github.unidbg.linux.android.AndroidResolver;
import com.github.unidbg.linux.android.dvm.*;
import com.github.unidbg.memory.Memory;
import java.io.File;
import com.github.unidbg.AndroidEmulator;
import com.github.unidbg.linux.android.dvm.DalvikModule;
import com.github.unidbg.linux.android.dvm.DvmClass;
import com.github.unidbg.linux.android.dvm.VM;
import com.github.unidbg.linux.android.dvm.array.ArrayObject;
import java.util.ArrayList;
import java.util.List;

public class likeliang extends AbstractJni {
    private final AndroidEmulator emulator;
    private final VM vm;
    private final Module module;

    //private final DvmClass TTEncryptUtils;
    public likeliang() {
        // 创建模拟器实例，进程名依照实际进程名填写，要模拟32位或者64位，在这里区分
        emulator = AndroidEmulatorBuilder.for64Bit().setProcessName("com.ijiami.JMEncryptBoxByRandom").build();
        // 模拟器的内存操作接口
        final Memory memory = emulator.getMemory();
        // 设置系统类库解析，有19和23 两个版本选择
        memory.setLibraryResolver(new AndroidResolver(23));
        // 创建Android虚拟机,传入APK，Unidbg可以替我们做部分签名校验的工作
        vm = emulator.createDalvikVM();
        // 日志开关
        vm.setVerbose(false);
        // 加载so
        DalvikModule dm = vm.loadLibrary(new File("unidbg-android/src/test/java/com/ijiami/ceshi/libJMEncryptBox.so"), false);
        //获取SO模块的句柄
        module = dm.getModule();
        System.out.println("SO模块句柄:" + module.base);
        // 设置JNI,简单的说就是jni 是java世界和c/c++世界沟通的桥梁，java可以通过jni来调用c/c++封装好的函数，反之也可以，其中第⼀个参数JNIEnv *env，这个参数就是java环境。
        vm.setJni(this);
        // Java调用System.loadLibrary()加载一个库的时候，会首先在库中搜索JNI_OnLoad()函数，如果该函数存在，则执行它；
        dm.callJNI_OnLoad(emulator);
        vm.resolveClass("com/ijiami/JMEncryptBoxByRandom");
    }

    //主入口
    public static void main(String[] args) {
        likeliang Likeliang = new likeliang();
    }

    public void encryptBuType1() {
        // 0x4a069
        List<Object> list = new ArrayList<>(10);
        list.add(vm.getJNIEnv()); // 第一个参数是env
        list.add(0); // 第二个参数，实例方法是jobject，静态方法是jclass，直接填0，一般用不到。
        module.callFunction(emulator, 0x6524, list.toArray());
    }
    //配置环境
    @Override
    public DvmObject<?> callObjectMethodV(BaseVM vm, DvmObject<?> dvmObject, String signature, VaList vaList) {
        switch (signature) {
            case "android/app/ActivityThread->getApplication()Landroid/app/Application;":
                return vm.resolveClass("android/app/Application").newObject(signature);
        }
        return super.callObjectMethodV(vm, dvmObject, signature, vaList);
    }

    @Override
    public DvmObject<?> callStaticObjectMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
        switch (signature) {
            case "com/ijiami/JMEncryptBox->getFinger(Ljava/lang/String;[B)Ljava/lang/String;":
                return vm.resolveClass("java/lang/String").newObject(null);
            case "android/app/ActivityThread->currentActivityThread()Landroid/app/ActivityThread;":
                return vm.resolveClass("android/app/ActivityThread.currentActivityThread", vm.resolveClass("android/app/ActivityThread")).newObject(signature);
        }
        return super.callObjectMethodV(vm, dvmClass, signature, vaList);
    }
}

`

**Comment by okdabenniu** [comment]
请各位前辈大佬不吝赐教,拜谢了

**Comment by okdabenniu** [comment]
另外还有个问题,现在加载完毕SO后会提示一个乱码,我也不知道是什么?请问有人知道吗?
![111](https://user-images.githubusercontent.com/122476352/212067894-d825f169-e9c5-4c3b-afc5-d9a12648a384.jpg)

**Comment by okdabenniu** [comment]
**救命...卡了几天了**
