### ISSUE TITLE
createNewFile failed: C:\Users\Henry\AppData\Local\Temp\rootfs\default\C:\Users\Henry\***\server\target\sg_oc.lock, offset=101ms

### ISSUE THREAD

**Issue by HenryWu01** [zhkl0228/unidbg#507]
我使用的版本如下:
```Groovy
implementation 'com.github.zhkl0228.unidbg:unidbg-api:v0.9.7'
implementation 'com.github.zhkl0228.unidbg:unidbg-android:v0.9.7'
implementation 'com.github.zhkl0228.unidbg:unidbg-unicorn2:v0.9.7'
```

下面是完整的日志:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[main]W/libc: pthread_create failed: clone failed: Out of memory
2�� 13, 2023 8:39:27 ���� com.github.unidbg.linux.ARM64SyscallHandler faccessat
��Ϣ: faccessat failed dirfd=-100, pathname=C:\Users\Henry\***\server\target/storage/com.taobao.maindex, oflags=0x0, mode=0x0
2�� 13, 2023 8:39:27 ���� com.github.unidbg.linux.ARM64SyscallHandler faccessat
��Ϣ: faccessat failed dirfd=-100, pathname=C:\Users\Henry\***\server\target\app_SGLib/lvmreport, oflags=0x0, mode=0x0
2�� 13, 2023 8:39:27 ���� com.github.unidbg.linux.AndroidSyscallHandler mkdirat
��Ϣ: mkdir pathname=C:\Users\Henry\***\server\target\app_SGLib/lvmreport, mode=448
2�� 13, 2023 8:39:27 ���� com.github.unidbg.linux.ARM64SyscallHandler hook
����: handleInterrupt intno=2, NR=56, svcNumber=0x0, PC=RX@0x4046a6a4[libc.so]0x6a6a4, LR=RX@0x40422854[libc.so]0x22854, syscall=null
java.lang.IllegalStateException: createNewFile failed: C:\Users\Henry\AppData\Local\Temp\rootfs\default\C:\Users\Henry\***\server\target\sg_oc.lock
	at com.github.unidbg.file.BaseFileSystem.createFileIO(BaseFileSystem.java:97)
	at com.github.unidbg.file.BaseFileSystem.open(BaseFileSystem.java:60)
	at com.github.unidbg.file.linux.LinuxFileSystem.open(LinuxFileSystem.java:35)
	at com.github.unidbg.unix.UnixSyscallHandler.resolve(UnixSyscallHandler.java:114)
	at com.github.unidbg.unix.UnixSyscallHandler.open(UnixSyscallHandler.java:324)
	at com.github.unidbg.linux.ARM64SyscallHandler.openat(ARM64SyscallHandler.java:1306)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:177)
	at com.github.unidbg.arm.backend.Unicorn2Backend$11.hook(Unicorn2Backend.java:343)
	at com.github.unidbg.arm.backend.unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:109)
	at com.github.unidbg.arm.backend.unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.unicorn.Unicorn.emu_start(Unicorn.java:312)
	at com.github.unidbg.arm.backend.Unicorn2Backend.emu_start(Unicorn2Backend.java:380)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:284)
	at com.taobao.hack.XSignTool.init(XSignTool.java:55)
	at com.taobao.hack.XSignTool.<init>(XSignTool.java:49)
	at com.taobao.hack.XSignTool.main(XSignTool.java:203)
Caused by: java.io.IOException: Cannot create directory 'C:\Users\Henry\AppData\Local\Temp\rootfs\default\C:\Users\Henry\***\server\target'.
	at org.apache.commons.io.FileUtils.mkdirs(FileUtils.java:2200)
	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:1383)
	at com.github.unidbg.file.BaseFileSystem.createFileIO(BaseFileSystem.java:91)
	... 24 more

2�� 13, 2023 8:39:27 ���� com.github.unidbg.AbstractEmulator handleEmuException
����: emulate RX@0x4003c884[libmain.so]0x3c884 exception sp=unidbg@0xbfffe1e0, msg=createNewFile failed: C:\Users\Henry\AppData\Local\Temp\rootfs\default\C:\Users\Henry\***\server\target\sg_oc.lock, offset=101ms
2�� 13, 2023 8:39:27 ���� com.github.unidbg.linux.android.dvm.DalvikVM64 handle
����: Throw dvmObject=com.alibaba.wireless.security.open.SecException@7ba8c737, class=class com/alibaba/wireless/security/open/SecException
```

> 项目名称已经用 ``***`` 替代

看到网上有说切换 sdk Version 到 19 的, 我这里切换到 19 就会触发 Illegal JNI version 0xffffffff, arm32 则无法加载 so

**Comment by fxh615** [comment]
23 版本开启多线程。
