### ISSUE TITLE
So 文件提示失败

### ISSUE THREAD

**Issue by KKKKKKKEM** [zhkl0228/unidbg#513]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/30348060/223754457-3b6a6a35-d5a5-4d68-93d2-1d0d7611386c.png">

异常信息：
```
Exception in thread "main" net.fornwall.jelf.ElfException: Bad magic number for file
	at net.fornwall.jelf.ElfFile.<init>(ElfFile.java:271)
	at net.fornwall.jelf.ElfFile.fromBuffer(ElfFile.java:259)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:316)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:174)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:62)
	at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:237)
	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:239)
	at com.alibaba.aliexpresshd.doCommand.<init>(doCommand.java:28)
	at com.alibaba.aliexpresshd.doCommand.main(doCommand.java:35)
```
加载代码：
```java
        emulator = AndroidEmulatorBuilder.for32Bit().addBackendFactory(new Unicorn2Factory(true)).setProcessName("com.alibaba.aliexpresshd").build();
        Memory memory = emulator.getMemory();
        memory.setLibraryResolver(new AndroidResolver(23));
        vm = emulator.createDalvikVM(new File("unidbg-android/src/test/resources/AliExpress_8.62.2_Apkpure.apk"));
        vm.setJni(this);
        vm.setVerbose(true);
        DalvikModule dm = vm.loadLibrary("sgmain", false);
        JNICLibrary = vm.resolveClass("com.taobao.wireless.security.adapter.JNICLibrary");
        dm.callJNI_OnLoad(emulator);
```

APK :
[AliExpress_8.62.2_Apkpure.apk](https://apkbog.com/en/apk/aliexpress-shopping-app/8.62.2)

**Comment by Pr0214** [comment]
你加载的这个 sgmain 不是 ELF 文件，你要加载 lib 下的另一个 sgmainxxx，带版本号的。
