### ISSUE TITLE
文件报错 大佬求下解决方案

### ISSUE THREAD

**Issue by hao13358806769** [zhkl0228/unidbg#515]
[main] WARN com.github.unidbg.linux.ARM64SyscallHandler - handleInterrupt intno=2, NR=-130432, svcNumber=0x11f, PC=unidbg@0xfffe0284, LR=RX@0x40541cec[libpoxy.so]0x41cec, syscall=null
com.github.unidbg.arm.backend.BackendException: dvmObject=java.io.File@6c80d78a, dvmClass=class java.io.File, jmethodID=unidbg@0xffffffffa8c98101
	at com.github.unidbg.linux.android.dvm.DalvikVM64$32.handle(DalvikVM64.java:525)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:91)
	at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
	at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend64.callSVC(DynarmicBackend64.java:42)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:61)
	at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:76)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:220)
	at com.github.unidbg.Module.emulateFunction(Module.java:158)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:133)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethodObject(DvmObject.java:93)
	at com.crack.QQSignTlv544.QQgetByte(QQSignTlv544.java:220)
	at com.crack.QQSignTlv544.main(QQSignTlv544.java:233)
[main] WARN com.github.unidbg.AbstractEmulator - emulate RX@0x40516548[libpoxy.so]0x16548 exception sp=unidbg@0xbfffe410, msg=dvmObject=java.io.File@6c80d78a, dvmClass=class java.io.File, jmethodID=unidbg@0xffffffffa8c98101, offset=132ms
Exception in thread "main" java.lang.NullPointerException
	at com.crack.QQSignTlv544.QQgetByte(QQSignTlv544.java:226)
	at com.crack.QQSignTlv544.main(QQSignTlv544.java:233)

**Comment by Pr0214** [comment]
这是典型的 methodid 问题。

**Comment by hexin46373** [comment]
解决了吗?怎么解决的呢?

**Comment by axbing** [comment]
怎么解决呀？
