### ISSUE TITLE
求大佬,不知道是找不到类,还是补环境问

### ISSUE THREAD

**Issue by hyoHhh** [zhkl0228/unidbg#517]
[19:58:31 410]  WARN [com.github.unidbg.linux.android.dvm.jni.ProxyJni] (ProxyJni:223) - callStaticObjectMethodV
java.lang.ClassNotFoundException: android.app.ActivityThread
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)

@Override
    public DvmObject<?> callStaticObjectMethodV(BaseVM vm, DvmClass dvmClass, String signature, VaList vaList) {
        if (signature.equals("android/app/ActivityThread->getApplication()Landroid/app/Application;")){
            return vm.resolveClass("android/app/Application").newObject(null);
        }
        switch (signature) {
            case "android/app/ActivityThread->currentActivityThread()Landroid/app/ActivityThread;":
                return vm.resolveClass("android/app/ActivityThread").newObject(null);
        }
        if (signature.equals("android.app.ActivityThread")) {
                return vm.resolveClass("android/app/ActivityThread").newObject(null);
        }

        return super.callStaticObjectMethodV(vm, dvmClass, signature, vaList);

    }

**Comment by Pr0214** [comment]
你好，把你代码里的 vm.setDvmClassFactory(new ProxyClassFactory()); 删掉，这个样本所依赖的类没法通过反射获取，所以报错。

**Comment by hyoHhh** [comment]
> 

感谢大佬,这个又出新问题了com.github.unidbg.arm.backend.BackendException: dvmObject=android.app.Application@326de728, dvmClass=class android/app/Application, jmethodID=unidbg@0xfffffffff6590850
	at com.github.unidbg.linux.android.dvm.DalvikVM64$32.handle(DalvikVM64.java:527)
,看到您在别的问题回复是methodID问题,实在找不到资料

**Comment by sxhao-dodo** [comment]
我也遇到了这个错误，vm.setDvmClassFactory(new ProxyClassFactory()); 删掉后还是报这个错
