### ISSUE TITLE
1

### ISSUE THREAD

**Issue by hyoHhh** [zhkl0228/unidbg#518]

**Comment by hyoHhh** [comment]
1

**Comment by sxhao-dodo** [comment]
问题解决了吗？删除后还是报错。而且很奇怪的是，报出来的是JniFunction，但是我的代码类是继承AbstractJni的。这种怎么补环境？
警告: callStaticObjectMethodV
java.lang.ClassNotFoundException: android.app.ActivityThread
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.unidbg.linux.android.dvm.jni.ProxyClassLoader.loadClass(ProxyClassLoader.java:22)
	at com.github.unidbg.linux.android.dvm.jni.ProxyJni.callStaticObjectMethodV(ProxyJni.java:220)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callStaticObjectMethodV(DvmMethod.java:59)
	at com.github.unidbg.linux.android.dvm.DalvikVM64$112.handle(DalvikVM64.java:1836)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:121)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:378)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:341)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:262)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:262)
	at com.github.unidbg.linux.LinuxSymbol.call(LinuxSymbol.java:27)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:33)

java.lang.UnsupportedOperationException: android/app/ActivityThread->currentActivityThread()Landroid/app/ActivityThread;
	at com.github.unidbg.linux.android.dvm.JniFunction.callStaticObjectMethodV(JniFunction.java:173)
	at com.github.unidbg.linux.android.dvm.JniFunction.callStaticObjectMethodV(JniFunction.java:167)
	at com.github.unidbg.linux.android.dvm.jni.ProxyJni.callStaticObjectMethodV(ProxyJni.java:227)
