### ISSUE TITLE
异常  java.lang.UnsupportedOperationException: clk_id=2

### ISSUE THREAD

**Issue by lengong** [zhkl0228/unidbg#522]
### 
19:46:44.916 [main] WARN com.github.unidbg.linux.ARM64SyscallHandler - handleInterrupt intno=2, NR=113, svcNumber=0x0, PC=RX@0x4046a86c[libc.so]0x6a86c, LR=RX@0x4041d888[libc.so]0x1d888, syscall=null
java.lang.UnsupportedOperationException: clk_id=2
	at com.github.unidbg.linux.ARM64SyscallHandler.clock_gettime(ARM64SyscallHandler.java:1194)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:327)
	at com.github.unidbg.arm.backend.Unicorn2Backend$11.hook(Unicorn2Backend.java:347)
	at com.github.unidbg.arm.backend.unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:109)
	at com.github.unidbg.arm.backend.unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.unicorn.Unicorn.emu_start(Unicorn.java:312)
	at com.github.unidbg.arm.backend.Unicorn2Backend.emu_start(Unicorn2Backend.java:384)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:383)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:343)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:316)

**Comment by ZGN16668181478** [comment]
解决了吗朋友

**Comment by tiam-bloom** [comment]
解决了吗朋友
