### ISSUE TITLE
异常报错 java.lang.IllegalStateException: svc number: 14

### ISSUE THREAD

**Issue by georgeJzzz** [zhkl0228/unidbg#524]
报错信息如下：
```sh
[18:23:44 088]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:532) - handleInterrupt intno=2, NR=192, svcNumber=0xe, PC=RX@0x4001aaea[libdusanwa.so]0x1aaea, LR=RX@0x4001aad7[libdusanwa.so]0x1aad7, syscall=null
java.lang.IllegalStateException: svc number: 14
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:135)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.Function32.run(Function32.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:229)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:262)
	at com.js.dewusdk.callheracles(dewusdk.java:104)
	at com.js.dewusdk.main(dewusdk.java:67)
[18:23:44 097]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:420) - emulate RX@0x400274f9[libdusanwa.so]0x274f9 exception sp=unidbg@0xbfffee8c, msg=svc number: 14, offset=112ms
Exception in thread "main" java.lang.NullPointerException
```

当前的开发环境如下
```sh
root@ubuntu:~# uname -a
Linux ubuntu 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~# 
````

看到有类似的大大 ，麻烦帮看下，谢谢

**Comment by jdxhu** [comment]
同求！！！
