### ISSUE TITLE
Please help its giving this error all the time

### ISSUE THREAD

**Issue by TrilochanSati** [zhkl0228/unidbg#540]
Exception in thread "main" java.lang.IllegalStateException: java.io.FileNotFoundException: /Users/badhra/Reverse%20Eng/unidbg-0.9.7/unidbg-android/target/classes/android/sdk23/lib/liblog.so (No such file or directory)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:190)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:62)
	at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:233)
	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:312)
	at org.telegram.messenger.Utilities32.<init>(Utilities32.java:57)
	at org.telegram.messenger.Utilities32.main(Utilities32.java:82)

**Comment by 0xjacklove** [comment]
(No such file or directory)

**Comment by TrilochanSati** [comment]
<img width="1440" alt="Screenshot 2023-05-05 at 11 19 29 AM" src="https://user-images.githubusercontent.com/43339728/236385615-c5cc7652-0875-48f8-9fd5-bcce2487da1a.png">
All the files are their but still giving me this error.

**Comment by csisoap** [comment]
Try rename your Reverse Eng folder without space.
