### ISSUE TITLE
backend.dynarmic.Dynarmic.context_alloc(J)J 报错

### ISSUE THREAD

**Issue by Alphamerry** [zhkl0228/unidbg#543]
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.github.unidbg.arm.backend.dynarmic.Dynarmic.context_alloc(J)J
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.context_alloc(Native Method)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.context_alloc(Dynarmic.java:55)
	at com.github.unidbg.arm.backend.DynarmicBackend.context_alloc(DynarmicBackend.java:195)
	at com.github.unidbg.thread.BaseTask.saveContext(BaseTask.java:59)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:184)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:52)
	at com.anjuke.mobile.sign.SignUtil.getSign0(SignUtil.java:306)
	at com.anjuke.mobile.sign.SignUtil.main(SignUtil.java:383)
在Issues中找到一个同样问题的#420 ，有人说是dynarmic.dll这个库没更新，导致新接口context_alloc找不到,我打印了一下这个DLL的导出函数，好像真的没有，这个能更新一下吗？或者说我自己怎么能更新呢？谢谢  
![dy](https://github.com/zhkl0228/unidbg/assets/133935849/0d33b001-a14d-46fb-9e60-3c777f0ce80b)

**Comment by Alphamerry** [comment]
解决了，从realse区下载的源码，那个DLL是旧的，从code区下载新的就可以了。
