### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by fyfyfy982** [zhkl0228/unidbg#549]
JNIEnv->NewStringUTF("0b2cf7ed7b925696de4b5c4dd129b18d9933ce2f9eac3b6b12eba8e86a2c9de11e") was called from RX@0x40008470[libxtoken.so]0x8470
函数最后一步字符串都new出来了但是我用Number number =dm.getModule().callFunction(emulator, 0x83a4, list.toArray());
        System.out.println("================================================");
        String result = (String) vm.getObject(number.intValue()).getValue();
获取返回值会报错
Exception in thread "main" java.lang.NullPointerException
	at com.kanxue.test2.XTokenServer.getXtoken(XTokenServer.java:239)
	at com.kanxue.test2.XTokenServer.main(XTokenServer.java:290)
我打印了number.intValue()发现是-1这是为什么

**Comment by fyfyfy982** [comment]
最新的master版本
