### ISSUE TITLE
/ by zero

### ISSUE THREAD

**Issue by google-mirror** [zhkl0228/unidbg#562]
https://github.com/fornwall/jelf/issues/21

```
[15:33:56 429]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:317) - loadInternal /system/lib64/liblog.so
[15:33:56 437]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:317) - loadInternal /system/lib64/libc++.so
[15:33:56 475]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:317) - loadInternal /system/lib64/libc.so
[15:33:56 544]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:317) - loadInternal /system/lib64/ld-android.so
[15:33:56 550]  INFO [com.github.unidbg.linux.AndroidElfLoader] (AndroidElfLoader:317) - loadInternal /system/lib64/libdl.so
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at net.fornwall.jelf.ElfDynamicStructure.<init>(ElfDynamicStructure.java:315)
	at net.fornwall.jelf.ElfSegment$3.computeValue(ElfSegment.java:153)
	at net.fornwall.jelf.ElfSegment$3.computeValue(ElfSegment.java:150)
	at net.fornwall.jelf.MemoizedObject.getValue(MemoizedObject.java:21)
	at net.fornwall.jelf.ElfSegment.getDynamicStructure(ElfSegment.java:255)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:435)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:478)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:478)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:478)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:478)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:478)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:175)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:63)
	at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:237)
	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:239)
```

**Comment by joshuachenn** [comment]
vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7/libc.so"),false);

**Comment by google-mirror** [comment]
> vm.loadLibrary(new File("unidbg-android/src/test/resources/example_binaries/armeabi-v7/ld-android.so"),false);

不是这个问题, 样本如下

[libc.zip](https://github.com/fornwall/jelf/files/12546686/libc.zip)
[libdl.zip](https://github.com/fornwall/jelf/files/12594752/libdl.zip)

**Comment by wxl2578** [comment]
这个问题有方案了吗

**Comment by google-mirror** [comment]
> 这个问题有方案了吗

已解决

**Comment by funaihui** [comment]
> > 这个问题有方案了吗
> 
> 已解决

怎么解决的呀，我也遇到这个了

**Comment by alex223232321** [comment]
怎么解决的，能提供解决方案吗？

**Comment by thouger** [comment]
> > 这个问题有方案了吗
> 
> 已解决

国人经典自己只提问解决完之后就不放出方案

**Comment by thouger** [comment]
debugger一下，我发现libc.so 解析的时候，
```
ElfSegment ph = elfFile.getProgramHeader(i);
            System.out.println(ph.type);
```
这里的第三个2，pltRelOffset > 0这里为2064，而d_val_or_ptr这里又没有 19，导致了relEntrySize变量为空
```
loop: for (int i = 0; i < numEntries; i++) {
			long d_tag = parser.readIntOrLong();
			final long d_val_or_ptr = parser.readIntOrLong();
```

**Comment by thouger** [comment]
https://github.com/zhkl0228/unidbg/issues/585
