### ISSUE TITLE
java环境补完后，紧接着提示 PipedWriteFileIO 错误

### ISSUE THREAD

**Issue by cih1996** [zhkl0228/unidbg#567]
调用某so的函数后，返回null结果，错误列表中提示 java.lang.AbstractMethodError: com.github.unidbg.linux.file.PipedWriteFileIO
在issues中找到 #442 同样的错误，这个应该如何解决。。
目前使用的0.9.5版本
java.lang.AbstractMethodError: com.github.unidbg.linux.file.PipedWriteFileIO
	at com.github.unidbg.file.AbstractFileIO.dup2(AbstractFileIO.java:160)
	at com.github.unidbg.linux.ARM32SyscallHandler.dup3(ARM32SyscallHandler.java:2086)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:438)
	at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
	at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend32.callSVC(DynarmicBackend32.java:32)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:61)
	at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:76)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:370)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:446)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:220)
	at com.github.unidbg.Module.emulateFunction(Module.java:158)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:133)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:292)
	at com.example.qqpayserver.service.unidbg.PddEncrypt.pddInfo3(PddEncrypt.java:161)
	at com.example.qqpayserver.service.unidbg.PddEncrypt.main(PddEncrypt.java:34)

![image](https://github.com/zhkl0228/unidbg/assets/27680901/8cf940c1-0400-46c7-9538-51cfd637d00d)
![image](https://github.com/zhkl0228/unidbg/assets/27680901/86628fb7-a7a4-4eeb-8b15-74888b04120a)

**Comment by cih1996** [comment]
已自行解决，正好看雪的某个大佬也在研究同样的事情，在创建虚拟机的时候，添加对 Syscall的处理即可
AndroidEmulatorBuilder androidEmulatorBuilder = new AndroidEmulatorBuilder(false) {
            @Override
            public AndroidEmulator build() {
                return new AndroidARMEmulator("com.xunmeng.pinduoduo",rootDir,backendFactories) {
                    @Override
                    protected UnixSyscallHandler<AndroidFileIO> createSyscallHandler(SvcMemory svcMemory) {
                        return new PddArmSysCallHand(svcMemory);
                    }
                };
            }
        };




public class PddArmSysCallHand extends com.github.unidbg.linux.ARM32SyscallHandler {
    public PddArmSysCallHand(SvcMemory svcMemory) {
        super(svcMemory);
    }
    @Override
    protected boolean handleUnknownSyscall(Emulator emulator, int NR) {
        switch (NR) {
            case 190:
                vfork(emulator);
                return true;
            case 359:
                pipe2(emulator);
                return true;
        }

        return super.handleUnknownSyscall(emulator, NR);
    }
    private void vfork(Emulator<?> emulator) {
        EditableArm32RegisterContext context = (EditableArm32RegisterContext) emulator.getContext();
        int childPid = emulator.getPid() + ThreadLocalRandom.current().nextInt(256);
        int r0 = 0;
        r0 = childPid;
        System.out.println("vfork pid=" + r0);
        context.setR0(r0);
    }


    @Override
    protected int pipe2(Emulator<?> emulator) {
        EditableArm32RegisterContext context = (EditableArm32RegisterContext) emulator.getContext();
        Pointer pipefd = context.getPointerArg(0);
        int flags = context.getIntArg(1);
        int write = getMinFd();
        this.fdMap.put(write, new DumpFileIO(write));
        int read = getMinFd();
        String stdout = "d29d36c7-df12-461f-96d7-c0804cb9686e\n";
        this.fdMap.put(read, new ByteArrayFileIO(0, "pipe2_read_side", stdout.getBytes()));
        pipefd.setInt(0, read);
        pipefd.setInt(4, write);
        System.out.println("pipe2 pipefd=" + pipefd + ", flags=0x" + flags + ", read=" + read + ", write=" + write + ", stdout=" + stdout);
        context.setR0(0);
        return 0;
    }

}

**Comment by sanqudui8ban** [comment]
真棒
