### ISSUE TITLE
 大佬，请问一下这应该怎么改

### ISSUE THREAD

**Issue by joobih** [zhkl0228/unidbg#578]
[10:33:13 939] DEBUG [com.github.unidbg.pointer.UnidbgPointer] (UnidbgPointer:348) - getString pointer=RX@0x4063a629[libqlustre_v++.so]0xfa629, size=17, encoding=UTF-8, ret=/proc/self/status
[10:33:13 940] DEBUG [com.github.unidbg.pointer.UnidbgPointer] (UnidbgPointer:348) - getString pointer=RX@0x4063d0e9[libqlustre_v++.so]0xfd0e9, size=0, encoding=UTF-8, ret=
fopen 1=/proc/self/status
fopen 2=
[10:33:13 940] DEBUG [com.github.unidbg.pointer.UnidbgPointer] (UnidbgPointer:348) - getString pointer=RX@0x4063a629[libqlustre_v++.so]0xfa629, size=17, encoding=UTF-8, ret=/proc/self/status
fopen=, ret=0
[10:33:13 941] DEBUG [com.github.unidbg.pointer.UnidbgPointer] (UnidbgPointer:348) - getString pointer=unidbg@0xbfffeda8, size=0, encoding=UTF-8, ret=
fgets 1=
fgets 2=1024
[10:33:13 941]  WARN [com.github.unidbg.arm.AbstractARM64Emulator] (AbstractARM64Emulator$1:66) - Read memory failed: address=0x58, size=8, value=0x0
[10:33:13 941]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:420) - emulate RX@0x40637304[libqlustre_v++.so]0xf7304 exception sp=unidbg@0xbfffed00, msg=unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED), offset=242ms
[10:33:13 941] DEBUG [com.github.unidbg.thread.UniThreadDispatcher] (UniThreadDispatcher:177) - End dispatch task=Runnable|Function64 address=0x40637304, arguments=[unidbg@0xfffe1640, 0, 1344199921, 10003], ret=-1
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.github.unidbg.linux.android.dvm.DvmObject.getValue()" because the return value of "com.github.unidbg.linux.android.dvm.VM.getObject(int)" is null
	at qunar.Qlustre_v.call_cd(Qlustre_v.java:326)
	at qunar.Qlustre_v.main(Qlustre_v.java:279)

**Comment by HappyTsing** [comment]
+1，楼主解决了吗
