### ISSUE TITLE
Exception in thread "main" java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by funaihui** [zhkl0228/unidbg#585]
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at net.fornwall.jelf.ElfDynamicStructure.<init>(ElfDynamicStructure.java:315)
	at net.fornwall.jelf.ElfSegment$3.computeValue(ElfSegment.java:153)
	at net.fornwall.jelf.ElfSegment$3.computeValue(ElfSegment.java:150)
	at net.fornwall.jelf.MemoizedObject.getValue(MemoizedObject.java:21)
	at net.fornwall.jelf.ElfSegment.getDynamicStructure(ElfSegment.java:252)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:427)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:470)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:470)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:470)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:470)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:174)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:62)
	at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:237)
	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:315)

**Comment by chaodchen** [comment]
这个大概是环境问题 建议使用VM createDalvikVM(File apkFile);和DalvikModule loadLibrary(String libname, boolean forceCallInit);来创建虚拟机和加载so

**Comment by berkedel** [comment]
@funaihui try to change the library resolver to android resolver version 23

**Comment by AXiX-official** [comment]
遇到了同样的问题
```java
        //创建模拟器
        emulator = AndroidEmulatorBuilder
                .for64Bit()
                .addBackendFactory(new Unicorn2Factory(true))
                .setProcessName("com.example.antiollvm")
                .build();
        Memory memory = emulator.getMemory();
        //设置andorid系统库版本
        memory.setLibraryResolver(new AndroidResolver(33));
        //创建虚拟机
        vm = emulator.createDalvikVM(new File("f:\\workspace\\hbr\\132831.apk"));
        vm.setVerbose(false);
        vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\ld-android.so"),false);
        vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\libc.so"),false);
        vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\libm.so"),false);
        vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\libstdc++.so"),false);
        vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\libdl.so"),false);
        //加载动态库
        dm = vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\libtprt.so"), false);
        module = dm.getModule();
```
是在加载libc.so和后面三个so的时候出现的，这些so都是从真机环境获取的。前面提到的方式似乎不能解决问题。

**Comment by thouger** [comment]
> ```java
> android
> ```

我也遇到同样的问题

**Comment by thouger** [comment]
> 遇到了同样的问题
> 
> ```java
>         //创建模拟器
>         emulator = AndroidEmulatorBuilder
>                 .for64Bit()
>                 .addBackendFactory(new Unicorn2Factory(true))
>                 .setProcessName("com.example.antiollvm")
>                 .build();
>         Memory memory = emulator.getMemory();
>         //设置andorid系统库版本
>         memory.setLibraryResolver(new AndroidResolver(33));
>         //创建虚拟机
>         vm = emulator.createDalvikVM(new File("f:\\workspace\\hbr\\132831.apk"));
>         vm.setVerbose(false);
>         vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\ld-android.so"),false);
>         vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\libc.so"),false);
>         vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\libm.so"),false);
>         vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\libstdc++.so"),false);
>         vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\libdl.so"),false);
>         //加载动态库
>         dm = vm.loadLibrary(new File("f:\\workspace\\hbr\\antiollvm\\libtprt.so"), false);
>         module = dm.getModule();
> ```
> 
> 是在加载libc.so和后面三个so的时候出现的，这些so都是从真机环境获取的。前面提到的方式似乎不能解决问题。

我也遇到同样的问题

**Comment by thouger** [comment]
解决了，方案就是哪个 so 出的问题就把它注释了

**Comment by FBLeee** [comment]
> 解决了，方案就是用这种vm.loadLibrary方案导入 so 是不行的，要用AndroidModule类这种方法

请问有示例吗，没找到相关资料。。
