### ISSUE TITLE
getIFaceFlags: tun0 这个应该怎么搞

### ISSUE THREAD

**Issue by byxuanmai** [zhkl0228/unidbg#600]
java.lang.UnsupportedOperationException: getIFaceFlags: tun0
	at com.github.unidbg.linux.file.UdpSocket.getIFaceFlags(UdpSocket.java:247)
	at com.github.unidbg.linux.file.UdpSocket.ioctl(UdpSocket.java:185)
	at com.github.unidbg.linux.ARM64SyscallHandler.ioctl(ARM64SyscallHandler.java:1410)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:156)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:316)

**Comment by eachlove** [comment]
第一个点进去 throw 注释掉 return -1
