### ISSUE TITLE
怎么重写读取目录下所有文件的io

### ISSUE THREAD

**Issue by bbbydz** [zhkl0228/unidbg#621]
class=class com.github.unidbg.linux.file.DirectoryFileIO, offset=0x0, whence=0, path=
com.github.unidbg.file.AbstractFileIO.lseek(AbstractFileIO.java:109)

java.lang.AbstractMethodError: class=class com.github.unidbg.linux.file.DirectoryFileIO, offset=0x0, whence=0, path=
	at com.github.unidbg.file.AbstractFileIO.lseek(AbstractFileIO.java:109)
	at com.github.unidbg.linux.ARM64SyscallHandler.lseek(ARM64SyscallHandler.java:1459)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:150)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)

路径是空

**Comment by juedi998** [comment]
解决了嘛？我也遇到同一个问题
