### ISSUE TITLE
运行报错DalvikVM64$128.handle，怎么解决呀 

### ISSUE THREAD

**Issue by Phoebe-xylon** [zhkl0228/unidbg#623]
报错内容如下，该如何解决
`java.lang.UnsupportedOperationException
	at com.github.unidbg.linux.android.dvm.DalvikVM64$128.handle(DalvikVM64.java:2059)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:121)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:378)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:341)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:262)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:316)`

**Comment by phpwzy** [comment]
你好 我遇到了与您相同的问题，请问您是如何解决这个问题的？

**Comment by Phoebe-xylon** [comment]
> 你好 我遇到了与您相同的问题，请问您是如何解决这个问题的？

前面的补环境补的不对，抛出了异常
