### ISSUE TITLE
运行其他示例正常，运行anjuke示例报错了，用了unidbg-0.9.7

### ISSUE THREAD

**Issue by guochengwei111** [zhkl0228/unidbg#625]
`[20:55:51 584]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:533) - handleInterrupt intno=2, NR=-1073744136, svcNumber=0x12d, PC=unidbg@0xfffe0364, LR=RX@0x40001c05[libsignutil.so]0x1c05, syscall=null
java.lang.IllegalStateException: Please vm.setJni(jni)
	at com.github.unidbg.linux.android.dvm.Hashable.checkJni(Hashable.java:8)
	at com.github.unidbg.linux.android.dvm.DvmMethod.callIntMethod(DvmMethod.java:129)
	at com.github.unidbg.linux.android.dvm.DalvikVM$46.handle(DalvikVM.java:795)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:132)
	at com.github.unidbg.arm.backend.UnicornBackend$11.hook(UnicornBackend.java:345)
	at unicorn.Unicorn$NewHook.onInterrupt(Unicorn.java:128)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.arm.backend.UnicornBackend.emu_start(UnicornBackend.java:376)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.Function32.run(Function32.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:172)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:96)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:229)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:316)
	at com.anjuke.mobile.sign.SignUtil.getSign0(SignUtil.java:58)
	at com.anjuke.mobile.sign.SignUtil.sign(SignUtil.java:67)
	at com.anjuke.mobile.sign.SignUtil.main(SignUtil.java:82)
[20:55:51 588]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:420) - emulate RX@0x40001bad[libsignutil.so]0x1bad exception sp=unidbg@0xbffff688, msg=Please vm.setJni(jni), offset=7ms
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.github.unidbg.linux.android.dvm.StringObject.getValue()" because "obj" is null
	at com.anjuke.mobile.sign.SignUtil.getSign0(SignUtil.java:59)
	at com.anjuke.mobile.sign.SignUtil.sign(SignUtil.java:67)
	at com.anjuke.mobile.sign.SignUtil.main(SignUtil.java:82)`

**Comment by guochengwei111** [comment]
java -version
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)

**Comment by 2666fff** [comment]
你会java不, 看报错原因, 就在最下面.

**Comment by guochengwei111** [comment]
啊对对对，你说的对

**Comment by airqj** [comment]
> java -version java version "1.8.0_371" Java(TM) SE Runtime Environment (build 1.8.0_371-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)

java 11 worked

**Comment by phantomseeds** [comment]
java.lang.IllegalStateException: Please vm.setJni(jni)
```
vm.setJni(jni)
```
在创建虚拟机时 `vm.setJni` 设置一下
