### ISSUE TITLE
大佬们这个环境要咋补呢，init方法它没得返回值，必然会调用callVoidMethod这个方法，这个方法只有一个出路就是抛出异常

### ISSUE THREAD

**Issue by liuliang520530** [zhkl0228/unidbg#633]
java.lang.UnsupportedOperationException: javax/crypto/Cipher->init(ILjava/security/Key;Ljava/security/spec/AlgorithmParameterSpec;)V
at com.github.unidbg.linux.android.dvm.AbstractJni.callVoidMethod(AbstractJni.java:985)
at com.github.unidbg.linux.android.dvm.AbstractJni.callVoidMethod(AbstractJni.java:980)

**Comment by ddzgy** [comment]
点这里 改源码
at com.github.unidbg.linux.android.dvm.AbstractJni.callVoidMethod(AbstractJni.java:985)
