### ISSUE TITLE
调用callStaticJniMethod出现UC_ERR_FETCH_UNMAPPED

### ISSUE THREAD

**Issue by whenxx** [zhkl0228/unidbg#64]
`unicorn.UnicornException: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:366)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:203)
	at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:189)`

`debugger break at: 0x2b0 `

 `r0=0xfffe0950 r1=0x1 r2=0x76f84423, r3=0x83d61724 r4=0xfffe0950 r5=0x46607d73 r6=0x76f84423 r7=0xbfffeff0 r8=0x608da06e r9=0xd8355a8 r10=0x4e4e3b1c fp=0x83d61724 ip=0x2b0 sp=0xbfffef78 lr=0x4025f815 pc=0x2b0 cpsr: N=0, Z=0, C=1, V=0, T=0, mode=0b10000
`

#48、#20 提到过，但是好像没有解决

请问下作者 ，这个错误应该怎么做呢

**Comment by zhkl0228** [comment]
发测试用例跟相关so文件

**Comment by whenxx** [comment]
已发邮箱

**Comment by zhkl0228** [comment]
已经提交了0x2b0的实现

**Comment by whenxx** [comment]
可以了，但是运行后修复了其他错误又出现了`0x210`

`unicorn.UnicornException: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:366)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:203)
	at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:189)
	at TestSignso.test(TestSignso.java:331)
	at TestSignso.main(TestSignso.java:223)`

`debugger break at: 0x210`

`r0=0xfffe0960 r1=0x5e82b3f8 r2=0x9fd971d2, r3=0x210 r4=0x0 r5=0x8067ab8 r6=0xbffff2f8 r7=0xbffff2f0 r8=0x39 r9=0xbffff440 r10=0xa8 fp=0xbffff700 ip=0xfb sp=0xbffff2e0 lr=0x4024fd11 pc=0x210 cpsr: N=0, Z=1, C=1, V=0, T=0, mode=0b10000
unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)`

代码已发邮箱

**Comment by zhkl0228** [comment]
已经提交0x210的实现
