### ISSUE TITLE
没有对 SocketIO.SOCK_RAW 进行模拟

### ISSUE THREAD

**Issue by HappyTsing** [zhkl0228/unidbg#647]
```java
// ARM32SyscallHandler.java
private int socket(Backend backend, Emulator<?> emulator) {

        int fd;
        switch (domain) {
            case SocketIO.AF_UNSPEC:
                throw new UnsupportedOperationException();
				// ...
            case SocketIO.AF_NETLINK:
                switch (type) {
                    case SocketIO.SOCK_DGRAM:
                        fd = getMinFd();
                        fdMap.put(fd, new NetLinkSocket(emulator)); 
                        return fd;
                    case SocketIO.SOCK_RAW:
                    default:
                        throw new UnsupportedOperationException(); // Here line 1585
                }
        }
```
这里没有对 SocketIO.SOCK_RAW 的 case 进行实现，导致报错。
```
[14:19:40 536] DEBUG [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:1537) - socket domain=16, type=3, protocol=0
[14:19:40 536]  WARN [com.github.unidbg.linux.ARM32SyscallHandler] (ARM32SyscallHandler:546) - handleInterrupt intno=2, NR=281, svcNumber=0x0, PC=RX@0x402cba98[libc.so]0x40a98, LR=RX@0x401bd050[libpdd_secure.so]0x1bd050, syscall=null
java.lang.UnsupportedOperationException
	at com.github.unidbg.linux.ARM32SyscallHandler.socket(ARM32SyscallHandler.java:1585)
	at com.github.unidbg.linux.ARM32SyscallHandler.hook(ARM32SyscallHandler.java:438)
```

**Comment by 3859** [comment]
老哥，解决了吗 ，我也遇到了相同的问题，不知道如何决绝
