### ISSUE TITLE
UnsupportedOperationException option=16 报错

### ISSUE THREAD

**Issue by whenxx** [zhkl0228/unidbg#66]
`java.lang.UnsupportedOperationException: option=16
 at cn.banny.unidbg.linux.ARMSyscallHandler.prctl(ARMSyscallHandler.java:1361)
 at cn.banny.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:252)
 at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
 at unicorn.Unicorn.emu_start(Native Method)
 at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)`

运行so抛出这个异常

代码已发您邮箱

**Comment by zhkl0228** [comment]
StackTraceElementObject的定义还没发我

**Comment by zhkl0228** [comment]
option=16已实现，pull最新代码

**Comment by whenxx** [comment]
可以了，但是又出现了新的错误

`java.lang.AbstractMethodError: cn.banny.unidbg.unix.file.UdpSocket: request=0x8912, argp=0xbfffebb0
 at cn.banny.unidbg.file.AbstractFileIO.ioctl(AbstractFileIO.java:66)
 at cn.banny.unidbg.linux.ARMSyscallHandler.ioctl(ARMSyscallHandler.java:1707)
 at cn.banny.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:163)`
