### ISSUE TITLE
java.lang.UnsupportedOperationException : _CallCharMethodA 

### ISSUE THREAD

**Issue by littXu** [zhkl0228/unidbg#678]
执行时候_CallCharMethodA异常，主动抛出的，这样的我应该怎么去补环境呢？
异常日志如下：
[15:14:19 980]  WARN [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:399) - handleInterrupt intno=2, NR=-130176, svcNumber=0x12f, PC=unidbg@0xfffe0384[libandroid.so]0x384, LR=RX@0x4004edb8[libdexjni.so]0x4edb8, syscall=null
java.lang.UnsupportedOperationException
	at com.github.unidbg.linux.android.dvm.DalvikVM64$42.handle(DalvikVM64.java:699)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:118)
	at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
	at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend64.callSVC(DynarmicBackend64.java:32)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:78)
	at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:82)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:380)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:236)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:317)

**Comment by nihaomayx** [comment]
问题解决了吗
