### ISSUE TITLE
getAllNetworks() Problem

### ISSUE THREAD

**Issue by 123edi10** [zhkl0228/unidbg#689]
The JNI function check the network but there not built-in class for this.
What can I do?

My solution :
`return vm.resolveClass("android/net/Network").newObject(null);`

Logs:
`JNIEnv->CallObjectMethodV(android.net.ConnectivityManager@36bc55de, getAllNetworks() => android.net.Network@564fabc8) was called from RX@0x12045cec[libscplugin.so]0x45cec
[15:48:08 409]  WARN [com.github.unidbg.linux.ARM64SyscallHandler] (ARM64SyscallHandler:410) - handleInterrupt intno=2, NR=-128368, svcNumber=0x1a0, PC=unidbg@0xfffe0a94, LR=RX@0x12065264[libscplugin.so]0x65264, syscall=null
java.lang.ClassCastException: class com.github.unidbg.linux.android.dvm.DvmObject cannot be cast to class com.github.unidbg.linux.android.dvm.Array (com.github.unidbg.linux.android.dvm.DvmObject and com.github.unidbg.linux.android.dvm.Array are in unnamed module of loader 'app')
	at com.github.unidbg.linux.android.dvm.DalvikVM64$161.handle(DalvikVM64.java:2648)
	at com.github.unidbg.linux.ARM64SyscallHandler.hook(ARM64SyscallHandler.java:119)
	at com.github.unidbg.arm.backend.InterruptHookNotifier.notifyCallSVC(InterruptHookNotifier.java:14)
	at com.github.unidbg.arm.backend.dynarmic.DynarmicBackend64.callSVC(DynarmicBackend64.java:32)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Native Method)
	at com.github.unidbg.arm.backend.dynarmic.Dynarmic.emu_start(Dynarmic.java:78)
	at com.github.unidbg.arm.backend.DynarmicBackend.emu_start(DynarmicBackend.java:82)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:378)
	at com.github.unidbg.thread.Function64.run(Function64.java:39)
	at com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:165)
	at com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:97)
	at com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:341)
	at com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:262)
	at com.github.unidbg.Module.emulateFunction(Module.java:163)
	at com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethodObject(DvmClass.java:316)
	at com.test.test.test.<init>(Test.java:63)
	at com.test.test.test.main(Test.java:35)
[15:48:08 411]  WARN [com.github.unidbg.AbstractEmulator] (AbstractEmulator:417) - emulate RX@0x120457e4[libscplugin.so]0x457e4 exception sp=unidbg@0xe4ffada0, msg=class com.github.unidbg.linux.android.dvm.DvmObject cannot be cast to class com.github.unidbg.linux.android.dvm.Array (com.github.unidbg.linux.android.dvm.DvmObject and com.github.unidbg.linux.android.dvm.Array are in unnamed module of loader 'app'), offset=364ms @ Runnable|Function64 address=0x120457e4, arguments=[unidbg@0xfffe1640[libjnigraphics.so]0x640, -1224627949, 521960438, 632587706]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.github.unidbg.lin`

**Comment by jalee0606** [comment]
You supposed to return an array instead of an DvmObject.

`return new ArrayObject()`

If you want to emulate the output of your device, then you put in some DvmObject[] as argument.

**Comment by 123edi10** [comment]
Thank you
