### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by HandsomeXi** [zhkl0228/unidbg#72]
java.lang.NegativeArraySizeException: -2157
       at cn.banny.unidbg.linux.file.SimpleFileIO.read(SimpleFileIO.java:100)
       at cn.banny.unidbg.unix.UnixSyscallHandler.read(UnixSyscallHandler.java:139)
       at cn.banny.unidbg.linux.ARMSyscallHandler.read(ARMSyscallHandler.java:1729)
       at cn.banny.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:112)
       at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
       at unicorn.Unicorn.emu_start(Native Method)
       at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:272)
       at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:371)
       at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
       at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:205)
       at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:191)

请问count 为负数怎么解决呢？

**Comment by zhkl0228** [comment]
测试用例发上来

**Comment by HandsomeXi** [comment]
http://t.cn/AiDPsRf2
apk文件未签名。
麻烦您了。

**Comment by zhkl0228** [comment]
bug已修复
