### ISSUE TITLE
java.lang.UnsupportedOperationException: signum=7

### ISSUE THREAD

**Issue by onegithuber** [zhkl0228/unidbg#80]
java.lang.UnsupportedOperationException: signum=7
	at cn.banny.unidbg.unix.UnixSyscallHandler.sigaction(UnixSyscallHandler.java:254)
	at cn.banny.unidbg.linux.ARMSyscallHandler.sigaction(ARMSyscallHandler.java:1073)
	at cn.banny.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:171)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:48)
	at com.grab.Xray.burn(Xray.java:66)
	at com.grab.Xray.main(Xray.java:58)
[15:59:11 282]  WARN [cn.banny.unidbg.linux.android.dvm.DalvikVM] (DalvikVM$2:61) - Throw object=unicorn@0x17c68925, dvmObject=StringObject{value=Success}, class=java/lang/String
unicorn.UnicornException: Invalid memory read (UC_ERR_READ_UNMAPPED)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:267)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:360)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:201)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:154)
	at cn.banny.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:48)
	at com.grab.Xray.burn(Xray.java:66)
	at com.grab.Xray.main(Xray.java:58)

**Comment by zhkl0228** [comment]
测试用例发来测试

**Comment by onegithuber** [comment]
发你邮箱了
