### ISSUE TITLE
signum=7不支持问题，想请教下是为什么

### ISSUE THREAD

**Issue by DemonKwong** [zhkl0228/unidbg#81]
signum=7不支持问题，想请教下是为什么

一月 07, 2020 5:25:27 下午 cn.banny.unidbg.linux.ARMSyscallHandler pthread_clone
信息: pthread_clone child_stack=unicorn@0x4083e930, thread_id=5, fn=unicorn@0x4019e7f5[libc.so]0x3f7f5, arg=unicorn@0x4083e930, flags=[CLONE_VM, CLONE_FS, CLONE_FILES, CLONE_SIGHAND, CLONE_THREAD, CLONE_SYSVSEM, CLONE_SETTLS, CLONE_PARENT_SETTID, CLONE_CHILD_CLEARTID]
一月 07, 2020 5:25:27 下午 cn.banny.unidbg.linux.ARMSyscallHandler hook
警告: handleInterrupt intno=2, NR=67, svcNumber=0x0, PC=unicorn@0x401a02a4[libc.so]0x412a4, syscall=null
java.lang.UnsupportedOperationException: signum=7
	at cn.banny.unidbg.unix.UnixSyscallHandler.sigaction(UnixSyscallHandler.java:297)
	at cn.banny.unidbg.linux.ARMSyscallHandler.sigaction(ARMSyscallHandler.java:1116)
	at cn.banny.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:179)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at cn.banny.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:302)
	at cn.banny.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:400)
	at cn.banny.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:202)
	at cn.banny.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:203)
	at cn.banny.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:209)
![image](https://user-images.githubusercontent.com/19722515/71884276-f5e9e280-3172-11ea-94eb-5b9eac1be716.png)

**Comment by zhkl0228** [comment]
需要测试用例
