### ISSUE TITLE
大佬求解答 三个WARN，最后执行完方法返回值为NULL

### ISSUE THREAD

**Issue by liurenqiu520** [zhkl0228/unidbg#93]
[18:17:23 425]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1662) - openat dirfd=-100, pathname=/proc/self/exe, oflags=0x0, mode=0
[18:17:23 435]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/proc/81488/fd/3, oflags=0x0, mode=0
[18:17:23 442]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:415) - handleInterrupt intno=2, NR=67, svcNumber=0x0, PC=RX@0x4000b818[libcms.so]0xb818, syscall=null
java.lang.UnsupportedOperationException: signum=32
	at com.github.unidbg.unix.UnixSyscallHandler.sigaction(UnixSyscallHandler.java:304)
	at com.github.unidbg.linux.ARMSyscallHandler.sigaction(ARMSyscallHandler.java:1150)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:196)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:344)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:435)
	at com.github.unidbg.arm.AbstractARMEmulator.eInit(AbstractARMEmulator.java:215)
	at com.github.unidbg.linux.AbsoluteInitFunction.call(AbsoluteInitFunction.java:38)
	at com.github.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:95)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:167)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:30)
	at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:237)
	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:298)
	at com.ss.sys.ces.Gorgon.<init>(Gorgon.java:36)
	at com.ss.sys.ces.Gorgon.main(Gorgon.java:49)
[18:17:23 453]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:415) - handleInterrupt intno=2, NR=172, svcNumber=0x0, PC=RX@0x4000b818[libcms.so]0xb818, syscall=null
java.lang.UnsupportedOperationException: option=3
	at com.github.unidbg.linux.ARMSyscallHandler.prctl(ARMSyscallHandler.java:1437)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:274)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:344)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:435)
	at com.github.unidbg.arm.AbstractARMEmulator.eInit(AbstractARMEmulator.java:215)
	at com.github.unidbg.linux.AbsoluteInitFunction.call(AbsoluteInitFunction.java:38)
	at com.github.unidbg.linux.LinuxModule.callInitFunction(LinuxModule.java:95)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:167)
	at com.github.unidbg.linux.AndroidElfLoader.loadInternal(AndroidElfLoader.java:30)
	at com.github.unidbg.spi.AbstractLoader.load(AbstractLoader.java:237)
	at com.github.unidbg.linux.android.dvm.BaseVM.loadLibrary(BaseVM.java:298)
	at com.ss.sys.ces.Gorgon.<init>(Gorgon.java:36)
	at com.ss.sys.ces.Gorgon.main(Gorgon.java:49)
[18:17:23 466]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/xbin/bbksu, oflags=0x0, mode=0
[18:17:23 467]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/bin/shuamesu, oflags=0x0, mode=0
[18:17:23 467]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/bin/bdsu, oflags=0x0, mode=0
[18:17:23 468]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/xbin/bdsu, oflags=0x0, mode=0
[18:17:23 468]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/su/bin/su, oflags=0x0, mode=0
[18:17:23 468]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/bin/.su, oflags=0x0, mode=0
[18:17:23 469]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/xbin/ku.sud, oflags=0x0, mode=0
[18:17:23 469]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/xbin/bstk/su, oflags=0x0, mode=0
[18:17:23 469]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/bin/sudo, oflags=0x0, mode=0
[18:17:23 470]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/bin/sutemp, oflags=0x0, mode=0
[18:17:23 470]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/sbin/su, oflags=0x0, mode=0
[18:17:23 470]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/bin/su, oflags=0x0, mode=0
[18:17:23 471]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/xbin/su, oflags=0x0, mode=0
[18:17:23 472]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1600) - faccessat dirfd=-100, pathname=/system/xbin/daemonsu, oflags=0x0, mode=0
[18:17:23 473]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:919) - stat64 pathname=/data/data/com.topjohnwu.magisk
[18:17:23 477]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:919) - stat64 pathname=/data/data/com.cyjh.mobileanjian
[18:17:23 479]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:919) - stat64 pathname=/data/data/com.touchsprite.android
[18:17:23 481]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:919) - stat64 pathname=/data/data/net.aisence.Touchelper
[18:17:23 482]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:919) - stat64 pathname=/dev/input/event0
[18:17:23 576]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1662) - openat dirfd=-100, pathname=/proc/self/cmdline, oflags=0x0, mode=0
[18:17:23 578]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1662) - openat dirfd=-100, pathname=/proc/self/cmdline, oflags=0x0, mode=0
[18:17:23 579]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1670) - openat dirfd=-100, pathname=, oflags=0x42, mode=1a0
[18:17:23 580]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1662) - openat dirfd=-100, pathname=/proc/self/cmdline, oflags=0x0, mode=0
[18:17:23 584]  INFO [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:1662) - openat dirfd=-100, pathname=/sdcard/.Y3ps, oflags=0x0, mode=0
JNIEnv->FindClass(com/ss/sys/ces/a) was called from RX@0x40002889[libcms.so]0x2889
JNIEnv->RegisterNatives(com/ss/sys/ces/a, unicorn@0xbffff520, 4) was called from RX@0x40003ff5[libcms.so]0x3ff5
RegisterNative(com/ss/sys/ces/a, meta(ILandroid/content/Context;Ljava/lang/Object;)Ljava/lang/Object;, RX@0x4006453d[libcms.so]0x6453d)
RegisterNative(com/ss/sys/ces/a, leviathan(II[B)[B, RX@0x400576dd[libcms.so]0x576dd)
RegisterNative(com/ss/sys/ces/a, decode(I[B)[B, RX@0x400249b1[libcms.so]0x249b1)
RegisterNative(com/ss/sys/ces/a, encode([B)[B, RX@0x40004451[libcms.so]0x4451)
call leviathan
Find native function Java_com_ss_sys_ces_a_leviathan(II[B)[B => RX@0x400576dd[libcms.so]0x576dd
JNIEnv->FindClass(java/lang/Thread) was called from RX@0x400155e1[libcms.so]0x155e1
[18:17:23 610]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:415) - handleInterrupt intno=2, NR=-1073744720, svcNumber=0x12b, PC=unicorn@0xfffe0344, syscall=null
java.lang.NullPointerException
	at com.github.unidbg.linux.android.dvm.DvmClass.getStaticMethodID(DvmClass.java:70)
	at com.github.unidbg.linux.android.dvm.DalvikVM$44.handle(DalvikVM.java:948)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:111)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:344)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:435)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:203)
	at com.github.unidbg.Module.emulateFunction(Module.java:155)
	at com.github.unidbg.linux.android.dvm.DvmClass.callStaticJniMethod(DvmClass.java:221)
	at com.ss.sys.ces.Gorgon.leviathan(Gorgon.java:65)
	at com.ss.sys.ces.Gorgon.main(Gorgon.java:51)
ret = 4294838832
result = null
destroy

Process finished with exit code 0

**Comment by yattin** [comment]
兄弟解决了吗，不知道为啥这里就是报啥找不到jni
