### ISSUE TITLE
直接跑Utilities32例子中间有个错误

### ISSUE THREAD

**Issue by dqzg12300** [zhkl0228/unidbg#95]
[16:23:02 525]  WARN [com.github.unidbg.linux.ARMSyscallHandler] (ARMSyscallHandler:397) - handleInterrupt intno=2, NR=0, svcNumber=0x11c, PC=unicorn@0xfffe0254[libjnigraphics.so]0x254, syscall=null
java.lang.NullPointerException
	at com.github.unidbg.linux.android.dvm.DvmClass.getFieldID(DvmClass.java:119)
	at com.github.unidbg.linux.android.dvm.DalvikVM$29.handle(DalvikVM.java:585)
	at com.github.unidbg.linux.ARMSyscallHandler.hook(ARMSyscallHandler.java:93)
	at unicorn.Unicorn.invokeInterruptCallbacks(Unicorn.java:123)
	at unicorn.Unicorn.emu_start(Native Method)
	at com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:304)
	at com.github.unidbg.AbstractEmulator.eFunc(AbstractEmulator.java:404)
	at com.github.unidbg.arm.AbstractARMEmulator.eFunc(AbstractARMEmulator.java:202)
	at com.github.unidbg.linux.LinuxModule.emulateFunction(LinuxModule.java:207)
	at com.github.unidbg.linux.LinuxModule.callFunction(LinuxModule.java:184)
	at com.github.unidbg.linux.LinuxSymbol.call(LinuxSymbol.java:27)
	at com.github.unidbg.linux.android.dvm.DalvikModule.callJNI_OnLoad(DalvikModule.java:30)
	at org.telegram.messenger.Utilities32.<init>(Utilities32.java:48)
	at org.telegram.messenger.Utilities32.main(Utilities32.java:59)
Find native function Java_org_telegram_messenger_Utilities_aesCbcEncryptionByteArray([B[B[BIIII)V => unicorn@0x40190c50[libtmessages.29.so]0x190c50

DalvikModule dm = vm.loadLibrary(new File("src/test/resources/example_binaries/armeabi-v7a/libtmessages.29.so"), false);
dm.callJNI_OnLoad(emulator);     //这一句报错的。啥也没改。只是跑一下例子看下效果

**Comment by zhkl0228** [comment]
我用最新代码测试没问题

**Comment by dqzg12300** [comment]
哦哦。更新到最新版本测试正常了。
